Use docker-layer cache
moodlehq/moodleapp pull request #2631
Opened 2020-11-28 22:04 UTC by LetsMelon

Docker can cache each individual layer. 
If a layer changes, each subsequent layer is repeated. A file change counts as a change and therefore it is stupid to install the libraries after everything has been copied. Furthermore, they should be installed using ```npm ci```, otherwise ```package-lock.json``` will be ignored and errors may occur as a result.

2020-12-01 10:37 UTC, NoelDeMartin requested changes
I think that's it, once you fix that we can merge your changes :) Thanks!

2020-12-01 10:37 UTC, NoelDeMartin commented on Dockerfile
> +RUN rm -rf /root/.npmCOPY . /app
I think you're missing a newline here, right? It should be:

```dockerfile
# Delete caches.
RUN rm -rf /root/.npm
COPY . /app
```

2020-12-01 11:47 UTC, LetsMelon commented on Dockerfile
> +RUN rm -rf /root/.npmCOPY . /app
Oh thanks, I'll fix this quickly.

2020-12-01 12:07 UTC, NoelDeMartin approved these changes

2020-12-01 19:45 UTC, LetsMelon commented
Thanks!

2020-12-09 08:30 UTC, LetsMelon commented
What's the status?

2020-12-09 22:17 UTC, moodlemobile commented
hi there, the original author of that file has provided this feedback:

1. You should be copying the package.lock file before running npm ci not just the Json file
2. I would keep the npm ci and rm commands on the same RUN to prevent the layer from increasing in size unnecessarily. That’s why we were doing that in the first place

2021-04-27 15:52 UTC, NoelDeMartin commented
Hey @LetsMelon thanks for your contribution!

We are working on a new version of the app in the [ionic5](https://github.com/moodlehq/moodleapp/tree/ionic5) branch, and since I've had to update the docker file I applied your suggestions there. I've added you as a co-author in a commit in this PR: #2725.

2021-04-27 15:52 UTC, closed without merging

2021-04-27 16:48 UTC, LetsMelon commented
@NoelDeMartin Thank you!