Mobile 3744
moodlehq/moodleapp pull request #2729
Opened 2021-04-29 08:43 UTC by crazyserver

2021-04-29 09:24 UTC, NoelDeMartin requested changes
I've spotted some things to fix but overall it's good to go.

One comment I have regarding the approach to accessibility is that we should talk about implementing accessible components, instead of having to indicate all the accessibility attributes in pages. There is a lot of repetition going around, and it's very easy for a developer to forget some of these when they are working on a page.

2021-04-29 09:24 UTC, NoelDeMartin commented on src/addons/calendar/components/calendar/addon-calendar-calendar.html
> +                        <a *ngIf="index < 3 || day.filteredEvents.length == 4" class="addon-calendar-event"
Is it ok to replace this with an anchor? I'm not sure if an anchor without an href attribute is valid markup, maybe we should use an unstyled button instead.

2021-04-29 09:24 UTC, NoelDeMartin commented on src/addons/calendar/pages/edit-event/edit-event.html
> +            <ion-item-divider class="ion-text-wrap core-expandable" (click)="toggleAdvanced()"
This isn't part of this issue, but I'll say it to keep in mind for later. This divider is not accessible because it cannot be focused and it doesn't have a role="button" (it should also respond to ENTER/SPACE keyboard, not just clicks). This happens in other places, so we should review that all click listeners are accessible.

2021-04-29 09:24 UTC, NoelDeMartin commented on src/core/features/editor/components/rich-text-editor/core-editor-rich-text-editor.html
>                  (mousedown)="mouseDownAction($event)" [title]="'core.editor.h3' | translate">
The title on these buttons should be converted to aria-label. I'm not sure if this is part of this issue, but since it's been done in other parts of the commit I'm mentioning it.

2021-04-29 09:24 UTC, NoelDeMartin commented on src/addons/messages/pages/group-conversations/group-conversations.html
> +                    [attr.aria-expanded]="favourites.expanded" role="heading">
Is it ok to use role="heading" here? This has a click listener, so I think it should be role="button", be focusable and react to ENTER/SPACE keyboard.

2021-04-29 09:24 UTC, NoelDeMartin commented on src/addons/mod/chat/pages/sessions/sessions.html
> +                [attr.aria-current]="sessions.isSelected(session) ? 'page' :  'false'"
Given that this pattern is so common when using a CorePageItemsListManager, I think we could create a new function that returns the `aria-current` value for an avoid the need to write a ternary every time.

2021-04-29 09:24 UTC, NoelDeMartin commented on src/core/features/grades/pages/courses/courses.html
> +                    [attr.aria-current]="courses.isSelected(course) ? 'page' :  'false'"
There is another CSS rule for selected items down this file that also needs to be updated.

2021-04-29 10:01 UTC, crazyserver commented on src/addons/calendar/pages/edit-event/edit-event.html
> +            <ion-item-divider class="ion-text-wrap core-expandable" (click)="toggleAdvanced()"
I will include the usage of button property in ion-items and similar tags to make them tappable. I think ion-item-divider does not have button property, so probably I have to use aria roles.

2021-04-29 10:02 UTC, crazyserver commented on src/core/features/editor/components/rich-text-editor/core-editor-rich-text-editor.html
>                  (mousedown)="mouseDownAction($event)" [title]="'core.editor.h3' | translate">
Yep, I will take care of that, this is not an ion-button but a native button, I'll check if title does the trick.

2021-04-29 10:03 UTC, crazyserver commented on src/addons/messages/pages/group-conversations/group-conversations.html
> +                    [attr.aria-expanded]="favourites.expanded" role="heading">
Probably it needs both roles. heading role is needed to apply aria-expanded.

2021-04-29 10:04 UTC, crazyserver commented on src/addons/mod/chat/pages/sessions/sessions.html
> +                [attr.aria-current]="sessions.isSelected(session) ? 'page' :  'false'"
Good catch, I'll have a look

2021-04-29 12:14 UTC, crazyserver commented on src/core/features/editor/components/rich-text-editor/core-editor-rich-text-editor.html
>                  (mousedown)="mouseDownAction($event)" [title]="'core.editor.h3' | translate">
Finally title is better than aria-label in this case, it will define an accessible name and also show a tooltip.
+info https://dev.opera.com/articles/ux-accessibility-aria-label/#accessible-name-calculation

2021-04-29 15:58 UTC, NoelDeMartin requested changes
I found a couple more things, but we can proceed by fixing typos and checking the rest in other issues.

2021-04-29 15:58 UTC, NoelDeMartin commented on src/core/classes/page-items-list-manager.ts
> +    getSelectedAriaCurrent(item: Item): string {
I think this should be called `getItemAriaCurrent` instead, or some other variation that does not include the concept of "selected". This is because we'll call this method for all items, and the fact that the returned value is different for selected items is an implementation detail.

Also, I've been looking at [the spec](https://www.w3.org/TR/wai-aria-1.1/#aria-current) for `aria-current` and it doesn't make any reference to "roles", so the value of this attribute is not a role (so the function docs should not mention it either).

2021-04-29 15:58 UTC, NoelDeMartin commented on src/addons/mod/forum/pages/new-discussion/new-discussion.html
> +                [attr.aria-label]="(advanced ? 'core.hideadvanced' : 'core.showadvanced') |translate" role="heading button">
We're using two roles here: heading and button. It seems like it's not possible to use more than one role per element. According to [this spec](https://www.w3.org/TR/2014/REC-wai-aria-implementation-20140320/#mapping_role), it is a valid attribute value but multiple roles will only work as fallback, not all at once.

2021-04-29 15:58 UTC, NoelDeMartin commented on src/core/features/grades/pages/grade/grade.html
> +                    [alt]="grade.iconAlt" role="presentation">
Using a role="presentation" here will hide this image from screen readers, but it has an alt attribute. Was that your intention or is this just a typo? I'm asking to make sure because in all other instances with role="presentation" we're using alt="", unless I missed something.

2021-04-29 15:58 UTC, NoelDeMartin commented on src/addons/calendar/components/calendar/addon-calendar-calendar.html
> +                            (click)="eventClicked(event, $event)" [class.addon-calendar-event-divast]="event.ispast">
I think this is a typo, you didn't mean to change `addon-calendar-event-past` to `addon-calendar-event-divast`.

2021-04-29 15:58 UTC, NoelDeMartin commented on src/addons/mod/forum/components/post/post.html
> +                [attr.aria-label]="(advanced ? 'core.hideadvanced' : 'core.showadvanced') |translate" role="button">
This may not be part of this issue but just for the record, even if this element has the "button" role it still not accessible because it doesn't receive focus, and so cannot react to keyboard events. We can look into this in [MOBILE-3753](https://tracker.moodle.org/browse/MOBILE-3753), but keep it in mind.

2021-05-03 08:10 UTC, crazyserver commented on src/core/features/grades/pages/grade/grade.html
> +                    [alt]="grade.iconAlt" role="presentation">
Good catch thanks!

2021-05-03 08:10 UTC, crazyserver commented on src/addons/calendar/components/calendar/addon-calendar-calendar.html
> +                            (click)="eventClicked(event, $event)" [class.addon-calendar-event-divast]="event.ispast">
True thx!

2021-05-03 08:11 UTC, crazyserver commented on src/addons/mod/forum/components/post/post.html
> +                [attr.aria-label]="(advanced ? 'core.hideadvanced' : 'core.showadvanced') |translate" role="button">
That's right! We'll have a look then

2021-05-03 08:12 UTC, crazyserver commented on src/addons/mod/forum/pages/new-discussion/new-discussion.html
> +                [attr.aria-label]="(advanced ? 'core.hideadvanced' : 'core.showadvanced') |translate" role="heading button">
As a fallback will be ok, because anyway I would leave it as heading. We'll have to add keyboard focus on following issues

2021-05-03 08:26 UTC, crazyserver commented
Thanks Noel. I removed the presentation role on img tag on grade, also solved the typo on calendar and changed the aria current function and jsdoc.

2021-05-03 08:35 UTC, NoelDeMartin commented on src/addons/mod/forum/pages/new-discussion/new-discussion.html
> +                [attr.aria-label]="(advanced ? 'core.hideadvanced' : 'core.showadvanced') |translate" role="heading button">
Ok, I'm going forward with the merge because buttons are not the focus of this issue. But I think this will be a problem, because if it has a click listener it should have a button role, not heading. If it's really serving as both I guess we should use two separate elements, I'm not sure. Let's check it out on the issue about buttons.

2021-05-03 08:41 UTC, NoelDeMartin approved these changes

2021-05-03 08:42 UTC, merged