MOBILE-3750: Improve accessibility of horizontal scrolls
moodlehq/moodleapp pull request #2762
Opened 2021-05-13 11:00 UTC by NoelDeMartin

2021-05-14 08:25 UTC, crazyserver requested changes
Hi Noel!

Changes are ok, but I found that RTL is not supported:
You'll need to flip the buttons order. You can easily do that using flex instead of inline block. I think it will be automatically reversed.

2021-05-17 14:55 UTC, NoelDeMartin commented
Thanks @crazyserver for the review, good catch I didn't think about RTL at all. Other than that, I've also done a rebase and fixed a bug where multiple instances of a component with an horizontal scroll wouldn't work properly. Please take another look.

2021-05-17 15:10 UTC, crazyserver approved these changes

2021-05-17 15:10 UTC, crazyserver commented on src/addons/block/recentlyaccessedcourses/components/recentlyaccessedcourses/recentlyaccessedcourses.ts
> +        const scrollId = CoreUtils.getUniqueId('AddonBlockStarredCoursesComponent-Scroll');
You are using AddonBlockStarredCoursesComponent on AddonBlockRecentlyAccessedCoursesComponent

2021-05-17 15:24 UTC, merged