Mobile 3761
moodlehq/moodleapp pull request #2794
Opened 2021-05-27 07:08 UTC by dpalou

2021-05-27 09:59 UTC, NoelDeMartin requested changes
I found one improvement and a small fix, other than that I think it's pretty much ready for merging.

2021-05-27 09:59 UTC, NoelDeMartin commented on src/core/constants.ts
> +    iosopenfilepicker?: boolean;
We were using all lowercase characters for historical purposes, but now that we already have camel cased properties, could we call this one `iOSOpenFilePicker` instead?

Other than that, what do you think of using a string instead of a boolean here? We could call it something like `defaultFilePickerAction` and it could have the values "open" or "open-with" (iOS only). I think the code would be more readable because you would see something like `openFile('open');' and `openFile('open-with');`.

In any case, these are just suggestions so feel free to apply the ones you like.

2021-05-27 09:59 UTC, NoelDeMartin commented on src/core/components/local-file/core-local-file.html
> +            <ng-container *ngIf="manage">
This ng-container is unnecessary, given that this is already inside of a div with the same `ngIf` condition.

2021-05-27 11:21 UTC, dpalou commented on src/core/components/local-file/core-local-file.html
> +            <ng-container *ngIf="manage">
Nice catch, I forgot to remove the ngIf from the parent div.

2021-05-27 11:21 UTC, dpalou commented on src/core/constants.ts
> +    iosopenfilepicker?: boolean;
I added a new commit with these changes.

2021-05-28 10:11 UTC, crazyserver approved these changes

2021-05-28 10:11 UTC, merged