MOBILE-3320: Support alerts on top of loading
moodlehq/moodleapp pull request #2795
Opened 2021-05-27 08:06 UTC by NoelDeMartin

2021-05-28 06:54 UTC, dpalou requested changes
Hi Noel, I added a couple of comments in the code but I also want to comment the general approach of supporting alerts on top of loading. Couldn't you just put a higher z-index to the alerts so they're displayed on top of the loading modals?

2021-05-28 06:54 UTC, dpalou commented on src/core/classes/ion-loading.ts
> +            return;
Shouldn't you call the dismiss listeners even if the modal is paused or hasn't been displayed yet? Otherwise some listeners might never be called.

BTW I found a bit hard to understand the code at first, maybe it would be nice to include some comments like "No need to dismiss the modal if it's paused since it's already hidden" and things like that.

2021-05-28 06:54 UTC, dpalou commented on src/core/services/utils/dom.ts
> +        await alert.onDidDismiss();
Do we really want to wait for the modal to be dismissed? The function name and JSDoc doesn't say anything about it. Currently we never wait for this function to be resolved so this change shouldn't break anything, just saying.

2021-05-28 07:13 UTC, dpalou commented on src/core/services/utils/dom.ts
> +        await alert.onDidDismiss();
Ok, I've just seen the result will be used now, so ignore this comment.

2021-05-31 08:19 UTC, NoelDeMartin commented on src/core/classes/ion-loading.ts
> +            return;
Thanks for spotting that, you're right we should call the listeners here as well, I fixed it now.

I also added a new comment explaining the purpose of the pause/resume.

2021-05-31 08:22 UTC, NoelDeMartin commented
Thanks for the review @dpalou, I suppose it would be possible to use the z-index approach but I decided to do it this way because stacking modals on top of one another makes the overlay ever darker. With this approach, every time a modal is displayed the previous modal will be hidden visually but remain active conceptually, which I think makes better UX.

2021-05-31 08:35 UTC, dpalou approved these changes

2021-05-31 08:35 UTC, merged