MOBILE-3320 core: Change some icons to fontawesome
moodlehq/moodleapp pull request #2804
Opened 2021-06-01 14:15 UTC by crazyserver

2021-06-01 14:31 UTC, dpalou requested changes

2021-06-01 14:31 UTC, dpalou commented on src/core/features/sitehome/pages/index/index.html
> +            <core-empty-box *ngIf="!hasContent" icon="fas-qrcode" [message]="'core.course.nocontentavailable' | translate">
IIRC the qr-scanner icon wasn't a qrcode, it was a square with some missing parts, like the one used by scanner apps to indicate the area where to put the QR code. So IMO we should find another icon for these cases instead of qrcode.

2021-06-02 08:18 UTC, crazyserver commented on src/core/features/sitehome/pages/index/index.html
> +            <core-empty-box *ngIf="!hasContent" icon="fas-qrcode" [message]="'core.course.nocontentavailable' | translate">
True! I've replaced that with an open box (on 2 places).

2021-06-02 09:08 UTC, dpalou approved these changes

2021-06-02 09:08 UTC, merged