MOBILE-3320: Forum improvements
moodlehq/moodleapp pull request #2814
Opened 2021-06-08 09:34 UTC by NoelDeMartin

2021-06-08 10:56 UTC, dpalou requested changes

2021-06-08 10:56 UTC, dpalou commented on src/addons/mod/forum/components/index/index.ts
> +        return super.loaded && (!CoreApp.isOnline() || this.onlineLoaded || this.fetchFailed);
I think the CoreApp.isOnline() condition shouldn't be here. When the user is offline we can still load online discussions (if they're cached), so the app would display the contents before the cached data is displayed.

2021-06-08 15:42 UTC, NoelDeMartin commented on src/addons/mod/forum/components/index/index.ts
> +        return super.loaded && (!CoreApp.isOnline() || this.onlineLoaded || this.fetchFailed);
Thanks for spotting that, while looking at this I noticed there was another bug; when the online discussions array was empty `onlineLoaded` wouldn't ever be set to `true`, so that's probably what tripped me up doing some tests before. I also fixed it so it should be fine now.

2021-06-09 06:10 UTC, dpalou approved these changes

2021-06-09 06:10 UTC, merged