MOBILE-3320: Fix regressions
moodlehq/moodleapp pull request #2850
Opened 2021-06-23 15:50 UTC by NoelDeMartin

The last commit in particular fixes database templates, that were broken in [this commit](https://github.com/moodlehq/moodleapp/commit/49f6cc56e55a503c696102946f73a4b3b96be0f5#diff-23f88613aff553b7ff16c3c2f1541eca6be80af122be539ce36247a0b6fec225R661), and I think it was a mistake done by using global replacements.

The fix may undo the a11y improvements that were introduced in that commit, but the proper solution would involve making a regex that captures the whole link (including contents and closing tag) and replacing it for a button. I think that's too risky at this stage, so it's better to just revert it to what we had before and revisit this issue later on, when we review a11y for the database activity.

2021-06-25 06:17 UTC, dpalou requested changes

2021-06-25 06:17 UTC, dpalou commented on src/addons/mod/forum/pages/discussion/discussion.html
> +            [priority]="500" [content]="'addon.mod_forum.modeflatoldestfirst' | translate" iconAction="fa-arrow-down"
We should use "fas" or "far" icons instead of "fa". I think that right now we default to "fas" if you use "fa".

2021-06-28 09:21 UTC, NoelDeMartin commented on src/addons/mod/forum/pages/discussion/discussion.html
> +            [priority]="500" [content]="'addon.mod_forum.modeflatoldestfirst' | translate" iconAction="fa-arrow-down"
Thanks for the review, I added a new commit updating all the `fa-` to `fas-` across the app to keep it consistent.

2021-06-28 09:29 UTC, dpalou approved these changes

2021-06-28 09:30 UTC, merged