MOBILE-3833 mod: Create a base module to remove duplicated getData func
moodlehq/moodleapp pull request #2941
Opened 2021-09-09 08:30 UTC by crazyserver

2021-09-09 09:07 UTC, dpalou requested changes

2021-09-09 09:07 UTC, dpalou commented on src/addons/mod/lti/services/handlers/module.ts
> +        const data = super.getData(module, courseId, sectionId, forCoursePage);
This module didn't define showDownloadButton before, with this change it will be set to true when it shouldnt.

2021-09-09 13:09 UTC, crazyserver commented on src/core/features/course/services/module-delegate.ts
> +    getIconSrc?(module: CoreCourseWSModule): string | undefined;
Ooops, yep sorry

2021-09-09 13:09 UTC, crazyserver commented on src/core/features/course/classes/module-base-handler.ts
> +            mainPageName: this.pageName,
Got it!

2021-09-09 13:09 UTC, crazyserver commented on src/addons/mod/wiki/services/handlers/module.ts
> +    protected pageName = AddonModWikiModuleHandlerService.PAGE_NAME;
Ok, so discarding some changes from wiki. I didn't realised about the path

2021-09-09 13:10 UTC, crazyserver commented on src/addons/mod/lti/services/handlers/module.ts
> +        const data = super.getData(module, courseId, sectionId, forCoursePage);
OK, showDownloadButton false again

2021-09-09 13:55 UTC, dpalou commented on src/addons/mod/wiki/services/handlers/module.ts
> +    protected pageName = AddonModWikiModuleHandlerService.PAGE_NAME;
Actually, I guess the right approach would be to just add a redirect in the wiki routes. Can you please verify if it works?

2021-09-09 15:06 UTC, crazyserver commented on src/addons/mod/wiki/services/handlers/module.ts
> +    protected pageName = AddonModWikiModuleHandlerService.PAGE_NAME;
OK done!!!

2021-09-13 10:23 UTC, dpalou requested changes

2021-09-13 10:57 UTC, merged