MOBILE-3833 forum: Fix discussion link navigation
moodlehq/moodleapp pull request #2964
Opened 2021-09-30 14:52 UTC by crazyserver

2021-10-01 06:09 UTC, dpalou requested changes

2021-10-01 06:09 UTC, dpalou commented on src/addons/mod/forum/services/handlers/discussion-link.ts
> -                    cmId: data?.cmid && parseInt(data.cmid, 10),
I think you should keep the cmId and courseId params when using the discussion path, that way if one of them is set (but not both) the page will get the param that is set.

2021-10-01 07:59 UTC, crazyserver commented on src/addons/mod/forum/services/handlers/discussion-link.ts
> -                    cmId: data?.cmid && parseInt(data.cmid, 10),
Thanks Dani ! I thought the same but then I just thought it was difficult to have it one or the other. Fixed

2021-10-04 05:33 UTC, dpalou approved these changes

2021-10-04 05:33 UTC, merged