Mobile 3807
moodlehq/moodleapp pull request #2983
Opened 2021-10-29 12:46 UTC by crazyserver

2021-11-02 13:51 UTC, dpalou requested changes

2021-11-02 13:51 UTC, dpalou commented on src/core/features/login/components/sites/sites.html
> +                <ion-item button (click)="login($event, site.id)" *ngFor="let site of accountsList.sameSite" detail="true">
The HTML for sites in sameSite and otherSites is the same, you can use an ng-template to avoid duplicating all the HTML.

2021-11-02 13:51 UTC, dpalou commented on src/core/features/login/services/login-helper.ts
> +            await CoreSites.logout();
I think it would be better to stop the execution when there are site plugins instead of navigating to login/sites after logout. Otherwise it can happen that the navigation is performed before the app is refreshed, and navigating to login can consume the redirect that you have just stored. Usually when we do logout and there are site plugins we don't do anything else, we just wait for the app to be refreshed.

2021-11-02 13:51 UTC, dpalou commented on src/core/features/login/services/login-helper.ts
> +        let params: Params = { openAddSite: true , showKeyboard };
The "openAddSite" can probably be implemented using the "nextNavigation" introduced recently in the navigator. But since it's something that already exists you can leave it like it is if you prefer.

2021-11-02 13:51 UTC, dpalou commented on src/core/features/login/components/sites/sites.html
> +                            <core-format-text [text]="sites[0].siteName" clean="true" [siteId]="sites[0].id"></core-format-text>
You're assuming that each list of sites will have a first element, and looking at the implementation of getAccountsList and deleteAccountFromList it will. But this could change in the future, IMO it would be better to verify that sites[0] exists so it doesn't break so easily.

The same happens in sites.html.

2021-11-02 13:52 UTC, dpalou commented
Along with the comments above, I think the commit name "Add some delegates to user menu" is wrong, you're adding handlers, not delegates.

2021-11-02 14:47 UTC, crazyserver commented on src/theme/globals.variables.scss
> +// Configuration options for more page. (deprecated)
ok!! thx!

2021-11-02 14:48 UTC, crazyserver commented on src/addons/privatefiles/services/handlers/user.ts
> +        // All course grades only available for the current user.
Nice catch, thanks!

2021-11-02 15:12 UTC, crazyserver commented on src/core/features/login/components/sites/sites.html
> +                <ion-item button (click)="login($event, site.id)" *ngFor="let site of accountsList.sameSite" detail="true">
Done!

2021-11-02 15:30 UTC, crazyserver commented on src/core/features/login/services/login-helper.ts
> +        let params: Params = { openAddSite: true , showKeyboard };
I will leave it as it is. Thanks!!

2021-11-02 15:30 UTC, crazyserver commented on src/core/features/mainmenu/components/user-menu/user-menu.html
> +            </ion-item>
Solved in lastest commit

2021-11-03 06:29 UTC, dpalou approved these changes

2021-11-03 06:29 UTC, merged