Mobile 3833
moodlehq/moodleapp pull request #2993
Opened 2021-11-12 12:07 UTC by crazyserver

2021-11-12 13:38 UTC, dpalou requested changes

2021-11-12 13:38 UTC, dpalou commented on src/addons/block/starredcourses/components/starredcourses/starredcourses.ts
> +        // @TODO: Sort won't coincide with website because timemodified is not informed.
You can probably use block_starredcourses_get_starred_courses.

2021-11-12 13:38 UTC, dpalou commented on src/core/services/sites.ts
> -    async getSortedSites(ids?: string[]): Promise<CoreSiteBasicInfo[]> {
I'd keep this parameter. We use it in getSites for certain cases, maybe in the future we want to get a sorted list in those same use cases.

2021-11-12 13:44 UTC, crazyserver commented on src/core/services/sites.ts
> -    async getSortedSites(ids?: string[]): Promise<CoreSiteBasicInfo[]> {
DOne

2021-11-12 13:44 UTC, crazyserver commented on src/addons/block/starredcourses/components/starredcourses/starredcourses.ts
> +        // @TODO: Sort won't coincide with website because timemodified is not informed.
Opened MOBILE-3923 as a follow up

2021-11-15 07:02 UTC, dpalou approved these changes

2021-11-15 07:02 UTC, merged