Mobile 3806
moodlehq/moodleapp pull request #3005
Opened 2021-11-24 14:09 UTC by crazyserver

2021-11-24 21:48 UTC, crazyserver commented
Checks passed, I'm removing Workaround commit (will fail checks)

2021-11-25 09:57 UTC, dpalou requested changes

2021-11-25 09:57 UTC, dpalou commented on src/core/features/courses/components/course-progress/course-progress.ts
>              component: CoreCoursesCourseOptionsMenuComponent,
Shouldn't you deprecate the course-progress class?

2021-11-25 09:57 UTC, dpalou commented on src/core/features/courses/pages/my/my.html
> +        <!-- Programs blocks. -->
I think this comment is wrong.

2021-11-25 09:57 UTC, dpalou commented on src/core/features/courses/pages/my/my.module.ts
> +            redirectTo: 'index',
You're redirecting to "index", but you only declare the paths "" and "list" so I guess this will fail, right?

2021-11-25 09:57 UTC, dpalou commented on src/core/features/courses/pages/my/my.ts
> +            this.block.invalidate().catch(() => {
The "doRefresh" function already invalidates the data, no need to do it twice. Also, you can use async/await and CoreUtils.ignoreErrors here to make it more readable.

2021-11-25 09:57 UTC, dpalou commented on src/core/features/courses/services/courses-helper.ts
> +     * @deprecated since 4.0, use single loadCourseColorAndImage instead.
I wouldn't deprecate this. The function is still valid and useful, even if we don't use it right now.

2021-11-25 09:57 UTC, dpalou commented on src/core/features/courses/services/courses-helper.ts
> +            await CoreCourses.getCoursesByField('ids', courseIds).then((coursesInfos) => {
Since you're using await you can remove the "then" part and use await properly.

2021-11-25 10:55 UTC, crazyserver commented on src/core/features/courses/components/course-list-item/core-courses-course-list-item.html
> +                        <span class="sr-only">{{ 'core.courses.aria:coursecategory' | translate }}</span>
Nice catch!

2021-11-25 10:55 UTC, crazyserver commented on src/core/features/courses/components/course-list-item/core-courses-course-list-item.html
> +                    <p *ngIf="course.categoryname || (course.displayname && course.shortname && course.fullname != course.displayname)"
Done!

2021-11-25 10:56 UTC, crazyserver commented on src/core/features/courses/components/course-list-item/course-list-item.ts
> +    async deleteCourse(): Promise<void> {
That right, changed

2021-11-25 10:58 UTC, crazyserver commented on src/core/features/courses/components/course-list-item/course-list-item.ts
> +            if (CoreDomUtils.isCanceledError(error)) {
Right, this was copied from course progress, I solved there too.

2021-11-25 10:59 UTC, crazyserver commented on src/core/features/courses/components/course-list-item/course-list-item.ts
> +                if (this.courseStatus == 'downloaded' || this.courseStatus == 'outdated') {
Also solved on course-progress

2021-11-25 11:00 UTC, crazyserver commented on src/core/features/courses/components/course-progress/course-progress.ts
>              component: CoreCoursesCourseOptionsMenuComponent,
Done!

2021-11-25 11:16 UTC, crazyserver commented on src/core/features/courses/services/courses-helper.ts
> +            await CoreCourses.getCoursesByField('ids', courseIds).then((coursesInfos) => {
nice cathc, thanks

2021-11-26 10:34 UTC, dpalou approved these changes

2021-11-26 10:34 UTC, merged