Mobile 3927
moodlehq/moodleapp pull request #3021
Opened 2021-12-13 08:48 UTC by dpalou

2021-12-13 17:34 UTC, NoelDeMartin requested changes
Well, I wrote a lot of comments but most of them are about code style and architecture, I actually don't think I found any real issue (other than some related with CSS). Let me know what you think about them.

2021-12-13 17:34 UTC, NoelDeMartin commented on src/core/classes/items-management/slides-dynamic-items-manager-source.ts
> +    async loadItem(item: Partial<Item>): Promise<void> {
Looking at the dynamic items manager, I think the concept of dynamic items and "unloaded items" has been conflated. What I mean with this is that the dynamic nature of this list makes reference to not all items being available in a list, given that it's theoretically an infinite list. However, the fact that items need to be loaded by themselves is not related with this. For example, if we had a calendar without any events or any data tied to each month, items would just be year/month, and we wouldn't need to load them individually. I think this is also part of the reason for the partial items I mentioned earlier. Is it too late to decouple these two concepts? We could also make reusable code for items that need to be loaded individually, but that code doesn't need to be in this class. Items can also have their own classes and inheritance, they don't always need to be plain JS objects. So this method could be replaced whenever it's called in the code with `item.load()` instead.

2021-12-13 17:34 UTC, NoelDeMartin commented on src/addons/calendar/components/calendar/calendar.ts
> +    monthLoaded = false;
Would it be possible to remove this and calculate it from the selected item instead?

2021-12-13 17:34 UTC, NoelDeMartin commented on src/addons/calendar/components/calendar/calendar.ts
> +            const isCurrentMonth = CoreTimeUtils.isSameMonth(month, CoreTimeUtils.getCurrentMonth());
Instead of recalculating this every time it's necessary, would it be easier to encode this information into each item? For example, we could have `month.isCurrent`, `month.isPrevious`, etc. as booleans.

2021-12-13 17:34 UTC, NoelDeMartin commented on src/addons/calendar/pages/day/day.page.ts
> +    protected categoriesRetrieved = false;
Instead of tracking this separately, could we just define `categories` as null and check whether categories have been retrieved or not from the status of that property?

2021-12-13 17:34 UTC, NoelDeMartin commented on src/addons/calendar/components/calendar/calendar.ts
>      loaded = false;
I think this property could be removed and inferred from the status of the manager.

2021-12-13 17:34 UTC, NoelDeMartin commented on src/addons/calendar/components/calendar/calendar.ts
> +                            AddonCalendar.scheduleEventsNotifications(day.eventsFormated || []);
I think this isn't related to this commit, but I want to make sure of something. How come this code is registered here? It seems like scheduling of events is not something that should be tied to a page being focused or not. If the default notification changes from another screen or any other service, we would want this to be called as well, right? So why not set this listener up in a service instead and decouple it from this page being present?

2021-12-13 17:34 UTC, NoelDeMartin commented on src/addons/calendar/pages/day/day.page.ts
> +        if (deleted) {
Could `deletedItems` be a Set instead of an array? It seems like that would simplify this code and possibly other parts.

2021-12-13 17:34 UTC, NoelDeMartin commented on src/core/classes/items-management/slides-dynamic-items-manager-source.ts
> +        // Not used in dynamic slides.
Instead of doing this, we could make the `load` method abstract instead. In this class, it would be implemented as is (notice that it isn't calling super), and in other managers where `loadItems` is actually necessary we could implement `load` and keep this one as abstract.

2021-12-13 17:34 UTC, NoelDeMartin commented on src/core/classes/items-management/slides-dynamic-items-manager-source.ts
> +            nextItem ? this.loadItemInList(nextItem, true) : undefined,
These can also be written as `item && this.loadItemInList(item, true)` to make them more terse.

2021-12-13 17:34 UTC, NoelDeMartin commented on src/core/classes/items-management/slides-items-manager-source.ts
> +        const index = this.getItemPosition(item);
In relation with some of my previous comments, this method is confusing. Should it be called `getItemById` and expect an id instead?

Just looking at the documentation and method signature, it gives the false impression that you can pass any partial fields of the item. Whereas in reality, it only works with the fields necessary to get the id.

2021-12-13 17:34 UTC, NoelDeMartin commented on src/core/classes/items-management/slides-items-manager-source.ts
> +    abstract getItemId(item: Partial<Item>): string | number;
This declaration is misleading, it declares that any partial item is accepted, but then implementations override the declaration with incompatible signatures (it may be related with some Typescript strict settings we are not using). For example, `{}` is a partial month, but the item in the calendar manager is declared as `getItemId(item: YearAndMonth)` which isn't valid.

2021-12-13 17:34 UTC, NoelDeMartin commented on src/core/components/swipe-slides/swipe-slides.html
> +    <ion-slide *ngFor="let item of manager.getSource().getItems()">
`manager.getSource().getItems()` could be encapsulated in an `items` getter, like it's already happening in the list manager (same for the `manager.getSource().isLoaded()` above).

2021-12-13 17:34 UTC, NoelDeMartin commented on src/core/services/utils/dom.ts
> +    isElementOutsideOfScreen(scrollEl: HTMLElement, element: HTMLElement, point: 'top' | 'mid' | 'bottom' = 'mid'): boolean {
I think this `point` argument should be declared as an enum instead. That way, the code below can also be implemented using a switch statement without a default case which is more type-safe, performant, and easier to understand.

2021-12-13 17:34 UTC, NoelDeMartin commented on src/core/classes/items-management/slides-dynamic-items-manager-source.ts
> +    markAllItemsUnloaded(): void {
Aside from the fact that items don't have to be dirty/loaded as I mentioned in a previous comment, I'm not sure if we need to track `loaded` with a property. Dirtyness is already the concept that something exists, but the data must be updated. Loaded, as I understand it, should be a state derived from the existance of other state, so technically it shouldn't be set unless it's necessary to optimize performance. In this case, I think dirtyness already does the same job, or am I missing something?

2021-12-13 17:34 UTC, NoelDeMartin commented on src/core/classes/items-management/items-manager-source.ts
> +    protected notifyItemsUpdated(): void {
I realize this has been extracted to a method because it's called when items are modified in dynamic managers. However, I don't think this should be the case, the items array should only be modified calling the setter (so in dynamic managers, they would create a new array instead of modifying the existing one).

Looking at dynamic managers, I think one of the motivations to do the current approach is that conceptually the array of items is modified, and not creating a new one. But in reality, this array of items is just a collection of items, because the positions don't have a meaning (as exposed by the fact that these change every time we navigate backwards). So I was thinking, maybe a linked list would be more appropriate for those managers. But then it may not be straight-forward to reconcile with this array, and the concept of position/index that is used in other parts of the parent classes. So I guess just calling `setItems` with a new array should suffice, but the idea of a linked list seems more appropriate.

2021-12-13 17:34 UTC, NoelDeMartin commented on src/core/classes/items-management/slides-dynamic-items-manager-source.ts
> +export abstract class CoreSwipeSlidesDynamicItemsManagerSource<Item extends CoreSwipeSlidesDynamicItem>
This file is missing the `swipe-` prefix in the filename, as do all the others starting with `slides-*`.

2021-12-13 17:34 UTC, NoelDeMartin commented on src/core/classes/items-management/swipe-items-manager.ts
>  export class CoreSwipeItemsManager<
This should be renamed to `CoreSwipeNavigationItemsManager`, tying it up with the `CoreSwipeNavigationComponent`. And the file should be called `swipe-navigation-items-manager`.

2021-12-16 14:12 UTC, dpalou commented on src/core/components/swipe-slides/swipe-slides.scss
> +:host {
I rebased the code and it no longer happens, it seems it wasn't related with my code.

2021-12-16 14:12 UTC, dpalou commented on src/addons/calendar/components/calendar/addon-calendar-calendar.html
> +    <core-swipe-slides [manager]="manager" (onWillChange)="slideChanged($event)">
Now the managers notify the change, but I'm using a listener. That way pages only need to register a listener instead of creating a subclass of the manager.

2021-12-16 14:14 UTC, dpalou commented on src/core/components/swipe-slides/swipe-slides.ts
> +    slideToItem(item: Partial<Item>, speed?: number, runCallbacks?: boolean): void {
Now all the methods using items use just Item instead of Partial<Item>. In subclasses, the items basic properties are required, and all the loaded properties are optional.

2021-12-16 14:20 UTC, dpalou commented on src/addons/mod/book/components/index/index.ts
> +    tags?: CoreTagItem[];
Actually, to fix the issue with the partial items I made that Items only require the properties to identify them (in this case, id), so now content will be optional too.

2021-12-16 14:25 UTC, dpalou commented on src/addons/mod/book/components/index/index.ts
> +            const error = exception ?? new CoreError(Translate.instant('addon.mod_book.errorchapter'));
I don't know when it can happen, or if it can even happen right now. But usually when this kind of checks are there it's because we found the issue in the past, looking at the code my guess is that it was related to the download file part.

I changed the code, now it'll just check if the error has a message, and put a message if it didn't.

2021-12-16 14:31 UTC, dpalou commented on src/core/components/swipe-slides/swipe-slides.ts
> +    @Output() onDidChange = new EventEmitter<CoreSwipeCurrentItemData<Item>>();
The onInit output wasn't used, it was used at first but then I refactored the code so I removed it.

2021-12-16 14:32 UTC, dpalou commented on src/core/components/swipe-slides/swipe-slides.ts
> +    getCurrentItem(): Item | null {
I changed it to always use "selected" because in some contexts the word current can be confusing. E.g. if I do:

const month = manager.getCurrentItem();

it could be confusing whether the current month is the month I'm viewing or the actual month we're at.

2021-12-16 14:33 UTC, dpalou commented on src/core/classes/items-management/slides-items-manager-source.ts
> +    getInitialPosition(): number {
Using the word index now.

2021-12-16 14:35 UTC, dpalou commented on src/core/classes/items-management/slides-items-manager-source.ts
> +    protected initialized = false;
I changed it to use the word "loaded", and I moved it to the root class. As we talked in chat, I preferred to use a loaded boolean property instead of refactoring the dynamic slides source to add the items "in block".

2021-12-16 14:39 UTC, dpalou commented on src/addons/calendar/components/calendar/calendar.ts
>      loaded = false;
I could remove the "monthLoaded" one, but this one has a special case where I need it: when the user goes to the current month/day. In this case the user might be going to an item that isn't in the list yet, so I cannot select/get the item. So I use `this.loaded = false` to display a spinner, load the item and then we'll slide to the loaded item.

2021-12-16 14:42 UTC, dpalou commented on src/addons/calendar/components/calendar/calendar.ts
> +                            AddonCalendar.scheduleEventsNotifications(day.eventsFormated || []);
I opened MOBILE-3951 to change this.

2021-12-16 14:45 UTC, dpalou commented on src/core/classes/items-management/slides-dynamic-items-manager-source.ts
> +        // Not used in dynamic slides.
If we make the `load` method abstract in CoreSwipeSlidesItemsManagerSource, then all the classes extending this one will have to implement the load method (e.g. the book manager), and we don't want that. So I left this as it was, we can improve it later if needed.

2021-12-16 14:52 UTC, dpalou commented on src/core/classes/items-management/slides-dynamic-items-manager-source.ts
> +    markAllItemsUnloaded(): void {
I cannot derive the `loaded` from other properties because `CoreSwipeSlidesDynamicItem` doesn't know the properties that are loaded later. So I'd have to move the `markAllItemsUnloaded` method to the pages that need it, making it less reusable.

IMO the advantage of using loaded & dirty is that you can behave differently depending on the case. E.g. in the case of the day page, `loaded=false` means I display a spinner, but I don't when `dirty=true` (because I only use `dirty=true` when the user performs a PTR, and we already have the PTR spinner in that case). I could do it checking if one of the optional properties has been loaded, but then in another similar page I'd have to reimplement it with a different property. I think this way is easier to reuse.

2021-12-16 14:52 UTC, dpalou commented on src/core/classes/items-management/items-manager-source.ts
> +    protected notifyItemsUpdated(): void {
As we talked in chat, I prefer to keep it like this instead of creating a new array every time I want to add an item to the list.

2021-12-16 14:54 UTC, dpalou commented on src/core/components/swipe-slides/swipe-slides.ts
> +        this.options.runCallbacksOnInit = false;
I don't like the idea of having two different option objects, I think it can be confusing. IMO having an overridden option is not a big deal, we can document it as a limitation of our component. And passing extra properties shouldn't be a problem either, it's something that TypeScript accepts.

2021-12-16 14:55 UTC, dpalou commented
Thanks Noel, I fixed most of the things you commented. If I didn't comment on any of the things you mentioned it means I just fixed it, no need to put "Done" everywhere :)

2021-12-20 11:25 UTC, NoelDeMartin requested changes
I found a couple of small things, after fixing those this'll be ready for merging.

2021-12-20 11:25 UTC, NoelDeMartin commented on src/core/classes/items-management/items-manager.ts
> +    // eslint-disable-next-line @typescript-eslint/no-unused-vars
This line can be removed, `items` is not unused anymore.

2021-12-20 11:25 UTC, NoelDeMartin commented on src/addons/calendar/components/calendar/calendar.ts
> +    get isCurrentMonth(): string {
It seems like this has been added by mistake and can be removed.

2021-12-20 13:49 UTC, NoelDeMartin approved these changes

2021-12-20 13:57 UTC, merged