MOBILE-3971: Improve config db performance
moodlehq/moodleapp pull request #3070
Opened 2022-01-25 08:47 UTC by NoelDeMartin

2022-01-25 10:36 UTC, dpalou requested changes

2022-01-25 10:36 UTC, dpalou commented on src/core/classes/database-table.ts
> +     * @param conditions Mathinc conditions or record id.
Typo, it says "Mathinc".

2022-01-25 10:36 UTC, dpalou commented on src/core/classes/database-table.ts
> +    find(conditions: Partial<DBRecord> | string): DBRecord | null  {
Maybe it would be better to have 2 functions, something like _findByPrimaryKey_ and _find_. The first would accept a string the second would accept an object. And the same for the delete function. I think the code will be easier to understand like this.

2022-01-26 08:15 UTC, NoelDeMartin commented on src/core/classes/database-table.ts
> +     * @param conditions Mathinc conditions or record id.
Good catch, I don't know how that happened xD

2022-01-26 08:16 UTC, NoelDeMartin commented on src/core/classes/database-table.ts
> +    find(conditions: Partial<DBRecord> | string): DBRecord | null  {
I have updated this as we've discussed in private.

2022-01-26 10:57 UTC, dpalou approved these changes

2022-01-26 10:57 UTC, merged