Mobile 3976
moodlehq/moodleapp pull request #3077
Opened 2022-01-28 18:13 UTC by crazyserver

2022-02-01 08:03 UTC, NoelDeMartin requested changes
I found a couple of things to improve, but it looks good overall.

2022-02-01 16:09 UTC, crazyserver commented on src/addons/notifications/pages/settings/settings.html
> +        </ng-container>
same :-p

2022-02-01 16:11 UTC, crazyserver commented on src/addons/messages/pages/settings/settings.html
> +                                <ion-toggle *ngIf="!processor.locked" [(ngModel)]="processor[state].checked"
Great catch! fixed

2022-02-01 16:11 UTC, crazyserver commented on src/addons/messages/pages/settings/settings.html
> +                            <ion-toggle *ngIf="!processor.locked" [(ngModel)]="processor.enabled"
Great catch! fixed

2022-02-01 16:11 UTC, crazyserver commented on src/addons/notifications/pages/settings/settings.html
> +                                    <ion-toggle *ngIf="!notification.processorsByName[currentProcessorName].locked"
Great catch! fixed

2022-02-02 09:05 UTC, NoelDeMartin commented on src/addons/messages/pages/settings/settings.html
> +            </ng-container>
I think we didn't understand each other, I meant to say that instead of using templates at all, we could just place the html inline. And if that's too unreadable because we have a lot of code, I think the better way to encapsulate is using components, not templates.

But it's ok, it was just a suggestion so we can leave it as is.

2022-02-02 09:06 UTC, NoelDeMartin approved these changes

2022-02-02 09:06 UTC, merged