MOBILE-3915 course: Align icons on course index
moodlehq/moodleapp pull request #3087
Opened 2022-02-01 11:07 UTC by crazyserver

2022-02-01 11:24 UTC, dpalou requested changes

2022-02-01 11:24 UTC, dpalou commented on src/core/features/course/components/course-index/course-index.ts
> +        this.sectionsToRender = Object.assign([], this.sections);
This instruction doesn't clone each item, only the array. If you add a new item to "sectionsToRender" it won't be added to "sections", but if you modify a section inside "sectionsToRender" it will also be modified inside "sections". So I understand this is wrong.

2022-02-01 12:04 UTC, dpalou submitted a review, later dismissed

2022-02-02 10:43 UTC, crazyserver commented on src/core/features/course/components/course-index/course-index.ts
> +        this.sectionsToRender = Object.assign([], this.sections);
Hi Dani! Check if you like the current solution :-)

2022-02-02 10:53 UTC, dpalou approved these changes

2022-02-02 10:55 UTC, merged