MOBILE-3977: Database optimization strategies
moodlehq/moodleapp pull request #3091
Opened 2022-02-03 13:17 UTC by NoelDeMartin

2022-02-04 09:37 UTC, dpalou requested changes

2022-02-07 13:43 UTC, NoelDeMartin commented on src/core/classes/database/database-table.ts
> +    find(conditions: Partial<DBRecord>): Promise<DBRecord> {
As we've discussed in private I renamed them the `getOne` and `getMany`.

2022-02-07 13:43 UTC, NoelDeMartin commented on src/core/classes/database/lazy-database-table.ts
> +        return super.all(conditions);
Good catch, fixed.

2022-02-07 13:44 UTC, NoelDeMartin commented on src/core/services/sites.ts
> +    protected cacheTables: Record<string, CorePromisedValue<CoreDatabaseTable<CoreSiteWSCacheRecord>>> = {};
Ok, I agree it's too soon to extract anything but it's very likely that we'll eventually need it. I've also added a new DX improvement with something I'm calling a "lazy map", let me know what you think.

2022-02-08 10:06 UTC, dpalou approved these changes

2022-02-08 10:06 UTC, merged