MOBILE-3974 paypal: Open paypal enrol in browser
moodlehq/moodleapp pull request #3107
Opened 2022-02-10 10:41 UTC by dpalou

2022-02-10 16:57 UTC, NoelDeMartin requested changes

2022-02-10 16:57 UTC, NoelDeMartin commented on src/core/features/course/pages/preview/preview.html
> +                        <p class="item-heading">{{ 'core.courses.otherenrolments' | translate }}</p>
It seems like this was the only usage of the `isMobile` property, so it can be removed from the TS file.

2022-02-10 16:57 UTC, NoelDeMartin commented on src/core/features/course/pages/preview/preview.page.ts
> +        this.appResumeSubscription = Platform.resume.subscribe(() => {
This class is missing an `ngOnDestroy` hook to unsubscribe from this.

2022-02-10 16:57 UTC, NoelDeMartin commented on src/core/features/course/pages/preview/preview.page.ts
> +            this.zone.run(async () => {
Can we use the `NgZone` singleton instead?

2022-02-11 06:56 UTC, dpalou commented on src/core/features/course/pages/preview/preview.html
> +                        <p class="item-heading">{{ 'core.courses.otherenrolments' | translate }}</p>
Fixed.

2022-02-11 06:56 UTC, dpalou commented on src/core/features/course/pages/preview/preview.page.ts
> +            this.zone.run(async () => {
Changed.

2022-02-14 08:46 UTC, NoelDeMartin approved these changes

2022-02-14 08:46 UTC, merged