MOBILE-3981: Optimize tables used during startup
moodlehq/moodleapp pull request #3110
Opened 2022-02-10 16:01 UTC by NoelDeMartin

2022-02-14 06:02 UTC, dpalou requested changes

2022-02-14 13:23 UTC, NoelDeMartin commented on src/core/classes/database/eager-database-table.ts
> +                ? Object.values(this.records).find(record => conditions && this.recordMatches(record, conditions))
Thanks, I removed the redundant conditional. I also refactored to using if/else. I'm used to coding in this way because I avoid using `let` as much as possible, and using if/else you need to either use a `let` or extract it into another method. I just used `let` which is more straightforward, even if not as elegant.

2022-02-14 13:27 UTC, NoelDeMartin commented on src/core/classes/database/lazy-database-table.ts
> +        const record = await super.getOne(conditions, options);
Yes, I changed it because I realized a possible bug here. With this query, the value returned from the database should be the first one matching the conditions. However, given that these conditions are not the primary key, it'd be possible to have some value in memory that is actually stored after the first value in the table but is returned from cache. That would cause an inconsistency between the values returned by different database optimizations.

2022-02-14 13:27 UTC, NoelDeMartin commented on src/core/classes/sqlitedb.ts
> +            if (onEmptyItems === null || onEmptyItems === undefined) { // Special case, NULL value.
Ok, I applied your suggestion.

2022-02-14 13:34 UTC, NoelDeMartin commented on src/core/features/pushnotifications/services/pushnotifications.ts
> +                        config: { cachingStrategy: CoreDatabaseCachingStrategy.None },
For this task, I'm just migrating to the new approach tables that are used during start up. This table is not one of them, but since I was updating the pushnotifications service for the other tables that are used during start up, I did it for this one as well. If you think I shouldn't have I can remove it, but given that we'll eventually migrate all the tables to the new approach it shouldn't be an issue.

2022-02-15 07:13 UTC, dpalou commented on src/core/services/sites.ts
> +        await this.migrateCurrentSiteLegacyTable();
Oh ok, you're right, thanks!

2022-02-15 07:13 UTC, dpalou approved these changes

2022-02-15 07:14 UTC, merged