Mobile 3931
moodlehq/moodleapp pull request #3126
Opened 2022-02-17 11:52 UTC by crazyserver

2022-02-17 14:34 UTC, dpalou requested changes

2022-02-17 14:34 UTC, dpalou commented on src/core/features/course/services/course-helper.ts
> -    async contextMenuPrefetch(
Please document the functions removed in upgrade.txt :)

2022-02-17 14:34 UTC, dpalou commented on src/core/features/grades/pages/course/course.page.ts
> +                    CoreUtils.nextTick();
You lack an await here. If it was working, maybe this tick isn't needed.

2022-02-18 10:05 UTC, crazyserver commented on src/core/features/course/classes/main-resource-component.ts
> +                const modal = await CoreDomUtils.showModalLoading();
Great improvement! Thanks!

2022-02-18 10:05 UTC, crazyserver commented on src/core/features/course/services/course-helper.ts
> -    async contextMenuPrefetch(
Added!

2022-02-18 11:07 UTC, merged