MOBILE-3982 core: Refactor collapsible-header
moodlehq/moodleapp pull request #3141
Opened 2022-02-24 16:24 UTC by NoelDeMartin

2022-02-28 11:12 UTC, crazyserver approved these changes

2022-02-28 11:12 UTC, crazyserver commented on src/theme/components/collapsible-header.scss
> +            height: calc(var(--collapsible-header-expanded-height) * (1 - var(--collapsible-header-progress)));
I would not modify the height of any element to avoid flickering. This is also causing that the title is placed over some content text.

2022-02-28 11:12 UTC, crazyserver commented on src/theme/components/collapsible-header.scss
> +            transform: translateY(calc(var(--collapsible-header-title-top-delta) * var(--collapsible-header-progress)));
I think transform: none is always winning this rule so, it's not needed.

2022-02-28 11:12 UTC, crazyserver commented on src/theme/components/collapsible-header.scss
> +            flex-shrink: 0;
Why do we need that?

2022-02-28 11:12 UTC, crazyserver commented on src/theme/components/collapsible-header.scss
> +            overflow: visible;
If we don't set the height this is also not needed

2022-03-01 07:57 UTC, NoelDeMartin commented on src/core/directives/collapsible-header.ts
> +        const collapsedTitleStyles = getComputedStyle(collapsedHeaderTitle);
I think they are still needed because we're using them when the transition is halfway done, so that the change is not so jarring at the end.

2022-03-01 07:58 UTC, NoelDeMartin commented on src/core/directives/collapsible-header.ts
> +            .filter(property => property.startsWith('font-') || property.startsWith('letter-'))
Done.

2022-03-01 08:00 UTC, NoelDeMartin commented on src/core/directives/collapsible-header.ts
> +            Object
As mentioned above, this is intended so that the change is not so jarring at the end.

2022-03-01 08:00 UTC, NoelDeMartin commented on src/theme/components/collapsible-header.scss
> +            height: calc(var(--collapsible-header-expanded-height) * (1 - var(--collapsible-header-progress)));
Thanks, I fixed the issue you mentioned, but this is still needed in some situations (for example, in the course home where the expanded header is outside of the scroll).

2022-03-01 08:05 UTC, NoelDeMartin commented on src/theme/components/collapsible-header.scss
> +            transform: translateY(calc(var(--collapsible-header-title-top-delta) * var(--collapsible-header-progress)));
I have double-checked and it is being used, `transform: none` only applies when the expanded header is sitting within the scroll content.

2022-03-01 08:10 UTC, NoelDeMartin commented on src/theme/components/collapsible-header.scss
> +            overflow: visible;
As mentioned above, we need to set the height in some scenarios.

2022-03-01 08:15 UTC, NoelDeMartin commented
@crazyserver The diffs from history are a bit confusing because I did a couple of force-push, here's the diff since your last review: https://github.com/moodlehq/moodleapp/compare/a7b54534f0cae7a216366494cd63f26fc5e69a47..585f0b7afe9fe702a12ff8c42e1858b299ef0f55

2022-03-01 10:11 UTC, crazyserver requested changes
That's it! I think there are all minor changes :-) Great work!

2022-03-01 10:11 UTC, crazyserver commented on src/theme/components/collapsible-header.scss
> +                @include core-transition(width, 200ms, linear);
You cannot have two rules for the same property. Please use "all" since core-transition is not prepared to have commas on the first variable.

2022-03-01 10:11 UTC, crazyserver commented on src/theme/components/collapsible-header.scss
> +            @include core-transition(height, 200ms, linear);
See comment bellow

2022-03-01 10:11 UTC, crazyserver commented on src/theme/components/collapsible-header.scss
> +                opacity: calc(1 - var(--collapsible-header-progress));
Please add a transition for the opacity here.

2022-03-01 10:34 UTC, NoelDeMartin commented on src/theme/components/collapsible-header.scss
> +    .collapsible-header--expanded .collapsible-header--floating-title {
Ok, I have updated the class names and opened the following issue https://tracker.moodle.org/browse/MOBILE-4004

2022-03-01 10:49 UTC, NoelDeMartin commented on src/core/singletons/components-registry.ts
> +export class CoreComponentsRegistry {
Ok, I have deprecated the old ones and moved this to a separate commit.

2022-03-01 11:11 UTC, NoelDeMartin commented on src/theme/components/collapsible-header.scss
> +                @include core-transition(width, 200ms, linear);
Nice catch, I didn't think about that :sweat_smile: We cannot use `all` because it was causing a flickering when the title is substituted (because it's introduced with opacity: 0 to measure the offset). So what I did is refactor the `core-transition` mixin to accept an array of values, it should be working correctly now.

2022-03-01 11:12 UTC, NoelDeMartin commented on src/theme/components/collapsible-header.scss
> +            @include core-transition(height, 200ms, linear);
Same

2022-03-01 11:12 UTC, NoelDeMartin commented on src/theme/components/collapsible-header.scss
> +                opacity: calc(1 - var(--collapsible-header-progress));
Done.

2022-03-01 11:16 UTC, crazyserver approved these changes

2022-03-01 13:07 UTC, merged