Mobile 3814
moodlehq/moodleapp pull request #3193
Opened 2022-03-21 10:55 UTC by crazyserver

2022-03-21 11:41 UTC, dpalou requested changes

2022-03-21 11:41 UTC, dpalou commented on src/core/features/course/components/course-format/course-format.ts
> +        if (!CoreCourseHelper.canUserViewModule(module, section) && module.handlerData?.action) {
I think you shouldn't negate the return of the function, right? This if checked that uservisible was NOT false, it means the user can view the module.

2022-03-21 11:41 UTC, dpalou commented on src/core/features/course/services/course-helper.ts
> +     * This should not be true om Moodle 4.0 onwards.
Typo: oM Moodle.

2022-03-21 11:41 UTC, dpalou commented on src/core/features/course/services/course-helper.ts
> +     * Section is visible by the user.
Comment says section, but it should be module. Also in the return JSDoc.

2022-03-21 11:41 UTC, dpalou commented on src/core/features/course/services/course-helper.ts
> +     * @return Wether the module is steath.
Typo: steath. Also in the commit name.

2022-03-21 11:41 UTC, dpalou commented on src/core/services/utils/dom.ts
> +        const slots = content.shadowRoot.querySelectorAll('slot') || [];
I think _querySelectorAll_ always returns a list (empty if none found), no need to put the fallback.

2022-03-21 11:41 UTC, dpalou commented on src/core/directives/auto-focus.ts
> +            await focusElement.componentOnReady();
I think it would be nice to check that _componentOnReady_ exists, e.g.:

focusElement.componentOnReady && await focusElement.componentOnReady();

Otherwise if this directive is used in a component that supports getInputElement but not componentOnReady this code will throw an exception.

2022-03-21 11:41 UTC, dpalou commented on src/addons/qtype/ddwtos/classes/ddwtos.ts
> +        groupItems.forEach(async (item) => {
This async isn't needed.

2022-03-21 11:41 UTC, dpalou commented on src/addons/qtype/ddwtos/classes/ddwtos.ts
> +        groupItems.forEach(async (item) => {
This async isn't needed either.

2022-03-21 15:31 UTC, crazyserver commented on src/core/features/course/components/course-format/course-format.ts
> +        if (!CoreCourseHelper.canUserViewModule(module, section) && module.handlerData?.action) {
Yep.. Sorry!

2022-03-21 15:47 UTC, crazyserver commented
Thanks Dani! I totally forgot about it, and I added 2 more commits to the stack :-p

2022-03-22 06:48 UTC, dpalou approved these changes

2022-03-22 06:48 UTC, merged