Mobile 3919
moodlehq/moodleapp pull request #3207
Opened 2022-03-28 14:10 UTC by dpalou

2022-03-28 14:27 UTC, crazyserver requested changes

2022-03-28 14:27 UTC, crazyserver commented on src/addons/mod/assign/pages/edit/edit.ts
> +        options: AddonModAssignSubmissionStatusOptions,
Missing param on JS doc

2022-03-28 14:27 UTC, crazyserver commented on src/core/services/utils/time.ts
> +    formatTimeShort(duration: number): string {
Should this be moved to CoreTime singleton?

2022-03-28 14:27 UTC, crazyserver commented on src/theme/theme.base.scss
> +    &.core-danger-toast {
This can be automatized using a for each (like warning cards) this way all colors will be implemented

2022-03-29 06:14 UTC, dpalou commented on src/core/services/utils/time.ts
> +    formatTimeShort(duration: number): string {
Done, I added a new commit for this.

2022-03-29 06:15 UTC, dpalou commented on src/theme/theme.base.scss
> +    &.core-danger-toast {
Right, I changed it.

2022-03-29 07:48 UTC, crazyserver approved these changes

2022-03-29 07:48 UTC, merged