Mobile 4017
moodlehq/moodleapp pull request #3212
Opened 2022-03-30 09:25 UTC by alfonso-salces

2022-03-30 09:48 UTC, NoelDeMartin requested changes

2022-03-30 09:48 UTC, NoelDeMartin commented on .vscode/settings.json
> +    "files.eol": "\n",
I think this should go in the section above (called "Formatting").

2022-03-30 10:42 UTC, alfonso-salces commented on .vscode/settings.json
> +    "files.eol": "\n",
Done! thank you

2022-03-30 13:58 UTC, NoelDeMartin requested changes

2022-03-30 13:58 UTC, NoelDeMartin commented on src/core/classes/tests/error.test.ts
> -
I believe you've removed this line by mistake?

2022-03-30 13:58 UTC, NoelDeMartin commented on src/testing/utils.ts
> +/**
I think the JSDocs should be added in the same commit as the method, it'd also be better to have an empty line between functions (I've added a new linting rule to enforce that in https://github.com/moodlehq/moodleapp/pull/3214, but it's not merged yet)

2022-03-31 06:01 UTC, alfonso-salces commented on src/core/classes/tests/error.test.ts
> -
Nice catch! thanks you

2022-03-31 06:01 UTC, alfonso-salces commented on src/testing/utils.ts
> +/**
Done!

2022-03-31 06:24 UTC, NoelDeMartin approved these changes
I see you ended up squashing both commits, I think it was fine with two but I'll go ahead with merging anyways so that we get this done :).

2022-03-31 06:25 UTC, merged