Mobile 4061
moodlehq/moodleapp pull request #3278
Opened 2022-05-04 10:25 UTC by crazyserver

2022-05-04 12:55 UTC, NoelDeMartin requested changes
I think the commits are ok, but you should keep the history for the files you've moved. Using git, it is possible to move files with history from one repo to another. I did it in the [previous repository](https://github.com/moodlehq/moodle-local_moodlemobileapp/commits/7d1fd94c19b73db722c2eebdb4f4ef668b4de884), but I don't remember exactly how. Looking at my browser history, I visited these two questions in StackOverflow so they should be useful:

- [How to move a file from one git repository to another while preserving history](https://stackoverflow.com/questions/10524578/how-to-move-a-file-from-one-git-repository-to-another-while-preserving-history)
- [How to move some files from one git repo to another (not a clone), preserving history](https://stackoverflow.com/questions/1365541/how-to-move-some-files-from-one-git-repo-to-another-not-a-clone-preserving-hi)

2022-05-05 10:52 UTC, crazyserver commented
Thanks Noel! I did what you said and added also the tests from the plugin.

2022-05-05 11:28 UTC, crazyserver commented
To make your review easier:
- Forget about commits before 5th May
- Merge commit contains files from the old repo with renames.

2022-05-12 11:54 UTC, NoelDeMartin requested changes

2022-05-12 11:54 UTC, NoelDeMartin commented on src/tests/service/behat-blocking.ts
> +// (C) Copyright 2015 Moodle Pty Ltd.
This folder should be called `test/services` (with plural, not singular)

2022-05-12 11:54 UTC, NoelDeMartin commented on src/tests/tests.module.ts
> +@NgModule({
I'm not sure about the naming and location of this module. Since it's setting up something for testing, but it doesn't contain tests, it should be located under `src/testing` instead (this folder already exists). At the same time, testing so far in the app made reference to unit/integration tests (jest), but now this will make reference to behat. Should it be called "BehatModule" then? I don't know, maybe it's ok to just call it `TestingModule`.

2022-05-12 11:54 UTC, NoelDeMartin commented on src/tests/service/behat-runtime.ts
> +        (window as BehatTestsWindow).behat = {
Instead of doing this, wouldn't it be better to assign a `TestsBehatRuntime` instance to behat directly? In particular, it could be done like we're already exposing other services in the `prepare-automated-tests.ts` file.

The `TestsBehatBlocking.init()` and the rest of the initializing (setting config and env overrides) could be called directly from behat, as it was being done here: https://github.com/moodlehq/moodle-local_moodlemobileapp/blob/integration/tests/behat/behat_app.php#L562

Something to keep in mind as well is that sometimes, this may get called when the application has already been launched. In that case, things like `skipOnBoarding` will not have any effects because the onboarding will already be on screen. Looking at the code, that seems to be the case so I'm not entirely sure why it works (maybe this is executed before the app finishes loading? In that case, that's a race condition and we shouldn't depend on that).

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/behat_app.php
> +    protected $windowSize = '360x720';
Php files use Moodle's styling guide, so this should be `$windowsize` instead. Maybe at some point we should configure [the codechecker](https://github.com/moodlehq/moodle-local_codechecker) as well. There are other similar style errors in the file.

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/behat_app.php
> +                throw new DriverException('Behat already here.');
What does `Behat already here` mean? How come this needed a refactor, it wasn't working before?

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/behat_app.php
> +        $this->evaluate_script("window.behat.getAngularInstance('ion-content', 'CoreSwipeNavigationDirective').$method()");
Why did you add `window.` here? It's not necessary, but I can see that it's used elsewhere in this file. Maybe if we want to standarize, I'd actually not use `window.` anywhere because scripts are already evaluated in the window scope.

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/behat_app_trait.php
> +     * Evaludate a script that returns a Promise.
Typo, this should say "Evaluate".

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/behat_app.php
> +        $this->execute_script('window.close();');
Similar to my comment about removing `window.`, we can also remove `;` at the end of scripts.

Also, I just noticed that sometimes we use `evaluate_script` and others we use `execute_script`. It seems like the only difference is that evaluating returns a value whilst executing doesn't. I think we should also standardize this: either using each one appropriately or using always evaluate (I can't think of any drawbacks).

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/behat_app_trait.php
> +            $this->execute_script('window.behatInit(' . json_encode($initOptions) . ');');
As I mentioned in the service file, I don't think we need to do this. Here, we can check that `behat` is actually available in in the window and that should be enough.

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/behat_app.php
> +        $this->prepare_browser(['skiponboarding' => empty($runtime)]);
I think the `skiponboarding` override could be configured similarly to `$appconfig` which is disabling user tours by default. The only difference is that that makes reference to environment build config, whilst this is runtime config. Maybe we should also rename some of the variables in this file to make that more clear.

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/behat_app.php
> +     * @Given I enter the app
I'm not sure if we should accept both nomenclatures here. "I enter" makes reference to an action, so it should be defined as a `@Then`. And "I entered" makes reference to some state, so it should be defined as a `@Given`. But the implementation should be different as well, an action should really perform the action using the UI whilst some state can be set using shortcuts. The fact that this has now become a shortcut with the same syntax may break some existing tests (if not ours, for some third party). So I think it should be better to keep "I enter" as it was before, and define shortcuts specifically with "I entered".

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/behat_app_trait.php
> +        $this->evaluate_script("return window.behat.handleCustomURL('$customurl')");
Instead of implementing shortcuts using actual app functionality, I think it'd be better to implement them directly on the app's side. For example, in this case instead of relying on custom urls we could do something like this in the app's side (pseudocode):


```
CoreSites.setCurrentSite({ siteUrl, token, ... });
CoreNavigator.navigate(path, { reset: true });
```

I guess we can leave it as is for now if changing that is too much work, but I think it's important to implement shortcuts directly instead of relying on existing functionality.

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/behat_app_trait.php
> +     * @param string $path To navigate.
The name of the argument is `$customurl`, not `$path`

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/behat_app_trait.php
> +        $this->getSession()->executeScript('ngZone.run(() => {});');
It's ok to encapsulate this given how much it's used, but I've come to believe that we should never need to call this manually. So maybe instead of doing this, we could review where it's necessary and fix it instead. If that's too much work for now, I'd at least create a follow up issue or TODO to improve it in the future.

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/behat_app.php
> +     * Opens the Moodle App in the browser and logins (optional).
This should say "logs in" not "logins". Or maybe better, "Opens the Moodle App in the browser and optionally logs in."

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/classes/performance_measure.php
> +require_once(__DIR__ . '/../behat_app.php');
Why is this necessary now when it wasn't before?

2022-05-12 11:54 UTC, NoelDeMartin commented on src/tests/behat/performance.feature
> +    When I reload the page
We want to have the `I reload the page` step before we start measuring, because this is supposed to measure the performance of opening an activity, not the app startup.

2022-05-12 11:54 UTC, NoelDeMartin commented on src/tests/behat/performance.feature
> +    Given I entered the course "Course 1" in the app
This is supposed to test the performance of opening a course, so it shouldn't use any shortcuts between measurements.

2022-05-12 11:54 UTC, NoelDeMartin commented on local-moodleappbehat/tests/behat/behat_app.php
> +        global $DB;
This isn't used.

2022-05-12 11:54 UTC, NoelDeMartin commented on src/core/features/mainmenu/tests/behat/mainmen-311.feature
> +@app @javascript @lms_upto3.11
This file should be called `mainmenu-311.feature` (it's missing the "u" at the end of "menu").

2022-05-12 12:47 UTC, crazyserver commented on local-moodleappbehat/tests/behat/behat_app.php
> +                throw new DriverException('Behat already here.');
It was working but when failing console shows a general error. So now it explains something. However I changed the message.

2022-05-12 12:49 UTC, crazyserver commented on local-moodleappbehat/tests/behat/behat_app.php
> +        $this->evaluate_script("window.behat.getAngularInstance('ion-content', 'CoreSwipeNavigationDirective').$method()");
I'd leave the window then it's easier to understand that something has been added there.

2022-05-12 13:09 UTC, crazyserver commented on src/tests/service/behat-runtime.ts
> +        (window as BehatTestsWindow).behat = {
Main problem of doing this is that we'll be overriding XMLRequest and listening to mutations while developing, but probably we can separate this on two different functions.

2022-05-12 13:20 UTC, crazyserver commented on local-moodleappbehat/tests/behat/behat_app.php
> +        $this->execute_script('window.close();');
I think a discussion is needed here

2022-05-12 13:25 UTC, crazyserver commented on local-moodleappbehat/tests/behat/behat_app.php
> +     * @Given I enter the app
I think right now the declaration of Given, Then, When is something we have to check it works the same. Also I entered the app as doesn't exists previously so nothing changed on the current step.

2022-05-12 13:26 UTC, crazyserver commented on local-moodleappbehat/tests/behat/behat_app_trait.php
> +        $this->evaluate_script("return window.behat.handleCustomURL('$customurl')");
Yeah, I annotated that for a future improvement.

2022-05-12 13:29 UTC, crazyserver commented on local-moodleappbehat/tests/behat/behat_app_trait.php
> +        $this->getSession()->executeScript('ngZone.run(() => {});');
Annotated

2022-05-12 13:33 UTC, crazyserver commented on src/tests/behat/performance.feature
> +    When I reload the page
I know, and this is about the race condition you've mentioned before. It's causing the user tours to be shown when page is reloaded.

2022-05-12 13:36 UTC, crazyserver commented on src/tests/behat/performance.feature
> +    Given I entered the course "Course 1" in the app
True, my bad!

2022-05-12 13:47 UTC, crazyserver commented on src/tests/tests.module.ts
> +@NgModule({
I called BehatTestingModule

2022-05-12 15:36 UTC, merged