MOBILE-4021 configs: Add default zoom level
moodlehq/moodleapp pull request #3282
Opened 2022-05-17 09:51 UTC by alfonso-salces

2022-05-18 06:22 UTC, dpalou requested changes

2022-05-18 06:22 UTC, dpalou commented on moodle.config.json
> +        "normal": 110,
I just realized that, since the zoom level setting is stored in the DB by name, this change can have an impact to users who have changed the setting. E.g. imagine a user that changed the setting to the "middle A", the DB (CoreConfig) will have the value "low". After updating, the value "low" is now 100% so the zoom level will change.

IMO we should implement an upgrade step to change the value stored in the DB (if any), and you can also use it to change the word "normal" to "medium". So if the DB has "low" stored it should be changed to "medium" and viceversa.

I was also thinking that, since yesterday we said that the "Low" zoom should always be 100%, maybe we should rename it to "None" because 100% means there is no zoom instead of being a low zoom.

You can take a look to _CoreUpdateManagerProvider.initialize_ to see how to do the upgrade step.

2022-05-18 06:22 UTC, dpalou commented on src/types/config.d.ts
> +    defaultZoomLevel?: CoreZoomLevel; // Define list of zoom percentages to select in settings.
I think this comment could be improved, it makes me think the setting is a "list of zoom percentages" but it's actually a single zoom level.

2022-05-18 06:23 UTC, dpalou commented
The commit name is wrong (and the PR title too), the issue number is MOBILE-4074.

2022-05-18 09:43 UTC, alfonso-salces commented on src/types/config.d.ts
> +    defaultZoomLevel?: CoreZoomLevel; // Define list of zoom percentages to select in settings.
Nice catch, I forgot to edit this comment before. Now it's fine!

2022-05-19 09:49 UTC, dpalou approved these changes

2022-05-19 09:49 UTC, merged