Mobile 4021 tests
moodlehq/moodleapp pull request #3299
Opened 2022-05-30 11:26 UTC by alfonso-salces

2022-05-30 11:34 UTC, alfonso-salces commented
Need integrate https://tracker.moodle.org/browse/MDL-74674 to merge that Pull Request.

2022-09-20 07:31 UTC, NoelDeMartin commented
@alfonso-salces please rebase to resolve the merge conflicts.

2022-11-10 17:12 UTC, NoelDeMartin requested changes

2022-11-10 17:12 UTC, NoelDeMartin commented on src/addons/notifications/tests/behat/notifications.feature
> +Feature: Main Menu opens the right page
```suggestion
@app @javascript
Feature: Notifications
```

2022-11-14 09:04 UTC, NoelDeMartin approved these changes

2022-11-14 09:04 UTC, merged