MOBILE-4081: Improve notifications source and fix behat enter step
moodlehq/moodleapp pull request #3307
Opened 2022-06-02 15:10 UTC by NoelDeMartin

2022-06-10 06:12 UTC, dpalou requested changes

2022-06-13 11:08 UTC, NoelDeMartin commented on src/addons/notifications/services/notifications.ts
> +     * @deprecated since 4.1. Use getNotificationsWithStatus instead.
Thanks for pointing this out, but I think I'll leave as deprecated just in case.

2022-06-13 11:11 UTC, NoelDeMartin commented on src/addons/notifications/classes/notifications-source.ts
> +                ],
Good catch, I did this looking at the [feedback-attempts-source](https://github.com/moodlehq/moodleapp/blob/integration/src/addons/mod/feedback/classes/feedback-attempts-source.ts#L137) which has a similar issue (instead of read/unread, the endpoint returns anonymous/non anonymous results). However, in that case the component using the source already takes this into account and doesn't show the bottom part of the list until the top is completely loaded.

I have refactored the code and it should be working now, please take another look.

2022-06-14 09:57 UTC, dpalou requested changes

2022-06-14 09:57 UTC, dpalou commented on src/addons/notifications/classes/legacy-notifications-source.ts
> +            const offset = page * pageLength - totalUnread();
I think this _offset_ is wrong, it can be negative. Imagine I have 5 unread notifications and 5 read. When loading page 0, first we load the unread ones, we add 5 items and the _totals_ for unread is 5. So the offset is now: 0 * 20 - 5 = -5. I'm not sure if sending a negative value to the WS can cause problems or it will work as 0, but this offset is also used in _loadNotifications_ to calculate the _totals_ and that means we'll have a wrong value. Because the _totals_ for read will be:

offset + notifications.length = -5 + 5 = 0

but it should actually be 5. I think that forcing it to be 0 instead of negative will be enough to make it work fine.

2022-06-14 09:57 UTC, dpalou commented on src/addons/notifications/classes/legacy-notifications-source.ts
> +            pageUnreadCount = items.length;
I think this value will always be 0, right? Because it's calculated before modifying the _items_ array. Maybe you can get rid of this variable and just use _items.length_ when fetching the read notifications?

2022-06-15 08:46 UTC, NoelDeMartin commented on src/addons/notifications/classes/legacy-notifications-source.ts
> +            const offset = page * pageLength - totalUnread();
Yeah good catch, I didn't think this properly. This only happens when reading a page that has notifications from both read and unread sources, so it could be fixed like this as well (and maybe it's more semantically correct):

`const offset = page * pageLength - totalUnread() + pageUnreadCount;`

But I agree it's safer to just do `Math.max(0, ...)`, and it will produce the same results in the end so that's what I've done.

2022-06-15 08:47 UTC, NoelDeMartin commented on src/addons/notifications/classes/legacy-notifications-source.ts
> +            pageUnreadCount = items.length;
Yeah you're right, this was also wrong. Instead of removing the variable, I've fixed it to read from the `pageResults` variable. It's true that your proposal of using `items.length` later on would work, but I think this is more readable.

2022-06-15 09:18 UTC, dpalou approved these changes

2022-06-15 09:18 UTC, merged