Mobile 4081
moodlehq/moodleapp pull request #3325
Opened 2022-06-17 07:04 UTC by alfonso-salces

2022-06-21 11:29 UTC, NoelDeMartin requested changes

2022-06-21 11:29 UTC, NoelDeMartin commented on src/core/features/login/services/login-helper.ts
> +        return import('@features/login/pages/reconnect/reconnect.module').then(m => m.CoreLoginReconnectPageModule);
I think it'd be better to declare this as returning `Promise<unknown>` or something else, there a couple of reasons why I think that's better.

First, we should avoid importing module classes in this way because we already have many issues with circular dependencies and lazy modules not working as well as they should (I talked about it [in this issue](https://tracker.moodle.org/browse/MOBILE-1804?focusedCommentId=887454&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-887454)). So if we were to import the module, I think it should be a type import instead.

But secondly, and maybe more important, with this signature it would be difficult to override this method in subclasses (because they should return a subclass of the returned module). I think just returning `Promise<unknown>` should work because modules don't really have a parent class, and looking at the Angular types they use `any` so it should be equivalent.

2022-06-22 07:14 UTC, alfonso-salces commented on src/core/features/login/services/login-helper.ts
> +        return import('@features/login/pages/reconnect/reconnect.module').then(m => m.CoreLoginReconnectPageModule);
Hi, Im agreed with you, so now the return type is ` Promise<unknown>` 
Thanks for your review!

2022-06-22 07:16 UTC, NoelDeMartin approved these changes

2022-06-22 07:17 UTC, merged