MOBILE-4097 core: Don't convert to address URL if it's already a URL
moodlehq/moodleapp pull request #3329
Opened 2022-06-21 13:55 UTC by dpalou

2022-06-21 14:33 UTC, crazyserver requested changes

2022-06-22 05:44 UTC, dpalou commented on src/core/services/utils/text.ts
> +        if (address.match(/^https?:\/\//)) {
Hi Pau, I changed the code to use _CoreUrl.parse_.

I did some tests with URL and it seems to be supported in iOS 12 (MDN says the constructor was added in iOS 14.5), but it doesn't have the same behaviour as _CoreUrl.parse_. Our _parse_ function for example accepts "moodle.org" as a valid URL, but the URL class requires a protocol so it will throw an error in this case.

So I'd leave the code as it is for now and we can discuss if we want to change it in the future.

2022-06-22 07:39 UTC, crazyserver approved these changes

2022-06-22 07:39 UTC, crazyserver commented on src/core/services/utils/text.ts
> +        if (address.match(/^https?:\/\//)) {
Nice! Thanks!!!

2022-06-22 07:39 UTC, merged