MOBILE-4059: Contact site support
moodlehq/moodleapp pull request #3400
Opened 2022-10-10 09:00 UTC by NoelDeMartin

2022-10-18 13:32 UTC, dpalou requested changes

2022-10-18 16:14 UTC, NoelDeMartin commented on src/core/features/login/tests/credentials.test.ts
> +        const form = fixture.nativeElement.querySelector('form') as HTMLFormElement;
Does this work for you? I like it, but in my environment that doesn't work because `nativeElement` is typed as any. Looking at the [Angular source](https://github.com/angular/angular/blob/main/packages/core/testing/src/component_fixture.ts#L31), it seems that's the case so I think this would only work if we augment the types.

2022-10-18 16:31 UTC, NoelDeMartin commented on src/core/classes/errors/siteerror.ts
> +function getErrorMessage(options: CoreSiteErrorOptions) {
Thanks, I added the return type.

About having it as a stand-alone function, the problem is that javascript doesn't allow using `this` before calling `super` (it throws an error at runtime), so it needs to be defined like this. I'm not much of a fan either to be honest, but the only alternative is to do all the conditionals inline and I think that's worse. I'm open to suggestions tough.

2022-10-18 16:31 UTC, NoelDeMartin commented on src/theme/theme.light.scss
>      --text-size:        14px;
Ok, I've changed it for now.

One comment about the styles in this PR, as you'll have noticed I started adding some things for the Design System, but I'm not sure if this is the best way to go about it. I think we still need to discuss this separatedly, but this was a first approach to avoid blocking this issue until the Design System is "ready".

2022-10-18 16:34 UTC, NoelDeMartin commented on src/core/services/sites.ts
> +                siteConfig,
I don't know how you added this comment, because `createCannotConnectError` does not exist in this PR :/ can you double-check? It existed at some point, but it's been renamed so I don't know how you managed to make this comment xD.

2022-10-19 06:12 UTC, dpalou commented on src/core/features/login/tests/credentials.test.ts
> +        const form = fixture.nativeElement.querySelector('form') as HTMLFormElement;
Oh, I didn't notice that `nativeElement` was typed as `any`, that sucks :(

I think it's better to augment the type and declare `nativeElement` as `HTMLElement` or `Element`, we're assuming that's the case anyway because we're using `querySelector`.

2022-10-19 06:13 UTC, dpalou commented on src/core/services/sites.ts
> +                siteConfig,
Right, you renamed it to `createCannotConnectLoginError`. It's where the code checks this:

`data.error == 'Web services must be enabled in Advanced features.'`

2022-10-19 08:52 UTC, NoelDeMartin commented on src/core/features/login/tests/credentials.test.ts
> +        const form = fixture.nativeElement.querySelector('form') as HTMLFormElement;
I ended up refactoring a couple of things about the types here, so please take another look.

2022-10-19 15:31 UTC, NoelDeMartin commented on src/core/features/user/tests/behat/support.feature
> +@core @core_user @app @javascript
Thanks for this comment, looking at this I realized we had something in the Shaping document that wasn't true.

In a nutshell, contacting support was not supposed to work before 4.0 but turns out that [it can work for logged in users since 3.9](https://tracker.moodle.org/browse/MDL-69810). The problem is that it only works with an explicit url, there isn't a fallback form as in 4.0. So to simplify, we've decided to just have it starting in 4.0.

Because of this, and in preparation for [MDL-74643](https://tracker.moodle.org/browse/MDL-74643), I ended up refactoring how the support configuration is calculated. I added this in a separate commit (the latest one), so you should be able to review that one separatedly. The rest of the commits have also changed in response to your suggestions, so it should be fine if you don't look at them in too much detail again; unless there is something you want to take another look.

2022-10-19 15:34 UTC, NoelDeMartin commented on src/core/features/user/services/support.ts
> +    }
In the new version that you'll see in the latest commit, I've followed your suggestion of throwing an error. It should never happen, but it's a good idea to have it just in case.

The reason why the fallback url is that the way to check if a site has a support form is actually to look for the existence of the `supportpage` config, but the value can be an empty string ('that's why I'm using `||` and not `??` in the return).

2022-10-24 10:23 UTC, dpalou requested changes

2022-10-25 05:51 UTC, dpalou approved these changes

2022-11-08 11:14 UTC, dpalou requested changes

2022-11-08 11:14 UTC, dpalou commented on src/core/classes/site.ts
> +            throw new CoreError(Translate.instant('core.cannotconnect'));
The parameter $a is still used in some languages: zh_tw, fi, el_wp, hi, hu, km, ko, lv, lt, ro, ru, sr_cr, sr_lt, vi.

IMO if we don't fix those languages ourselves we should keep this parameter. You removed it in several places.

2022-11-08 15:17 UTC, NoelDeMartin commented on src/core/classes/site.ts
> +            throw new CoreError(Translate.instant('core.cannotconnect'));
Ok, I've added it back and I submitted the modifications to the translations, but I'll open a separate PR to remove it then.

2022-11-09 06:45 UTC, dpalou approved these changes

2022-11-09 06:45 UTC, merged