Mobile 3936
moodlehq/moodleapp pull request #3425
Opened 2022-10-28 11:24 UTC by crazyserver

2022-11-04 09:23 UTC, dpalou requested changes
Thanks Pau, I left a lot of comments here but they're all minor things, the solution looks good to me.

About the tests, I missed some things to be tested:

- We aren't testing that the "Reminder set" toast displays the right date. You could create an activity/course with a fixed time (e.g. 1/1/2050) and that way you can know for sure the date that will be displayed in the Toast.
- We aren't testing that local notifications can be canceled (they aren't triggered). 

These things only need to be tested once, there's no need to replicate them for course and activity.

2022-11-08 15:01 UTC, crazyserver commented on src/core/services/sites.ts
> +            this.sites[siteId] = site;
You're right!

2022-11-08 15:14 UTC, crazyserver commented on src/addons/calendar/services/calendar.ts
> +    async updateAllSitesEventReminders(): Promise<void> {
Done thanks!

2022-11-08 15:26 UTC, crazyserver commented on src/core/features/reminders/services/database/reminders.ts
> +    before: number; // Seconds before the event to remind.
Ok thanks!

2022-11-08 16:07 UTC, crazyserver commented on src/core/features/reminders/services/reminders.ts
> +    }
So, when the app starts, the events have been always scheculed before?

2022-11-09 07:03 UTC, dpalou commented on src/core/features/reminders/services/reminders.ts
> +    }
Well, if a reminder already exists in DB it means that the notification was scheduled before, right? And I think there's no need to reschedule them again, Android should keep the scheduled notifications.

You can do a test if you want: remove this code, create a couple of reminders to be triggered soon, kill the app and restart it and check if the notifications are triggered.

2022-11-09 12:19 UTC, crazyserver commented on src/addons/calendar/services/calendar.ts
> -    static readonly DEFAULT_NOTIFICATION_TIME_SETTING = 'mmaCalendarDefaultNotifTime';
Got it! Thanks!

2022-11-09 15:32 UTC, crazyserver commented on src/core/features/reminders/components/set-reminder-menu/set-reminder-menu.ts
> +        }
Thanks I've totally removed the conditions so it saves the reminder

2022-11-09 15:43 UTC, crazyserver commented on src/core/features/emulator/services/local-notifications.ts
> +            return;
It is a simplification,t this function checks the next notification and triggers it when notification time has been reached.

2022-11-09 20:37 UTC, crazyserver commented on src/core/features/reminders/services/reminders.ts
> +    }
Ok, I've added a new commit that we should discuss

2022-11-10 09:44 UTC, crazyserver commented on src/core/features/reminders/services/reminders.ts
> +    }
Discussed and merged on the LocalNotifications mock commit

2022-11-10 12:26 UTC, dpalou requested changes

2022-11-10 12:26 UTC, dpalou commented on src/core/features/reminders/tests/behat/activity_reminders.feature
> +    Given the following "activities" exist:
```suggestion
    And the following "activities" exist:
```

2022-11-10 12:26 UTC, dpalou commented on src/core/features/reminders/tests/behat/activity_reminders.feature
> +    And I press "Delete reminder" in the app
```suggestion
    When I press "Delete reminder" in the app
```

2022-11-10 12:26 UTC, dpalou commented on src/core/features/reminders/tests/behat/activity_reminders.feature
> +
You have an extra blank line here.

2022-11-10 14:31 UTC, dpalou approved these changes

2022-11-10 14:33 UTC, dpalou commented
Thanks Pau, it looks good now but you have some linter errors:

https://github.com/moodlehq/moodleapp/actions/runs/3436891988/jobs/5730955597

2022-11-11 07:12 UTC, merged