MOBILE-4177 forum: Empty box with auto height
moodlehq/moodleapp pull request #3436
Opened 2022-11-10 11:43 UTC by crazyserver

2022-11-10 14:29 UTC, dpalou requested changes
Thanks Pau,

this will fix the problem for forum, but I think this problem affects any empty box inside a split view left pane. I think the height wasn't calculated right in glossary either for example. Maybe we should put this fix inside the split-view CSS, probably only for left pane?

2022-11-10 15:43 UTC, crazyserver commented
Actually the problem is with any page: The height of the box is 100% so it will occupy the same height as her parent.
The thing is that when other elements are in page which is not very common because when it's empty, usually nothing else is shown, the element goes down. If I fix that for all the left panels, it will be at the top on those pages.

One solution is to check the top position of the element and remove the height 100% when this position is more than a threshold. But this is a JS solution... That do you think?

2022-11-11 08:22 UTC, crazyserver commented
After some chat, I've changed the approach to match splitview problem.

2022-11-11 08:34 UTC, dpalou approved these changes

2022-11-11 09:46 UTC, merged