MOBILE-4202 split-view: Scroll to current element when swipe
moodlehq/moodleapp pull request #3487
Opened 2022-11-29 14:25 UTC by alfonso-salces

Scroll to current element when swipe in split-view page.

2022-11-29 16:39 UTC, NoelDeMartin requested changes

2022-11-29 16:39 UTC, NoelDeMartin commented on src/core/classes/items-management/swipe-navigation-items-manager.ts
> +        this.scrollToCurrentElement(delta);
I think you're calling this here instead of inside of `navigateToItem` because you are using the `delta` to check whether to scroll to the next or the previous, but I don't understand why. What's the problem to scroll to the current item?

If the problem is that the "current item" is not actually the current item, but the one that will be selected next, I don't think this is the proper way to do it. I can see two ways.

The first one is to actually way for the selected item to be selected (I'm not sure if that can be achieved with nextTick or something else). The other option would be to actually find the item that will be selected next.

In both case, I think it's important to get the actually selected item rather than using the current algorithm. First, because delta may be more bigger than 1 or smaller than -1. And second, because the current implementation is looking at any element matching `[aria-current="page"]`, and for all we know that element may not even be one of the items in the split view. So I think we may need to get more creative with this solution.

Also, the manager in charge of the actual items seems to be the list manager, not the swipe items manager. So I think we need to take another look to solving this properly. Maybe we can do a call tomorrow and pair on this if you want.

2023-01-16 12:17 UTC, NoelDeMartin requested changes
Overall I think it's good now, but some E2E tests related with the split-view are failing so you should rebase to make sure that they are not related with these changes.

2023-01-16 12:17 UTC, NoelDeMartin commented on src/core/classes/items-management/list-items-manager.ts
> +    }
```suggestion
        this.select(selectDefault ? this.getDefaultItem() : this.selectedItem);
    }
```

I think it's better to leave this as this for a cleaner diff (it's probably changed because we had a different approach before).

2023-01-17 07:42 UTC, alfonso-salces commented on src/core/classes/items-management/routed-items-manager.ts
> -
I do that because if I scroll to the end of the list and load more items is scrolling to the selected item because we are calling to `this.updateSelectedItem()`.

2023-01-17 07:53 UTC, NoelDeMartin commented on src/core/classes/items-management/routed-items-manager.ts
> -
Hm I see, can you try instead of removing it only call `this.updateSelectedItem()` if the current item is null or it doesn't exist on the list of loaded items?

The idea of this override was to automatically select an item that was selected before the items load, which could happen for example opening a split-view with the url on a selected item. I think it's important to keep that behaviour, or it affects the UX of split-views because they could potentially open without a selected item which is weird.

2023-04-24 08:41 UTC, NoelDeMartin requested changes

2023-04-24 08:41 UTC, NoelDeMartin commented on src/core/classes/items-management/items-manager.ts
> +        if (item && this.selectedItem && this.getItemId(item) === this.getItemId(this.selectedItem)) {
```suggestion
        if (item === this.selectedItem) {
```

I think this is what's breaking the tests, so with this we should be ready to merge :). Although you may need to rebase because there's been a while since we looked into this. But I think it should be fine, because we haven't changed any of the related files that I'm aware.

2023-04-25 08:41 UTC, NoelDeMartin requested changes

2023-04-25 08:41 UTC, NoelDeMartin commented on src/core/classes/items-management/routed-items-manager.ts
> +        if (selectedItem !== null && items.some(item => this.getItemId(item) === this.getItemId(selectedItem))) {
```suggestion
        if (selectedItem !== null && items.some(item => item === selectedItem)) {
```

We also need to compare by reference rather than id here. I've reviewed the code to make sure we're not forgetting it anywhere else, and I think it should be fine after fixing this line.

2023-04-25 13:35 UTC, NoelDeMartin approved these changes

2023-04-25 13:35 UTC, merged