Mobile 4077 - Support user custom reports
moodlehq/moodleapp pull request #3533
Opened 2023-01-25 12:37 UTC by alfonso-salces

2023-01-30 17:09 UTC, NoelDeMartin requested changes

2023-01-30 17:09 UTC, NoelDeMartin commented on src/core/features/reportbuilder/components/report-detail/report-detail.html
> +            <ng-container *ngIf="layout === 'card' || (isMobile && layout === 'adaptative')">
Instead of doing this, maybe we could compute the "effective layout" in the controller and have this variable be only `card` or `table`? I get that this is a property, but in another comment I suggest that this shouldn't be a component at all, and even if it is we should be able to create a computed variable with another name (maybe effectiveLayout?)

2023-01-30 17:09 UTC, NoelDeMartin commented on src/core/features/reportbuilder/components/report-detail/report-detail.ts
> +    async getReport(): Promise<void> {
I think this should be called `loadReport` instead.

2023-01-30 17:09 UTC, NoelDeMartin commented on src/core/features/reportbuilder/pages/list/list.html
> +        <ion-list *ngIf="reports.items">
What happens if the user has no reports? Would this show an empty screen, or is this page unreachable? Maybe we need to handle the empty state here with some text.

2023-01-30 17:09 UTC, NoelDeMartin commented on src/core/features/reportbuilder/pages/list/list.module.ts
> +export class CoreReportBuilderListModule {}
We've decided to avoid page modules if page components are not reused in multiple modules, so this should be removed and the page can be declared in the lazy module directly.

2023-01-30 17:09 UTC, NoelDeMartin commented on src/core/features/reportbuilder/pages/report/report.module.ts
> +export class CoreReportBuilderReportModule {}
Same as the other page module, we should remove it.

2023-01-30 17:09 UTC, NoelDeMartin commented on src/core/features/reportbuilder/pages/list/list.ts
> +    styles: [''],
```suggestion
```

2023-01-30 17:09 UTC, NoelDeMartin commented on src/core/features/reportbuilder/tests/behat/reportbuilder.feature
> +@app @javascript @core_reportbuilder @alfonsodebug
```suggestion
@app @javascript @core_reportbuilder
```

2023-01-30 17:09 UTC, NoelDeMartin commented on src/core/features/reportbuilder/pages/report/report.html
> +    <core-report-builder-report-detail [isBlock]="false" [reportId]="reportId" (onReportLoaded)="loadTitle($event)">
It seems like this component is only used here and it fills the entire page, so what's the reason to extract a separate component?

2023-01-31 08:22 UTC, alfonso-salces commented on scripts/langindex.json
> +  "core.reportbuilder.menu": "tool_reportbuilder",
Nice catch, I renamed it by mistake.
The string that i was using before is `core.reportbuilder.customreports`, but I agree that maybe we should show to the user "Reports" so I will use `core.reportbuilder.reportstab`.

2023-01-31 09:20 UTC, alfonso-salces commented on src/core/features/reportbuilder/pages/report/report.html
> +    <core-report-builder-report-detail [isBlock]="false" [reportId]="reportId" (onReportLoaded)="loadTitle($event)">
Because it can be loaded as block.

2023-02-01 12:18 UTC, NoelDeMartin approved these changes

2023-02-01 12:18 UTC, merged