[4.2] Linting and small improvements release
moodlehq/moodleapp pull request #3536
Opened 2023-01-26 12:19 UTC by crazyserver

2023-03-13 08:58 UTC, dpalou requested changes

2023-03-13 08:58 UTC, dpalou commented on src/addons/qtype/ddimageortext/classes/ddimageortext.ts
> +            const pattern = new RegExp(`^${prefix}([0-9])+$`);
I think this change is wrong. Before the patch, `patt2` captured all numbers in `match[0]` (this was the value returned) and only the last number in `match[1]` (because "+" is outside of the parenthesis). 

With your patch you will only return the last number because the "+" is outside of the parenthesis too, so `match[1]` will only have the last number.

2023-03-13 08:58 UTC, dpalou commented on src/addons/qtype/essay/component/essay.ts
> +        if (this.offlineEnabled && this.question?.localAnswers?.attachments_offline) {
The "?" in this.question isn't needed, right?

2023-03-13 13:50 UTC, crazyserver commented on src/core/classes/sqlitedb.ts
> +            if (isLoggingEnabled) {
Cannot remember, I reverted that change

2023-03-13 13:58 UTC, crazyserver commented on src/addons/qtype/ddimageortext/classes/ddimageortext.ts
> +            const pattern = new RegExp(`^${prefix}([0-9])+$`);
True!

2023-03-13 14:00 UTC, crazyserver commented on src/addons/mod/scorm/components/index/index.ts
> +    protected async sync(retries = 0): Promise<AddonModScormSyncResult | undefined> {
I've added a new commit to solve that.

2023-03-14 11:26 UTC, dpalou requested changes

2023-03-14 11:26 UTC, dpalou commented on src/addons/mod/forum/services/handlers/prefetch.ts
> +export type AddonModForumSyncResult = CoreSyncResult;
This type is defined in forum-sync too, I guess we should define it in a single place.

2023-03-14 11:26 UTC, dpalou commented on src/addons/mod/forum/services/forum-sync.ts
> +        const syncDiscussions = async (): Promise<CoreSyncResult> => {
Shouldn't you use AddonModForumSyncResult instead?

2023-03-14 11:26 UTC, dpalou commented on src/addons/mod/scorm/services/scorm-sync.ts
> +export type AddonModScormAutoSyncEventData = CoreSyncResult &{
There is a blank space missing after the &.

2023-03-14 11:26 UTC, dpalou commented on src/core/features/course/classes/main-activity-component.ts
> +            updated: true,
Shouldn't this be false by default? We aren't sending anything.

2023-03-14 11:26 UTC, dpalou commented on src/addons/mod/quiz/services/quiz-offline.ts
> +import { CoreError } from '@classes/errors/error';
This import isn't used.

2023-03-14 14:42 UTC, crazyserver commented on src/core/features/course/classes/main-activity-component.ts
> +            updated: true,
Alright, double checked and updated means updated but hasSyncSucceed really means the same as updated...

2023-03-14 14:50 UTC, crazyserver commented on src/core/features/course/classes/main-activity-component.ts
> +            updated: true,
I've changed JS doc and also scorm return of hasSyncSucceed function

2023-03-14 15:30 UTC, merged