Mobile 4166
moodlehq/moodleapp pull request #3538
Opened 2023-01-31 14:20 UTC by dpalou

2023-02-08 12:29 UTC, NoelDeMartin requested changes

2023-02-08 12:29 UTC, NoelDeMartin commented on src/theme/theme.base.scss
> + * Styles extracted from the end of https://github.com/moodle/moodle/blob/master/media/player/videojs/styles.css
Instead of adding this here, I think it'd be better to create a new `src/theme/components/videojs.scss` file.

I'm also not a fan of including this type of comments saying where the code was taken from. If the code is 100% copy-pasted and will never change, I guess it's ok. But as soon as it changes in some way or functionality is added or modified, the comment becomes misleading. Instead, I think it's better to include the code in a separate commit and add this information in the commit message (even co-authoring authors who worked on the original repository as well, if we're doing this to keep attribution).

2023-02-08 12:29 UTC, NoelDeMartin commented on src/addons/filter/mediaplugin/services/handlers/mediaplugin.ts
> +                mediaElement.removeAttribute('data-setup-lazy');
I'm not sure why this is necessary, when were this classes added in the first place if not by the call above?

2023-02-08 12:29 UTC, NoelDeMartin commented on src/addons/filter/mediaplugin/services/handlers/mediaplugin.ts
> +     * Use video JS in a certain video.
```suggestion
     * Use video JS in a certain video or audio.
```

2023-02-08 12:29 UTC, NoelDeMartin commented on src/core/directives/external-content.ts
>          }
```suggestion
        const urls = CoreUtils.uniqueArray(Array.from(inlineStyles.match(/https?:\/\/[^"') ;]*/g) ?? []));
        if (!urls.length) {
```

2023-02-08 12:29 UTC, NoelDeMartin commented on src/core/services/app.ts
> +    }
I think it's better to move these two methods to `CorePlaform`, to decouple code and avoid circular dependencies (this `AppService` is imported in too many places). It'd be ideal if we had all these type of methods in there, but I haven't done it yet.

2023-02-08 12:29 UTC, NoelDeMartin commented on src/core/singletons/dom.ts
> +    static getMediaSources(mediaElement: HTMLVideoElement | HTMLAudioElement): CoreMediaSource[] {
What do you think of moving all these new methods to a `CoreMedia` service? In fact, you're already naming the type `CoreMediaSource` instead of `CoreDOMMediaSoure`, so it goes in line with that.

2023-02-08 12:29 UTC, NoelDeMartin commented on src/addons/filter/mediaplugin/classes/videojs-ogvjs.ts
> + * Code adapted from https://github.com/HuongNV13/videojs-ogvjs.
Same as I mentioned for the styles, I would remove this comment from the code and add it to the initial commit with proper attribution, co-authoring, etc.

In this case, we actually see what I was saying of the modifications because we're adding the fullscreen functionality.

2023-02-08 12:29 UTC, NoelDeMartin commented on src/core/singletons/object.ts
> +     * Code extracted from https://github.com/HuongNV13/videojs-ogvjs/blob/main/src/plugin.js
Same comment about this type of documentation.

Also, I'm not sure we'll ever use this outside of VideoJS, so maybe I'd just declare this function there and not bother exporting it.

2023-02-08 12:29 UTC, NoelDeMartin commented on src/addons/filter/mediaplugin/classes/videojs-ogvjs.ts
> +export class VideoJSOgvJS extends Tech {
I haven't reviewed much of the initial code because I think it was almost the same as the original repository, but let me know if you prefer that I take a deeper look.

2023-02-08 12:29 UTC, NoelDeMartin commented on src/addons/filter/mediaplugin/mediaplugin.module.ts
> +                Tech.registerTech('OgvJS', VideoJSOgvJS);
Maybe this could be encapsulated in the `videojs-ovgjs` file? If not called directly, we can encapsulate it within an `initializeVideoJSOvgJS` method or something.

2023-02-08 12:29 UTC, NoelDeMartin commented on src/addons/filter/mediaplugin/classes/videojs-ogvjs.ts
> +    constructor(options: VideoJSOptions & { playerId: string }, ready: () => void) {
```suggestion
    constructor(options: VideoJSTechOptions, ready: () => void) {
```

I think it's better to extract this into a different type, even if it's only used once and not exported from this file. When looking at the code, I was confused where this `playerId` comes from and it took me a while to realize that this is actually [called internally by VideoJS](https://github.com/videojs/video.js/blob/b306ce614e70e6d3305348d1b69e1434031d73ef/src/js/player.js#L1194).

2023-02-08 12:29 UTC, NoelDeMartin commented on src/addons/filter/mediaplugin/classes/videojs-ogvjs.ts
> +        return !!this.playerId;
`playerId` is typed as a required string, so won't this always be true? (unless it's an empty string, but I'm not sure if that's possible).

2023-02-08 12:29 UTC, NoelDeMartin commented on src/addons/filter/mediaplugin/classes/videojs-ogvjs.ts
> +        this.parentElement.replaceChild(this.placeholderElement, container);
Maybe you've already tried this, but I'm bringing it up just in case. Wouldn't it be possible to use `position: fixed` to work around this without the need to move the element around?

2023-02-09 11:25 UTC, dpalou commented on src/addons/filter/mediaplugin/services/handlers/mediaplugin.ts
> +                mediaElement.removeAttribute('data-setup-lazy');
They're added by LMS. LMS also uses VideoJS, and we receive the HTML already "filtered" so it includes this classes and attributes.

2023-02-09 11:27 UTC, dpalou commented on src/theme/theme.base.scss
> + * Styles extracted from the end of https://github.com/moodle/moodle/blob/master/media/player/videojs/styles.css
Moved to a new file.

I divided the CSS in 2 blocks: the styles specific of the app, and the ones copied from Moodle without changing anything. I also changed the link to point to the specific version of the CSS file.

2023-02-09 11:29 UTC, dpalou commented on src/core/services/app.ts
> +    }
I added a new commit to move these functions (and some existing ones) to CorePlatform.

2023-02-09 11:29 UTC, dpalou commented on src/core/singletons/dom.ts
> +    static getMediaSources(mediaElement: HTMLVideoElement | HTMLAudioElement): CoreMediaSource[] {
I like it, done!

2023-02-09 11:31 UTC, dpalou commented on src/addons/filter/mediaplugin/classes/videojs-ogvjs.ts
> + * Code adapted from https://github.com/HuongNV13/videojs-ogvjs.
As we talked in chat, I changed the link to point to the exact version of the file and I added the list of changes done.

2023-02-09 11:31 UTC, dpalou commented on src/core/singletons/object.ts
> +     * Code extracted from https://github.com/HuongNV13/videojs-ogvjs/blob/main/src/plugin.js
I moved the function to the videojs-ogvjs file and removed the comment about the original code (that file already has a comment like that).

2023-02-09 11:32 UTC, dpalou commented on src/addons/filter/mediaplugin/classes/videojs-ogvjs.ts
> +export class VideoJSOgvJS extends Tech {
IMO there's no need to, as you say the code is almost the same. Now there's a list of changes in the class JSDoc, so you might want to review those parts.

2023-02-09 11:39 UTC, dpalou commented on src/addons/filter/mediaplugin/classes/videojs-ogvjs.ts
> +        return !!this.playerId;
Actually, since this playerId is added to the options by VideoJS internally (and I'm not sure if this is documented) I preferred to change the declaration to optional.

2023-02-09 11:40 UTC, dpalou commented on src/addons/filter/mediaplugin/classes/videojs-ogvjs.ts
> +        this.parentElement.replaceChild(this.placeholderElement, container);
Yes, this is the first thing we tried but we didn't manage to make it work so we ended up using this solution.

2023-02-09 14:44 UTC, NoelDeMartin approved these changes

2023-02-09 14:44 UTC, merged