Mobile 4245
moodlehq/moodleapp pull request #3560
Opened 2023-02-23 10:50 UTC by alfonso-salces

2023-03-08 11:43 UTC, dpalou requested changes

2023-03-08 11:43 UTC, dpalou commented on src/core/features/login/services/login-helper.ts
> +    isStagingSite(site: CoreLoginSiteInfo | CoreLoginSiteInfoStaging): boolean {
This function doesn't have JSDoc.

2023-03-08 11:43 UTC, dpalou commented on src/core/features/login/services/login-helper.ts
> +    }
Since this function is deprecated I'd just return either all sites or only the not-staging ones without checking the setting, that way the function can stay synchronous and we don't break existing code.

The same happens in `isFixedUrlSet`.

2023-03-08 11:43 UTC, dpalou commented on src/core/services/sites.ts
> +
Instead of creating a new type, maybe we can just add these properties in CoreLoginSiteInfo as optional? That way we don't need to do `'staging' in site`, we can just check `!!site.staging`.

Also, I guess the className can be useful for all sites, not just staging ones.

2023-03-08 11:43 UTC, dpalou commented on src/core/features/login/pages/reconnect/reconnect.ts
> +        );
We usually put awaits in a separate line to make it more obvious that it has async code, but in this case you will be calling an asynchronous code that isn't needed if `CoreLoginHelper.displayQRInSiteScreen()` is true. So I'd either do:

`this.showScanQR = CoreLoginHelper.displayQRInSiteScreen() || (await ...);`

Or:

```
this.showScanQR = CoreLoginHelper.displayQRInSiteScreen();
if (!this.showScanQR) {
    this.showScanQR = await ...
}
```

2023-03-08 11:43 UTC, dpalou commented on src/core/features/login/services/login-helper.ts
> +    async displayQRInCredentialsScreen(qrCodeType = CoreSiteQRCodeType.QR_CODE_LOGIN): Promise<boolean> {
A couple of existing functions have changed to be async, and this can break existing code. I'd add a note in upgrade.txt explaining this, something like:

* CoreLoginHelperProvider.getAddSiteRouteInfo and CoreLoginHelperProvider.displayQRInCredentialsScreen are now async.

2023-03-08 11:43 UTC, dpalou commented on src/core/features/login/pages/reconnect/reconnect.ts
> +            this.showUserAvatar = !!this.userAvatar && !CoreConstants.CONFIG.sites.length;
Now that we can have staging and production sites in the same list, shouldn't you use `getAvailableSites` in several places where you are using `CoreConstants.CONFIG.sites` (like this one)? Maybe it no longer makes sense to deprecate `hasSeveralFixedSites`, this function could call getAvailableSites internally (and then check its length).

2023-03-08 11:45 UTC, dpalou requested changes

2023-03-08 11:45 UTC, dpalou commented on src/core/features/settings/services/settings-helper.ts
> +        window.location.reload();
Oh, one more thing I forgot to add. I guess you do this to reload the list of sites in the add site page. Maybe you should only do this if the user is not logged in? Because if the user has already authenticated then the add site page won't be loaded, so maybe there's no need to reload.

2023-03-09 10:03 UTC, dpalou requested changes

2023-03-09 16:07 UTC, dpalou requested changes

2023-03-09 16:07 UTC, dpalou commented on src/core/features/settings/pages/dev/dev.ts
> +    listenStagingSitesChanges = false;
I checked if using FormBuilder and FormControl avoided this problem, but it didn't. It also triggers the onChange callback when changing the value.

I also checked how we do it in other places of the app and I found [this code](https://github.com/moodlehq/moodleapp/blob/integration/src/addons/messages/pages/settings/settings.page.ts#L55). Every time the value successfully changes we store it in a variable named "previous". In the onChange callback, if the new value is the same as the one stored in "previous" then you don't need to do anything (this happens when you revert the value).

Both solutions are similar, I prefer the one in the link above (using a "previous" or "last" variable) but it's a personal opinion, if you prefer to keep the "listen" flag feel free to do so.

2023-03-10 08:01 UTC, alfonso-salces commented on src/core/features/settings/pages/dev/dev.ts
> +    listenStagingSitesChanges = false;
Hi @dpalou!
To solve this with FormControl / FormGroup you only have to call `setValue` or `patchValue` with the options `{ emitEvent: false }`, this is an [example](https://stackblitz.com/edit/angular-uxftfs?file=src%2Fmain.ts) of what I meant.

I personally prefer work with reactive forms over template driven forms (ngModel) because of the validation outside the template and the reactivity with RxJS. I think that we are using ngModel because is similar to how AngularJS works with forms before. Anyways, in that case I will keep using ngModel over FormControl.

I will keep using the `listenStagingSitesChanges` flag.

Thanks for your review! 😄

2023-03-13 07:24 UTC, dpalou approved these changes

2023-03-27 06:10 UTC, dpalou approved these changes

2023-03-27 06:10 UTC, merged