MOBILE-4250 course: Remove module name from course module info component
moodlehq/moodleapp pull request #3582
Opened 2023-03-16 13:49 UTC by crazyserver

2023-03-17 07:30 UTC, dpalou requested changes

2023-03-17 07:30 UTC, dpalou commented on src/core/components/mod-icon/mod-icon.ts
> +    @Input() fallbackTranslation = ''; // The module name. Used also as component if set.
This comment is wrong.

2023-03-17 07:30 UTC, dpalou commented on src/core/features/course/services/course.ts
> +            (fallback ?? moduleName);
I think it's better to do `fallback || moduleName` instead. In the mod-icon component you're initializing `fallbackTranslation` to an empty string, so an empty string will be used instead of `moduleName`.

2023-03-20 08:50 UTC, crazyserver commented
Thanks Dani! Changed!

2023-03-20 10:02 UTC, dpalou approved these changes

2023-03-20 10:03 UTC, merged