MOBILE-4188: Implement teacher gradebook
moodlehq/moodleapp pull request #3583
Opened 2023-03-20 15:44 UTC by NoelDeMartin

2023-03-21 11:38 UTC, dpalou requested changes

2023-03-21 11:38 UTC, dpalou commented on src/core/features/grades/services/handlers/course-participants-option.ts
> +            }
Each iteration of this `for` will block the next one, IMO it'd be better to run this in parallel using a `Promise.all`.

Also, did you talk with Juan if we want to prefetch ALL pages? It can be a lot of WS requests.

2023-03-21 12:28 UTC, NoelDeMartin commented on src/core/features/grades/services/grades.ts
> +        return CoreConstants.CONFIG.isTeacher ?? true;
Yes, that's it.

The thing is that I wanted to get this integrated because we wanted to test some things before moving this to testing, in particular whether to show the search box by default or not. This should never end up like this in the release, so as long as it doesn't affect other issues (which I think it doesn't), I thought this would be the best default to allow us testing the new page.

But I guess I can also compile and apk myself and send it around, if we only want it for testing :shrug:

2023-04-13 07:55 UTC, dpalou requested changes

2023-04-13 07:55 UTC, dpalou commented on src/core/features/grades/services/handlers/course-option.ts
> +            return;
Before this patch, if `navOptions.grades` was defined we didn't need to invalidate user courses because `showGradebook` doesn't call `getUserCourse` in that case (it's done in `isPluginEnabledForCourse`). But we still need to call `invalidateCourseGradesPermissionsData`, because `canViewAllGrades` is used even if `grades` is defined.

So IMO we should aways call `invalidateCourseGradesPermissionsData` (we could do it only if `navOptions.grades` is undefined or true, but this WS barely returns data so IMO it's ok to always do it). And we should only call `invalidateUserCourses` is if `navOptions.grades` is undefined.

2023-04-13 07:55 UTC, dpalou commented on src/core/features/grades/services/handlers/course-participants-option.ts
> +        return CoreGrades.invalidateCourseGradesPermissionsData(courseId);
This function should be implemented just like the one in `CoreGradesCourseOptionHandlerService`, because the implementation of `isEnabledForCourse` is almost the same.

2023-04-13 07:55 UTC, dpalou commented on src/core/features/user/pages/participants/participants.page.ts
> +    constructor(protected route: ActivatedRoute) {
This route isn't used, right?

2023-04-13 08:22 UTC, NoelDeMartin commented
Thanks @dpalou for reviewing, in addition to fixing what you mentioned, I've also amended the behat tests to actually test the new functionality. So now they should really fail until MDL-77585 is released in the weekly.

PS: Sorry about the noise with the force-pushes, I messed up doing some changes but it should be ok now :sweat_smile:

2023-04-13 14:13 UTC, dpalou requested changes

2023-04-13 14:13 UTC, dpalou commented on src/core/features/grades/tests/behat/navigation.feature
> +    # User grades
These new instructions should be in a Scenario with @lms_from4.2, since they won't work in older sites.

Also, I think it would be nice to keep the old instructions to test that teachers are still able to view the users grades from their profile.

2023-04-17 10:00 UTC, dpalou approved these changes

2023-04-17 12:08 UTC, merged