Mobile 4343
moodlehq/moodleapp pull request #3687
Opened 2023-05-23 11:51 UTC by crazyserver

2023-06-14 14:05 UTC, dpalou requested changes

2023-06-14 14:05 UTC, dpalou commented on scripts/update_lang_functions.sh
> +LANGPACKS_PATH='/tmp/moodleapp-lang'
This is creating this folder at the root of the OS. Is this intended? Also, this might not work in Windows (but maybe it didn't work either before these changes).

2023-06-14 14:05 UTC, dpalou commented on package.json
> +    "lang:detect-langpacks": "./scripts/update_langpacks.sh detect",
When running the detect-langpacks locally I got this in console:

```
4 Generating local_moodlemobileapp...
==================
head: tail: illegal offset -- +illegal line count -- ../../moodle-local_moodlemobileapp/lang/en/local_moodlemobileapp.php

[15:55:00] Working directory changed to ~/Development/moodlemobile-ionic5
[15:55:01] Using gulpfile ~/Development/moodlemobile-ionic5/gulpfile.js
[15:55:01] Starting 'lang-override'...
[15:55:01] Finished 'lang-override' after 50 ms
     OK:  All done!
```

It displays a warning/error (illegal offset), but it says "OK: All done" so I'm not sure if something went wrong or not.

2023-06-15 10:16 UTC, crazyserver commented on moodle.config.json
> +        "mn": "Англи",
They changed it again... changed in the app!

2023-06-15 10:20 UTC, crazyserver commented on scripts/update_lang_functions.sh
> +LANGPACKS_PATH='/tmp/moodleapp-lang'
This is intended, I don't think we'd support Windows for now...

2023-06-15 13:31 UTC, dpalou commented on package.json
> +    "lang:detect-langpacks": "./scripts/update_langpacks.sh detect",
This was a problem in my local environment, I had a branch different than main in the moodlemobileapp plugin. Sorry for the noise.

2023-06-15 15:22 UTC, merged