MOBILE-3973 course: Support svg geopatterns in the app
moodlehq/moodleapp pull request #3706
Opened 2023-06-08 13:20 UTC by crazyserver

2023-06-14 06:26 UTC, dpalou requested changes

2023-06-14 06:26 UTC, dpalou commented on src/core/features/courses/services/courses-helper.ts
> +    courseimage?: string; // Course thumbnail.
This change could affect plugins, but I guess plugins probably won't use this. So maybe we can just change it like you did. Another option is to keep both names and deprecate the old one.

If you prefer changing it like you did, please document it in upgrade.txt.

2023-06-14 06:26 UTC, dpalou commented on src/core/features/course/pages/course-summary/course-summary.page.ts
> +        // Set the color because it won't be set at this poing.
Typo: poing.

2023-06-14 06:26 UTC, dpalou commented on src/core/features/courses/components/course-list-item/course-list-item.ts
> +        // Set the color because it won't be set at this poing.
Typo: poing.

2023-06-14 06:26 UTC, dpalou commented on src/core/features/courses/components/course-list-item/course-list-item.ts
> +                } else if (instance === 'paypal' || instance === 'fee') {
This change doesn't seem related to the issue. I'm ok with including it in this PR since it's simple, but I would change the issue name in the commit to use the release issue instead.

2023-06-15 08:09 UTC, crazyserver commented on src/core/features/courses/services/courses-helper.ts
> +    courseimage?: string; // Course thumbnail.
Deprecated!

2023-06-15 08:10 UTC, crazyserver commented
Thanks for your comments Dani! Ready to integrate

2023-06-15 08:16 UTC, dpalou approved these changes

2023-06-15 08:19 UTC, merged