MOBILE-3371: Global Search
moodlehq/moodleapp pull request #3724
Opened 2023-06-28 15:26 UTC by NoelDeMartin

Behat tests won't pass until [MDL-56020](https://tracker.moodle.org/browse/MDL-56020) is integrated in core.

2023-09-06 10:31 UTC, dpalou requested changes
Along with the comments below, shouldn't we create a link handler to open the global search if the user clicks a link to /search/index.php?

2023-09-06 10:31 UTC, dpalou commented on src/core/features/search/components/global-search-filters/global-search-filters.component.ts
> +     */
This function was confusing for me because I didn't know checkboxes could have an indeterminate status. Maybe we should document what each value does (true -> enabled, false -> disabled, null -> indeterminate).

2023-09-06 10:31 UTC, dpalou commented on src/core/features/search/components/global-search-filters/global-search-filters.component.ts
> +    allCourses: boolean | null = true;
For consistency with the `searchAllAreaCategories` comment maybe this one should be named `searchAllCourses`. But then `searchAreaCategories` can be confused with these ones too... That's the problem of having the same word for the verb and the noun lol

Maybe we can have:

```
searchAllAreaCategories: boolean | null = true;
searchAllCourses: boolean | null = true;
areaCategories: Filter<CoreSearchGlobalSearchSearchAreaCategory>[] = [];
courses: Filter<CoreEnrolledCourseData>[] = [];
```

2023-09-06 10:31 UTC, dpalou commented on src/core/components/empty-box/empty-box.scss
> +    }
Have you checked if this complies the contrast for accessibility? The dimmed empty box text will have less contrast so maybe the contrast is not enough now.

2023-09-06 10:31 UTC, dpalou commented on src/core/features/search/components/global-search-filters/global-search-filters.component.ts
> +            searchAreaCategory.checked = checked;
Every time a value changes it will call `onSearchAreaCategoryInputChanged`, which will check the status of all categories and call `emitFiltersUpdated`. The same happens for courses. So we'll be calling a lot of functions that aren't really needed, and we'll iterate the whole list n times in `getGroupFilterStatus` (so this is an O(n^2) problem).

I guess the lists shouldn't be long enough to make this be a problem, but maybe it would be better to treat it. I'm not sure if this can be treated while using ngModel, but I think you can control it if you use FormControl:

`control.setValue(foo, { emitEvent: false });`

2023-09-06 10:31 UTC, dpalou commented on src/addons/block/globalsearch/services/block-handler.ts
> +            && site.canUseAdvancedFeature('enableglobalsearch');
It might be nice to abstract this into a function since it's used twice in the app. And if we end up implementing a like handler (I'll add another comment about that) you should probably have to use it there too.

2023-09-06 12:08 UTC, NoelDeMartin commented on src/core/classes/items-management/paginated-items-manager-source.ts
> +        await this.sempahore.run(async () => {
I don't remember exactly, but I think this happened sometimes when scrolling. Maybe this happens because the infinite-loader may be triggered more than once, depending on how "fast" the loader is shown. I'm not sure how easy it would be to fix something like that.

What you mention about waiting for the previous load to finish; the problem with that is that it can create similar race conditions to the ones raised in [MOBILE-4119](https://tracker.moodle.org/browse/MOBILE-4119). For example, if we update something (like the search query or filters), and then call "load" but a load was already happening, this would be ignored and result in the wrong results list. That wouldn't be a problem if we apply this logic of "waiting the previous one to finish" in the infinite loader callback instead. But we would still need to keep the semaphore in the source, so I'm not sure it's worth looking into.

All in all, this semaphore mechanism is something that should not be necessary, but if it happens at some point I don't think it's too much of a problem. Worst case scenario would be that we load 2 or 3 pages instead of one, but that's not the end of the world keeping in mind that it should happen often. Without the semaphore, we may be loading the same page multiple times and have duplicated items, which is worse.

2023-09-07 09:24 UTC, NoelDeMartin commented on src/core/features/search/services/global-search.ts
> +        // });
I completely forgot about this xD thanks for noticing.

2023-09-07 10:03 UTC, NoelDeMartin commented on src/core/features/search/components/global-search-filters/global-search-filters.component.ts
> +    allSearchAreaCategories: boolean | null = true;
In this case I think it's better to live it like that, because this value indicates whether all the filters from the `searchAreaCategories` property are checked or not (in the same way that `allCourses` works for `courses`). I think if we rename this, we should also rename the other attributes and it'd end up like this:

```ts
    searchAllSearchAreaCategories: boolean | null = true;
    searchSearchAreaCategories: Filter<CoreSearchGlobalSearchSearchAreaCategory>[] = [];
    searchAllCourses: boolean | null = true;
    searchCourses: Filter<CoreEnrolledCourseData>[] = [];
```

I'm not convinced that is better.

2023-09-07 10:21 UTC, NoelDeMartin commented on src/core/features/search/components/global-search-filters/global-search-filters.component.ts
> +    allCourses: boolean | null = true;
I replied in the other comment, let's have the conversation there.

2023-09-07 10:22 UTC, NoelDeMartin commented on src/core/components/empty-box/empty-box.scss
> +    }
I'm using the values provided by the design specs, but I'll double check.

2023-09-07 11:25 UTC, NoelDeMartin commented on src/core/components/course-image/course-image.ts
> +export class CoreCourseImageComponent implements OnInit, OnChanges {
Eventually yes, but I didn't want to add this refactor in this PR because it's big enough as it is. And I'm not sure it can be replaced so easily without some testing. So I decided to leave it as an improvement to do later.

2023-09-07 14:41 UTC, NoelDeMartin commented on src/core/features/search/services/global-search.ts
> +        const { areas } = await site.read<CoreSearchGetSearchAreasListWSResponse>('core_search_get_search_areas_list', params);
Ok, I followed your suggestion and also added a PTR in the filters popover.

2023-09-07 15:26 UTC, NoelDeMartin commented on src/core/components/empty-box/empty-box.scss
> +    }
I just took a look and you're right it didn't pass the a11y bar; and what it's more it didn't match the design either so I'm not sure where I got that. In any case, it's fixed now. Thanks for paying attention to these details.

2023-09-07 15:44 UTC, NoelDeMartin commented on src/core/features/search/components/global-search-filters/global-search-filters.component.ts
> +            searchAreaCategory.checked = checked;
I've debugged this, and it seems to be working with `O(n)` instead of `O(n^2)`. I think this happens because given the single-threaded nature of javascript, the first input change will recompute all the filters and then when other listeners are called, they won't be triggered again (because there's already some guards in the listeners to prevent computing if the value is already applied).

2023-09-07 15:59 UTC, NoelDeMartin commented on src/core/classes/semaphore.ts
> +    }
I've removed everything relating with the semaphore because I still need to debug it further, and I think we can add it later as an improvement.

2023-09-08 09:51 UTC, dpalou commented on src/core/features/search/components/global-search-filters/global-search-filters.component.ts
> +        const courses = await CoreCourses.getUserCourses(true);
You're passing `preferCache=true`, so the `invalidateUserCourses` in the refresh function won't do anything. If we want to allow updating the course list here you should remove this param. Another option is to only refresh the search areas if the user performs a PTR, but it can be confusing for the user.

2023-09-08 09:51 UTC, dpalou commented on src/core/features/search/components/global-search-filters/global-search-filters.component.ts
> +    allSearchAreaCategories: boolean | null = true;
Ok, let's leave it like this then.

2023-09-08 10:02 UTC, dpalou requested changes

2023-09-08 10:02 UTC, dpalou commented on src/core/components/course-image/course-image.ts
> +export class CoreCourseImageComponent implements OnInit, OnChanges {
Ok, I opened an issue so we don't forget: https://tracker.moodle.org/browse/MOBILE-4413

2023-09-14 11:26 UTC, NoelDeMartin commented
@dpalou Other than what we already discussed, I've also implemented support for 2 new result types: side blocks and course sections. This is in a new commit, but all the other changes are mostly amended in the previous ones. I also had to rebase to resolve merge conflicts, so you may have to look into the commits again.

2023-09-14 13:55 UTC, dpalou requested changes

2023-09-14 13:55 UTC, dpalou commented on src/core/features/sitehome/services/handlers/index-link.ts
> +                        params: pageParams,
The unit tests are failing, I think it's related to this change.

2023-09-14 15:28 UTC, dpalou approved these changes

2023-09-14 15:28 UTC, merged