Mobile 4009
moodlehq/moodleapp pull request #3727
Opened 2023-06-29 11:29 UTC by crazyserver

2023-07-04 12:24 UTC, NoelDeMartin requested changes

2023-07-04 12:24 UTC, NoelDeMartin commented on src/core/components/components.module.ts
> +        CorePasswordModalComponent,
This declaration means that this component will be included in the initial bundle of the app, but I'm not sure if it's so important to warrant that. For modals in particular, we've already started using a pattern to load them lazily so maybe this one could also use that. For example, you can see how we're doing that for the audio recorder: https://github.com/moodlehq/moodleapp/blob/main/src/core/features/fileuploader/services/fileuploader.ts#L162

2023-07-04 12:24 UTC, NoelDeMartin commented on src/core/features/course/pages/course-summary/course-summary.page.ts
> +            while (!validated) {
Rather than doing this, I think it'd be easier to pass a validator function as an input for the modal. I think it would make a better UX as well, because the modal itself could handle the loading state or something else, rather than modals opening/closing every time (which is fine if we decide that's the better UX, but it doesn't have to be a limitation).

2023-07-04 12:24 UTC, NoelDeMartin commented on src/core/features/courses/services/courses.ts
> +};
It seems like these two types should actually be only one.

2023-07-04 12:24 UTC, NoelDeMartin commented on src/core/features/course/tests/behat/guest_access.feature
> +    Then I should find "Course summary" in the app
```suggestion
    And I press "Course 1" in the app
    Then I should find "Course summary" in the app
```

2023-07-04 12:24 UTC, NoelDeMartin commented on src/core/features/course/tests/behat/guest_access.feature
> +    And I should not find "Add submission" in the app
```suggestion
    And I should find "Test workshop name" in the app

    When I press "assignment" in the app
    Then I should not find "Add submission" in the app
```

2023-07-04 12:24 UTC, NoelDeMartin commented on src/core/features/course/tests/behat/guest_access.feature
> +    Then I should find "Course summary" in the app
```suggestion
    And I press "Course 1" in the app
    Then I should find "Course summary" in the app
```

2023-07-04 12:24 UTC, NoelDeMartin commented on src/core/features/course/tests/behat/guest_access.feature
> +    And I should find "Incorrect access password, please try again" in the app
```suggestion
    And I set the following fields to these values in the app:
      | Password | wrong |
    And I press "Submit" "ion-button" in the app
    Then I should find "Incorrect access password, please try again" in the app
```

2023-07-04 12:24 UTC, NoelDeMartin commented on src/core/features/course/tests/behat/guest_access.feature
> +    Then the header should be "Course 1" in the app
```suggestion
    Given the following config values are set as admin:
      | showhint | 1 | enrol_guest |
    When I press "Submit" "ion-button" in the app
    Then I should find "That access password was incorrect, please try again" in the app

    When I set the following fields to these values in the app:
      | Password | moodle_rules |
    And I press "Submit" "ion-button" in the app
    Then the header should be "Course 1" in the app
```

2023-07-04 12:24 UTC, NoelDeMartin commented on src/core/features/course/tests/behat/guest_access.feature
> +    And I should not find "Add submission" in the app
```suggestion
    And I should find "Test workshop name" in the app

    When I press "assignment" in the app
    Then I should not find "Add submission" in the app
```

2023-07-05 09:54 UTC, crazyserver commented on src/core/features/course/services/course-helper.ts
> +                guestAccess: !!info.status && (!info.passwordrequired || CoreCourses.isValidateGuestAccessPasswordAvailable()),
It was defined as PARAM_RAW on WS but used as a boolean. Changed! THanks!

2023-07-05 10:01 UTC, crazyserver commented on src/core/components/password-modal/password-modal.ts
> +    @Input() placeholder =  'core.login.password';
I don't think it's a problem, because it's really coming from moodle.php language.

2023-07-06 08:19 UTC, crazyserver commented on src/core/features/course/services/course.ts
> +    async isGuestAccessPreauthorized(courseId: number): Promise<boolean> {
I've inlined in the call.

2023-07-06 11:24 UTC, crazyserver commented
Thanks Noel! Can you review again, please?

2023-07-06 13:59 UTC, NoelDeMartin commented on src/core/features/course/services/course-helper.ts
> +                guestAccess: !!info.status && (!info.passwordrequired || CoreCourses.isValidateGuestAccessPasswordAvailable()),
It seems like we're actually using the same type in the app for two different types in the LMS, so we should probably fix that.

One type is indeed a boolean, but the one that is typed as a PARAM_RAW seems to be `bool | string` where a string means an error message. It's difficult to see just from the webservice description, but if you search on the code you'll eventually find it here: https://github.com/moodle/moodle/blob/master/enrol/self/lib.php#L330

So I think we should treat them as two separate types in the app as well and handle them accordingly. In particular, it seems like we're not declaring the WS response types for `core_enrol_get_course_enrolment_methods` anywhere (we just return the untyped response). We should always type WS responses explicitly in case anything changes or we refactor some types. Personally I also think we should never expose WS types to the rest of the application, but that's another matter and we're already doing that throughout the app so that's only a suggestion.

2023-07-06 14:02 UTC, NoelDeMartin commented on src/addons/storagemanager/pages/course-storage/course-storage.ts
> +        return await CoreCourses.getCourseByField('id', this.courseId);
Yeah, only reading that I still don't understand what's the difference but if we're not sure how it works we should probably look into it before calling these WSs. In any case, whatever we know about their differences, even if it's only what you just wrote in that comment, should be documented. Otherwise, these two functions are equivalent from the outside and that could cause some problems later on (I have used methods to retrieve courses myself and I wouldn't have been aware of the difference).

2023-07-07 06:54 UTC, crazyserver commented on src/core/features/course/services/course-helper.ts
> +                guestAccess: !!info.status && (!info.passwordrequired || CoreCourses.isValidateGuestAccessPasswordAvailable()),
I've chenged it a bit but checking the code, the WS returns of the guest method are wrong and should be bool|string as well (they are using the same function).

2023-07-10 11:08 UTC, NoelDeMartin approved these changes

2023-07-10 11:08 UTC, merged

2023-07-14 17:01 UTC, phyr0s commented
@NoelDeMartin  @crazyserver  this commit MOBILE-4009 courses: Pass isGuest param on navigation -->breaks the animation --> e8e2b94b1. --> this line now take time the await to process so when you go from main to one course the animation is weird and broken.

this.isGuest = CoreNavigator.getRouteBooleanParam('isGuest') ??
            (!!this.course && (await CoreCourseHelper.courseUsesGuestAccessInfo(this.course.id)).guestAccess);

2023-07-17 11:01 UTC, crazyserver commented
I'll try to amend that! Thanks for noticing!