MOBILE-4283 quiz: Allow students to hide timer
moodlehq/moodleapp pull request #3731
Opened 2023-07-06 15:07 UTC by crazyserver

2023-07-06 15:50 UTC, NoelDeMartin requested changes

2023-07-06 15:50 UTC, NoelDeMartin commented on src/core/components/timer/core-timer.html
> +                ( <a *ngIf="showTimeLeft" (click)="toggleTimeLeftVisibility()">{{ 'core.hide' | translate }}</a>
Even though this looks like an anchor, it should be a button for accessibility. Even if it isn't, I'm not sure how an anchor without `href` will be interpreted by screen readers... In any case, I'd double check the accessibility of this component (additionally, I suppose the timer should have an `aria-live` attribute to indicate that it changes, but that was already unsupported before so I guess we can leave it like that).

2023-07-07 07:10 UTC, crazyserver commented on src/core/components/timer/core-timer.html
> +                ( <a *ngIf="showTimeLeft" (click)="toggleTimeLeftVisibility()">{{ 'core.hide' | translate }}</a>
I agree on the button part, I'll change it.

About the aria live, we're using role timer that is has aria live implicit on it. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/timer_role

2023-07-10 11:12 UTC, NoelDeMartin approved these changes

2023-07-10 11:12 UTC, merged