MOBILE-4323 enrol: Create enrol delegates
moodlehq/moodleapp pull request #3754
Opened 2023-07-25 09:12 UTC by crazyserver

2023-07-26 08:29 UTC, dpalou requested changes

2023-07-26 08:29 UTC, dpalou commented on src/core/features/course/pages/course-summary/course-summary.page.ts
> +     * Self enrol in a course.
This JSDoc seems wrong, now this function seems more generic (and if I understood it right this function is for "view" enrols, not for self enrol, right?).

2023-07-26 08:29 UTC, dpalou commented on src/core/features/course/pages/course-summary/course-summary.page.ts
> +    useGuestAccess = false;
Now we can have other "view" enrol methods besides guest, so I guess we should rename this variable (and also other params of functions where this variable is passed).

2023-07-26 08:29 UTC, dpalou commented on src/core/features/course/services/course-helper.ts
> +            const enrolmentMethods = await CoreEnrolHelper.getCourseEnrolmentMethods(courseId, 'guest', siteId);
Until now the only way to access a course without being enrolled was guest access, but now there can be other methods (not in the app's core, but in custom apps or when we support site plugins). So maybe all the code related to guest should be refactored to check all "view" enrols and also use some new naming that doesn't include the guest word.

2023-07-26 08:29 UTC, dpalou commented on src/core/features/course/services/course-helper.ts
> +            const info = await AddonEnrolGuest.getGuestEnrolmentInfo(enrolmentMethods[0].id);
We should try to avoid importing addons in core, it'd be better if we could obtain this info through the delegate.

2023-07-26 08:29 UTC, dpalou commented on src/addons/enrol/guest/services/guest.ts
> +            cacheKey: this.getGuestEnrolmentInfoCacheKey(instanceId),
This functions was previously in courses and used the courses cache key. Please see my other comment about cache key to see a way to handle this.

2023-07-26 08:29 UTC, dpalou commented on src/core/features/courses/services/courses.ts
> -    isValidateGuestAccessPasswordAvailable(): boolean {
You should keep the functions isValidateGuestAccessPasswordAvailable and validateGuestAccessPassword as deprecated.

2023-07-26 08:38 UTC, crazyserver commented on src/addons/enrol/guest/services/enrol-handler.ts
> +        }
Nope, sorry!

2023-07-26 08:44 UTC, crazyserver commented on src/addons/enrol/self/services/enrol-handler.ts
> +        }
Yep it can happen, it will show two icons in the course list (as LMS does)

2023-07-26 08:48 UTC, crazyserver commented on src/core/features/courses/services/courses.ts
> -    isValidateGuestAccessPasswordAvailable(): boolean {
isValidateGuestAccessPasswordAvailable has been recently created and not released.

2023-07-26 08:48 UTC, dpalou requested changes

2023-07-26 08:48 UTC, dpalou commented on src/core/features/courses/services/courses.ts
> +     * @deprecated since 4.3, use AddonEnrolSelf.selfEnrol instead.
Shouldn't we recommend using the delegate method instead of using the addon directly?

2023-07-26 08:48 UTC, dpalou commented on src/core/features/enrol/services/enrol-delegate.ts
> +    SELF = 'self', // User can enrol itself.
"itself" shouldn't be used for people, I'd say "himself or herself".

2023-07-26 08:48 UTC, dpalou commented on src/core/features/enrol/services/enrol-delegate.ts
> +    canAccess?(method: CoreCourseEnrolmentMethod): Promise<boolean>;
The typing could be improved so only certain types of plugins need to define the functions. E.g. you can have:

```
export interface CoreEnrolViewHandler extends CoreEnrolHandler {
    enrolmentAction: CoreEnrolAction.VIEW;
    
    canAccess(method: CoreCourseEnrolmentMethod): Promise<boolean>;
    ...
}
```

This is pseudo code, I haven't tried it. But this way you can define specific functions for each action.

2023-07-26 08:48 UTC, dpalou commented on src/core/features/enrol/services/enrol-helper.ts
> +            }
This can be changed to a single line:

`addBrowserOption = addBrowserOption || action === CoreEnrolAction.BROWSER;`

2023-07-26 08:48 UTC, dpalou commented on src/core/features/enrol/services/enrol-helper.ts
> +        });
Why are you doing this before calling getCourseEnrolmentMethods? After calling it you're also checking for browser or not supported. And in here you don't know if the methods are enabled or not, right? You don't have `method.status`.

2023-07-26 08:48 UTC, dpalou commented on src/core/features/enrol/services/enrol-helper.ts
> +                    // Only add the browser action once.
This comment (and the one in VIEW) is wrong.

2023-07-26 08:48 UTC, dpalou commented on src/core/features/siteplugins/classes/handlers/enrol-handler.ts
> + * Handler to support a enrol using a site plugin.
I'd put a `todo` or similar specifying that right now only browser methods can be supported.

2023-07-26 08:48 UTC, dpalou commented on src/core/features/siteplugins/services/siteplugins-helper.ts
> +        const action = handlerSchema.enrolmentAction ?? CoreEnrolAction.BROWSER;
IMO it doesn't make much sense to allow specifying an enrolmentAction because plugins cannot implement the required functions like "enrol", I'd always set this to BROWSER for now and I'd add a `todo` to support the rest of actions.

2023-08-22 08:59 UTC, dpalou commented on src/core/features/course/services/course-helper.ts
> +            const enrolmentMethods = await CoreEnrolHelper.getCourseEnrolmentMethods(courseId, 'guest', siteId);
After talking to Pau we decided it was best to use the "guest" word instead of "view". This way we don't need to refactor as much code, and in LMS they also use the guest word in generic classes like enrol_plugin (e.g. try_guestaccess).

2023-08-24 09:30 UTC, dpalou approved these changes

2023-08-24 09:35 UTC, merged