MOBILE-4272: Decouple workshop from initial bundle
moodlehq/moodleapp pull request #3756
Opened 2023-07-26 02:59 UTC by NoelDeMartin

2023-07-27 10:49 UTC, dpalou requested changes

2023-07-27 10:49 UTC, dpalou commented on src/addons/mod/workshop/services/handlers/prefetch.ts
> +    });
Why is this assign needed? Is it to be able to access these properties without having to create the instance?

I don't like the fact that we need to replicate the values, but maybe there's no other way.

2023-07-27 10:49 UTC, dpalou commented on src/addons/mod/workshop/services/handlers/prefetch-lazy.ts
> +export class AddonModWorkshopPrefetchHandlerService extends CoreCourseActivityPrefetchHandlerBase {
At first it made more sense to me to name this file just `prefetch`, and the file that loads this file lazily name it `prefetch-lazy`, but I think in modules we do it like you did here, the module that is loaded lazily we call it "-lazy", so for consistency I guess we should leave it like this.

2023-07-31 00:48 UTC, NoelDeMartin commented on src/addons/mod/workshop/services/handlers/prefetch.ts
> +    });
Yes, these are the only values that are needed before initializing the async instance.

I also don't like the idea of replicating the values. I think we could find a way to avoid it, but it'll probably result in even more indirection and more complex code :/. Although maybe it's worth it, I'll explore it.

2023-07-31 00:50 UTC, NoelDeMartin commented on src/addons/mod/workshop/services/handlers/prefetch-lazy.ts
> +export class AddonModWorkshopPrefetchHandlerService extends CoreCourseActivityPrefetchHandlerBase {
Ok we can discuss the naming before having the final version, I'm also not 100% sure about it. I'll bring it up in some of our team meetings.

2023-08-31 09:54 UTC, dpalou approved these changes

2023-08-31 09:54 UTC, merged