MOBILE-4362 behat: Improve BBB wait steps
moodlehq/moodleapp pull request #3766
Opened 2023-08-01 09:04 UTC by NoelDeMartin

2023-08-01 09:15 UTC, dpalou requested changes

2023-08-01 09:15 UTC, dpalou commented on local_moodleappbehat/tests/behat/behat_app.php
> +            $timeout = 6000;
I think `time()` returns time in seconds, so this 6000 means it will wait 1h and 40 minutes?

2023-08-01 23:57 UTC, NoelDeMartin commented on local_moodleappbehat/tests/behat/behat_app.php
> +            $timeout = 6000;
You're right, actually I should have noticed because if I wanted to wait 60 seconds in milliseconds it should have been 60000 xD. Anyhow, it's fixed now.

2023-08-02 06:35 UTC, dpalou approved these changes

2023-08-02 06:35 UTC, merged