MOBILE-4401 wiki: Fix selected subwiki when wiki is empty
moodlehq/moodleapp pull request #3767
Opened 2023-08-01 11:02 UTC by dpalou

This commit avoids a redundant error and also allows the create button to appear if the user has permissions to create the first page

2023-08-01 11:26 UTC, alfonso-salces requested changes

2023-08-01 11:26 UTC, alfonso-salces commented on src/addons/mod/wiki/components/index/index.ts
> +                } else {
Maybe this is a good moment to improve the cognitive complexity using guard clauses.

I think that we can create a new method to improve the readability, something like that is fine.

    /**
     * Set current page.
     *
     * @param subwikiPages list of subwikis to find in.
     */
    setCurrentPage(subwikiPages: AddonModWikiSubwikiPage[]): void {
        if (!this.currentPage) {
            return;
        }

        if (this.pageTitle) {
            const page = subwikiPages.find((page) => page.title === this.pageTitle );

            if (!page) {
                return;
            }

            this.currentPage = page.id;
        }

        const firstPage = subwikiPages.find((page) => page.firstpage );

        if (!firstPage) {
            return;
        }

        this.currentPage = firstPage.id;
        this.pageTitle = firstPage.title;
    }


With that, we can remove the `if (!this.currentPage)` completly

2023-08-01 11:30 UTC, alfonso-salces commented on src/addons/mod/wiki/components/index/index.ts
```suggestion
setCurrentPage(subwikiPages);
```

2023-08-01 12:23 UTC, dpalou commented on src/addons/mod/wiki/components/index/index.ts
> +                } else {
Thanks Alfonso, I applied your suggestion. Also, I realised that, with my new code, the block of code after "`const dbPages`" wasn't needed anymore because now we're always setting `pageTitle` to `this.wiki.firstpagetitle` if needed so I removed a few lines there too.

2023-08-02 05:46 UTC, alfonso-salces approved these changes

2023-08-02 05:46 UTC, merged