Mobile 4405
moodlehq/moodleapp pull request #3777
Opened 2023-09-01 10:18 UTC by alfonso-salces

2023-09-07 14:11 UTC, dpalou requested changes

2023-09-07 14:11 UTC, dpalou commented on src/core/services/storage.ts
> +    static forSite(site: CoreSite): AsyncInstance<CoreStorageService> {
forCurrentSite and forSite don't have JSDoc.

2023-09-07 14:11 UTC, dpalou commented on src/core/services/storage.ts
> +    }
This function will create a new instance every time is executed, it's not using SERVICE_INSTANCES. Shouldn't it use SERVICE_INSTANCES to avoid creating the same instance several times?

2023-09-07 14:11 UTC, dpalou commented on src/core/services/sites.ts
> +            await CoreAutoLogout.handleAppClosed(site);
IMO it'd be better to move this code to a new function so the restoreSession function is more readable.

2023-09-07 14:11 UTC, dpalou commented on src/core/classes/site.ts
> +                CoreEvents.trigger(CoreEvents.SESSION_EXPIRED, { redirectPath: Router.url }, this.id);
This commit can give us problems. I see 2 right now:

1. You need to pass the query parameters, not just the path. Because some parameters aren't included in the URL.
2. When the current page is "restored", the user will be sent to the "final" page, he won't have the whole history. And the only way to go back to a "previous" page will be to click the bottom tab to go back to the root page. IMO this can be confusing, some users might not know that clicking the tab will redirect to the root. Also, loading some pages directly can cause problems as Noel explained in the DevJam webinar (e.g. site plugin pages might not have some data loaded if they're opened directly).

IMO this change deserves its own issue and a better analysis.

2023-09-07 14:12 UTC, dpalou commented
Hi Alfonso, I decided to pass the review to Noel because he had some concerns about the storage implementation and he knows this part better than me. I sent you some comments about things I saw while reviewing the patch.

2023-09-12 06:46 UTC, alfonso-salces commented on src/core/classes/site.ts
> +                CoreEvents.trigger(CoreEvents.SESSION_EXPIRED, { redirectPath: Router.url }, this.id);
Hi Dani, well in that case im gonna drop this commit and I will open an issue soon.
Thanks for the review!

2023-09-26 12:44 UTC, NoelDeMartin approved these changes

2023-09-26 13:44 UTC, dpalou approved these changes

2023-09-26 13:44 UTC, merged