Mobile 4348
moodlehq/moodleapp pull request #3799
Opened 2023-09-28 14:54 UTC by crazyserver

2023-10-02 13:38 UTC, dpalou requested changes

2023-10-02 13:38 UTC, dpalou commented on src/core/features/course/components/module-completion/core-course-module-completion.html
> +            </ion-button>
It's a bit weird that a button with `*ngIf="completed"` displays "to do" and has class `completion_incomplete`, and a button with `*ngIf="!completed"` displays "done" and has class `completion_complete` a few lines below. The logic says it should be the opposite, right?

2023-10-02 13:38 UTC, dpalou commented on src/core/features/course/components/module-completion/module-completion.ts
> +    @Output() completionChanged = new EventEmitter<CoreCourseModuleCompletionData>(); // Notify when completion changes.
Why are you defining the new 2 inputs and the output here? They're already defined in `CoreCourseModuleCompletionBaseComponent`, right?

2023-10-02 13:38 UTC, dpalou commented on src/core/features/course/components/module/core-course-module.html
> +                        <!-- Buttons defined by the module handler. -->
This comment should now say "Button" in singular.

2023-10-02 13:38 UTC, dpalou commented on src/core/features/course/components/module/core-course-module.html
> +                        <ion-button fill="clear" class="core-module-buttons-more core-animate-show-hide" *ngIf="module.handlerData.button"
It looks a bit weird that a single button has a class named "core-module-buttons-more". If it's to avoid breaking existing custom themes maybe you should just keep the outer div with this class?

2023-10-02 13:38 UTC, dpalou commented on src/core/features/course/services/module-delegate.ts
> +    button?: CoreCourseModuleHandlerButton;
IMO the changes in this type should be documented in upgrade.txt since they are important changes.

2023-10-02 14:24 UTC, crazyserver commented on src/core/features/course/components/module/core-course-module.html
> +                        <ion-button fill="clear" class="core-module-buttons-more core-animate-show-hide" *ngIf="module.handlerData.button"
Nah, I'll change the class name

2023-10-02 14:27 UTC, crazyserver commented on src/core/features/course/components/module-completion/module-completion.ts
> +    @Output() completionChanged = new EventEmitter<CoreCourseModuleCompletionData>(); // Notify when completion changes.
I was going to delete the base element but then I rejected the change

2023-10-02 14:38 UTC, crazyserver commented on src/core/features/course/components/module/core-course-module.html
> +                        <ion-button fill="clear" class="core-module-buttons-more core-animate-show-hide" *ngIf="module.handlerData.button"
LOl!

2023-10-02 14:38 UTC, crazyserver commented on src/core/features/course/components/module-completion/core-course-module-completion.html
> +            </ion-button>
Lol!

2023-10-02 14:48 UTC, dpalou submitted a review, later dismissed

2023-10-03 06:42 UTC, dpalou approved these changes

2023-10-03 06:42 UTC, merged