Mobile 4362
moodlehq/moodleapp pull request #3825
Opened 2023-10-17 10:22 UTC by crazyserver

2023-10-17 11:09 UTC, NoelDeMartin commented on src/core/features/course/pages/list-mod-type/list-mod-type.ts
> +                    mod.indent = 0;
Is there a way to avoid this mutation? For example, passing a `showIndent="false"` or something.

I don't like the idea of "lying" about this module. It does have an indent, we just don't want to show it. Doing this may create some unintended consequences in the future, for example if we rely on the `indent` property for something else. I'm aware of YAGNI, but it's also important to keep a proper data model rather than patching it for our convenience.

2023-10-17 11:09 UTC, NoelDeMartin commented on src/core/features/course/pages/list-mod-type/list-mod-type.ts
> +    showSectionId = 0;
This should be called `showSectionIndex`, or even better `lastShownSectionIndex`, `shownSectionsLength`, etc.

2023-10-17 11:09 UTC, NoelDeMartin commented on src/core/features/course/pages/list-mod-type/list-mod-type.ts
> +    static readonly LOAD_MORE_ACTIVITIES = 20; // How many activities should load each time showMoreActivities is called.
```suggestion
    private static readonly PAGE_LENGTH = 20; // How many activities should load each time showMoreActivities is called.
```

Besides the naming, this could be a constant declared in the function where it is used, given that it's only used in one place at the moment.

2023-10-17 11:09 UTC, NoelDeMartin commented on src/core/features/course/pages/list-mod-type/list-mod-type.ts
> +            if (!sections[i].hasContent || !sections[i].modules) {
I see a couple of problems of following this approach.

First, it makes the code beyond more complicated (rather than just checking the length of the sections to calculate `canLoadMore`, we have to do yet another loop).

Also, it creates the possibility to load 0 items. Imagine the case that we have 20 modules in a row without content. It's very unlikely, but better to make it impossible.

Rather than doing this, I think it'd be better to filter these out when we assign the sections array in the `fetchData` method. Actually, it seems like we are already filtering them so maybe we could just move this additional check in there.

2023-10-17 11:09 UTC, NoelDeMartin commented on src/core/features/course/pages/list-mod-type/list-mod-type.ts
> +        }
```suggestion
        this.canLoadMore = sections.slice(i).some(section => sections[i].hasContent && sections[i].modules && sections[i].modules.length > 0);
```

If you follow my suggestion above, this will be removed. But if you don't, that's a better approach.

2023-10-17 11:12 UTC, dpalou requested changes

2023-10-17 11:12 UTC, dpalou commented on src/core/features/course/pages/list-mod-type/list-mod-type.ts
> +            this.canLoadMore = false;
This line isn't needed because you do it again in showMoreActivities.

2023-10-17 11:12 UTC, dpalou commented on src/core/features/course/pages/list-mod-type/list-mod-type.ts
> +     * Show more activities (only used when showing all the sections at the same time).
This comment says "only used when showing all the sections at the same time". But looking at the code, can we see only 1 section?

2023-10-17 11:12 UTC, dpalou commented on src/core/features/course/pages/list-mod-type/list-mod-type.ts
> +        for (i = this.showSectionId + 1; i < sections.length; i++) {
In the first execution, `i` will be 1 so you will always ignore the section 0. Do we really want this?

2023-10-17 11:12 UTC, dpalou commented on src/core/features/course/pages/list-mod-type/list-mod-type.ts
> +        this.canLoadMore = i < sections.length;
```suggestion
        this.canLoadMore = i < sections.length - 1;
```
Shouldn't this code be like this? If I'm not wrong, if `i` is `sections.length - 1` it means that the last section was already treated so there are no more to treat. Your code handles it properly in the next if, but IMO there's no need to in this case.

2023-10-17 11:12 UTC, dpalou commented on src/core/features/course/pages/list-mod-type/list-mod-type.ts
> +                if (sections[i].hasContent && sections[i].modules && sections[i].modules?.length > 0) {
```suggestion
                if (sections[i].hasContent && sections[i].modules?.length > 0) {
```

2023-10-17 11:12 UTC, dpalou commented on src/core/features/course/pages/list-mod-type/list-mod-type.ts
> +    showSectionId = 0;
```suggestion
    showSectionIndex = 0;
```
I think this name is better since this is not the section ID, it's the index in the array of sections.

2023-10-17 15:14 UTC, NoelDeMartin commented on src/core/features/course/pages/list-mod-type/list-mod-type.ts
> +        this.canLoadMore = i < this.sections.length;
```suggestion
        let modulesLoaded = 0;

        while (this.lastShownSectionIndex < this.sections.length - 1 && modulesLoaded >= CoreCourseListModTypePage.PAGE_LENGTH) {
            this.lastShownSectionIndex++;

            modulesLoaded += this.sections[this.lastShownSectionIndex].modules.length;
        }

        this.canLoadMore = this.lastShownSectionIndex < this.sections.length - 1;
```

This simplifies the code and takes care of @dpalou's open discussion.

2023-10-18 14:14 UTC, dpalou submitted a review, later dismissed

2023-10-18 14:18 UTC, NoelDeMartin approved these changes

2023-10-19 12:10 UTC, merged