Mobile 4465
moodlehq/moodleapp pull request #3850
Opened 2023-11-10 12:52 UTC by crazyserver

2023-11-17 15:04 UTC, dpalou requested changes

2023-11-20 09:15 UTC, crazyserver commented on src/core/features/courses/components/components.module.ts
> -        CoreCoursesCourseProgressComponent,
Nice catch and good idea! I'll work on that when I have a moment.
On the meantime I've just changed the code so the component is smaller and easier to maintain, using the new component.

2023-11-20 09:15 UTC, crazyserver commented on src/core/features/course/components/components.module.ts
> -        CoreCourseModuleDescriptionComponent,
Recovering it....

2023-11-20 10:02 UTC, dpalou approved these changes

2023-11-20 10:04 UTC, merged