Mobile 3947
moodlehq/moodleapp pull request #3865
Opened 2023-11-28 13:52 UTC by dpalou

2023-11-28 16:03 UTC, NoelDeMartin requested changes

2023-11-28 16:03 UTC, NoelDeMartin commented on webpack.config.js
> +                ngDevMode: true,
Why is this necessary? As far as I know, this file is not even being used yet because the custom builder to customize webpack was removed during the upgrade. Or is this now being used out of the box with the new builders?

There is a card open in trello to look into webpack, so if it is in fact not being used we can look into this at that point (maybe add a comment with some info in case it's relevant).

2023-11-29 08:59 UTC, crazyserver commented on webpack.config.js
> +                ngDevMode: true,
Nah, was just for testig purposes...

2023-11-29 09:34 UTC, NoelDeMartin approved these changes

2023-11-29 09:34 UTC, merged