MOBILE-3947: Fix build
moodlehq/moodleapp pull request #3868
Opened 2023-11-29 11:37 UTC by NoelDeMartin

2023-11-29 14:43 UTC, dpalou requested changes

2023-11-29 14:43 UTC, dpalou commented on src/core/features/emulator/services/zip.ts
> +        const onProgress = onProgressFunction as (ev: {loaded: number; total: number}) => void;
This threw an error because the Zip API has changed in awesome-cordova-plugins, they added an onSuccess callback before the onProgress. So this change is wrong IMO.

I don't know why they added this new onSuccess callback, the function returns a Promise so the "success" should be when the promise is resolved, I don't know why we need a callback for that. And this change in the API is a breaking change for plugins, although I think it won't affect any of them.

Maybe we should remove @awesome-cordova-plugins/zip and implement it ourselves as we did with other plugins, keeping the old API. What do you think?

2023-11-29 15:51 UTC, NoelDeMartin commented on src/core/features/emulator/services/zip.ts
> +        const onProgress = onProgressFunction as (ev: {loaded: number; total: number}) => void;
Ok, I looked into it and it seems like the API is quite straightforward so I removed the native plugin and implemented the wrapper from scratch.

2023-11-30 09:28 UTC, dpalou approved these changes

2023-11-30 09:28 UTC, merged