MOBILE-3947: Fix application startup
moodlehq/moodleapp pull request #3877
Opened 2023-12-05 09:10 UTC by NoelDeMartin

2023-12-05 10:25 UTC, dpalou requested changes

2023-12-05 10:25 UTC, dpalou commented on src/core/constants.ts
> +export const NULL = new InjectionToken('null');
Shouldn't we call this variable something like `INJECT_NULL` or `INJECTION_TOKEN_NULL` instead of just `NULL`? I feel like NULL is too generic.

2023-12-05 13:07 UTC, NoelDeMartin commented on src/core/constants.ts
> +export const NULL = new InjectionToken('null');
That's how I did it initially, but then I realized that all the injection tokens from Angular don't follow that convention, they are just called whatever they provide: `ROUTES`, `APP_INITIALIZER`, `INJECTOR`, etc.

If you still don't like it, we can rename it to something like `NULL_INJECTION_TOKEN`, I wouldn't mind changing it.

2023-12-05 13:52 UTC, dpalou requested changes

2023-12-05 13:52 UTC, dpalou commented on src/core/constants.ts
> +export const NULL = new InjectionToken('null');
I prefer `NULL_INJECTION_TOKEN`. I understand what you say about Angular not following that convention, but those words cannot be confused with a primitive type, while `NULL` can. I wouldn't mind naming it `NULL` if it was declared in a file dedicated to injection, but since this constant is declared in core/constants I think it's better to name it `NULL_INJECTION_TOKEN`.

2023-12-11 07:05 UTC, dpalou approved these changes

2023-12-11 07:05 UTC, merged