MOBILE-3947: Fix forum tests
moodlehq/moodleapp pull request #3880
Opened 2023-12-14 10:44 UTC by NoelDeMartin

2023-12-14 10:58 UTC, crazyserver requested changes

2023-12-14 10:58 UTC, crazyserver commented on src/core/features/reminders/tests/behat/course_reminders.feature
> +    When I set the field "Value" to "2" in the app
I don't really like this change, I think it would be better to change the behavious of behat to adapt to the ionic changes: calling ionChange after a change or simulating the clicks inside the setField function.

2023-12-14 11:09 UTC, NoelDeMartin commented on src/core/features/reminders/tests/behat/course_reminders.feature
> +    When I set the field "Value" to "2" in the app
Ok, it seems like there are other things affecting that test anyways, so I removed that commit from the PR.

2023-12-14 11:14 UTC, crazyserver approved these changes

2023-12-18 12:43 UTC, crazyserver requested changes

2023-12-19 08:52 UTC, NoelDeMartin commented
Closing in favour of #3884.

2023-12-19 08:52 UTC, closed without merging