MOBILE-4481 ws.ts: Get mimetype from file transfer headers
moodlehq/moodleapp pull request #3881
Opened 2023-12-14 11:19 UTC by alfonso-salces

2023-12-15 07:29 UTC, dpalou requested changes

2023-12-15 07:29 UTC, dpalou commented on src/core/services/ws.ts
> +                    const requestContentType = fileDownloaded.headers?.['Content-Type']?.match(/\[(.*?)\]/)?.[1];
IMO this line should be after the comment "Not valid, get the file's mimetype."

2023-12-15 07:29 UTC, dpalou commented on src/core/services/ws.ts
> +            const fileDownloaded = await transfer.download(url, fileEntry.toURL(), true, {
I noticed that this `fileDownloaded` is typed as `any` in ionic-native. I also noticed that the types modified in your PR in the file-transfer fork are wrong, here:

https://github.com/moodlemobile/cordova-plugin-file-transfer/commit/a8ee06df0fc368f2d7a2af261f872e86c190f34b#diff-093ad82a25aee498b11febf1cdcb6546e4d223ffcb49ed69cc275ac27ce0ccceR54

It should be `headers` instead of `header`, and it should be typed as optional because in iOS the headers won't be returned.

Taking into account that the Cordova plugin defines types and that ionic-native is wrongly typed (IMO the result shouldn't be type `any`), I propose that we stop using ionic-native for file-transfer as we did with other Cordova plugins.

FileTransfer is only used in CoreWS, and I don't think any plugin will use it directly because files should be downloaded through CoreFilepool, so in this case we might just use the Cordova plugin directly (using window.FileTransfer), without creating a wrapper. Site plugins will lose access to the FileTransfer service because it will no longer exist.

Let's discuss this internally with the rest of the team.

2024-01-23 07:51 UTC, dpalou requested changes

2024-01-23 07:51 UTC, dpalou commented on package.json
> +    "@moodlehq/cordova-plugin-file-transfer": "^1.7.1-moodle.8",
We don't use "^" in our plugins because we control their releases. Sometimes we introduce breaking changes in minor releases and we don't want our app to install those minors by mistake.

2024-01-23 07:51 UTC, dpalou commented on src/core/services/ws.ts
> +            onProgress && transfer.onprogress(onProgress[1]);
```suggestion
            if (onProgress) {
                transfer.onprogress = onProgress;
            }
```
This line is wrong, using onProgress[1] in a callback will return undefined IMO. The reason TS was complaining is because onprogress needs to be assigned like this.

2024-01-23 07:51 UTC, dpalou commented on src/core/services/ws.ts
> +                    (params) => resolve(params),
Can we rename this "params" to "result" or something like this? The name confused me a bit because I thought they were "input" parameters.

2024-01-23 07:51 UTC, dpalou commented on src/core/services/ws.ts
> +                transfer.download(
With your new code you lost 2 parameters: trustAllHosts and options (the headers we send). You need to pass them after the error callback.

2024-01-23 07:51 UTC, dpalou commented on src/core/services/ws.ts
> +                    const requestContentType = fileDownloaded.headers?.['Content-Type']?.match(/\[(.*?)\]/)?.[1];
When getting the mimetype using a HEAD request we found that in some cases the mimetype could contain "parameters" like charset (see [this code](https://github.com/moodlehq/moodleapp/blob/main/src/core/services/ws.ts#L343)). I guess it can happen here too, so I would add the treatment too just in case

2024-01-23 07:51 UTC, dpalou commented on src/core/services/ws.ts
> +                    const requestContentType = fileDownloaded.headers?.['Content-Type']?.match(/\[(.*?)\]/)?.[1];
In iOS, the headers are returned without "[]" in their values so this regex won't work properly. IMO it would be better if the Android's native code also removed those characters so the values returned are the same in both platforms. Example of what is returned in iOS:

Accept-Ranges: "bytes"
Cache-Control: "private, max-age=3600, no-transform"
Connection: "keep-alive"
Content-Disposition: "inline; filename=\"typesofsport.jpg\""
Content-Length: "96027"
Content-Type: "image/jpeg"
Date: "Tue, 23 Jan 2024 07:40:58 GMT"
Etag: "\"3b50e1ce6b7326e3cfdb847478215a49f6153c8b\""
Expires: "Tue, 23 Jan 2024 08:40:58 GMT"
Last-Modified: "Tue, 19 Jun 2018 11:37:21 GMT"
Pragma: ""
Server: "nginx"

2024-01-23 07:51 UTC, dpalou commented on src/core/services/ws.ts
> +            const transfer = new window.FileTransfer();
IMO we should stop using `@awesome-cordova-plugins/file-transfer` everywhere, not just in this function. I think it's only used in the WS provider so it shouldn't be a lot of work

Also, right now in browser we override the `FileTransfer` service to make this work in our webapp. If we stop using `@awesome-cordova-plugins/file-transfer` then we need to change our browser code to implement the Cordova API instead of this service (basically, we need to implement `window.FileTransfer` instead of an Angular service). You can search for `FileTransferMock` to see our implementation.

2024-01-29 12:09 UTC, alfonso-salces commented
Reminder: Update "@moodlehq/cordova-plugin-file-transfer" dependency to the last version before merge.

2024-01-30 11:13 UTC, dpalou requested changes

2024-01-30 11:13 UTC, dpalou commented on src/core/features/emulator/services/file-transfer.ts
> -            this.reject = reject;
This was done to be able to reject the promise when calling `abort`. Now you should probably do the same but using `errorCallback` instead. This means you can replace the `reject` property with an `errorCallback` or similar, and in `abort` you should call the `errorCallback` instead.

2024-01-30 11:13 UTC, dpalou commented on src/core/features/emulator/services/file-transfer.ts
> +    ): Promise<unknown> {
The original function from the Cordova plugin doesn't return a Promise, it returns void because it uses the callbacks to return the data. So IMO it would be better to be consistent with the original API and remove all the Promises usage in here, just use the callbacks.

2024-01-30 11:13 UTC, dpalou commented on src/core/features/emulator/services/file-transfer.ts
> +                    .then((entry: unknown) => {
Why are you using `unknown` here? Wouldn't it be better to use the inferred FileEntry type instead? If it causes conflicts with the type defined in `CoreFileTransferDownloadResponse`, you can try importing:

`import { FileEntry } from '@awesome-cordova-plugins/file/ngx';`

and use this type in `CoreFileTransferDownloadResponse`.

2024-01-30 11:13 UTC, dpalou commented on src/core/features/emulator/services/file-transfer.ts
> +    onprogress(event: ProgressEvent<EventTarget>): void {
`onprogress` now needs to be a property, not a function, since it's used like this:

`transfer.onprogress = onProgress;`

2024-01-30 11:13 UTC, dpalou commented on src/core/features/emulator/services/file-transfer.ts
> +    ): Promise<FileUploadResult> {
As with download, I think it's better to remove all Promises from here and just use the callbacks.

2024-01-30 11:13 UTC, dpalou commented on src/core/features/native/native.module.ts
> -        FileTransfer,
Please add a note in upgrade.txt mentioning that the `FileTransfer` service is no longer available.

2024-01-30 11:13 UTC, dpalou commented on src/core/services/ws.ts
> +                entry: globalThis.FileEntry;
If you try to use the type `FileEntry` from `@awesome-cordova-plugins/file/ngx`, do you get a conflict? In general in the app we use that type, so it would be great if we could use the same type everywhere. I'm not sure if they're compatible or not.

2024-02-02 09:07 UTC, dpalou requested changes

2024-02-02 09:07 UTC, dpalou commented on src/core/features/emulator/services/file-transfer.ts
>      progressListener?: (event: ProgressEvent) => void;
This property is no longer used and should be removed (it's never assigned), now you need to use `onprogress` instead.

2024-02-02 09:07 UTC, dpalou commented on src/core/features/emulator/services/file-transfer.ts
> +    onprogress!: (event: ProgressEvent) => void;
```suggestion
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    onprogress: (event: ProgressEvent) => void = () => {};
```

Instead of using "!" I think it's better to initialize this with a function that does nothing. This way you can always call onprogress in the implementation without having to check if it exists or not. E.g. instead of doing this:

```
if (this.progressListener) {
    this.progressListener(ev);
}
```

Now you will be able to just do:

`this.onprogress(ev);`

2024-02-02 09:39 UTC, dpalou approved these changes

2024-02-02 10:04 UTC, merged