MOBILE-3947 reminders: Fix tests
moodlehq/moodleapp pull request #3886
Opened 2024-01-09 13:31 UTC by NoelDeMartin

2024-01-10 11:13 UTC, crazyserver requested changes

2024-01-10 11:13 UTC, crazyserver commented on src/core/features/reminders/components/date/date.html
> +<span class="sr-only" *ngIf="reminderMessage">{{ reminderMessage }}</span>
I would move that inside the button, and would use the status aria role.

2024-01-10 11:13 UTC, crazyserver commented on src/core/features/reminders/tests/behat/activity_reminders.feature
> +    Then I should find "Reminder set for" in the app
This space was added on purpose to limit the word: we know this space will also be there. But it's correct anyway.

2024-01-11 14:43 UTC, NoelDeMartin commented on src/core/features/reminders/tests/behat/activity_reminders.feature
> +    Then I should find "Reminder set for" in the app
I was aware of that, but I think it's better to trim strings in Behat steps, given that users look at entire words, not trailing whitespace. Ideally, these steps would look for the complete text including the reminder date, but since those values are dynamic it wouldn't be straightforward to do.

2024-01-11 15:11 UTC, NoelDeMartin commented
Thanks for the review @crazyserver. I've looked at your suggestions and added a couple more commits, please take another look.

2024-01-11 15:30 UTC, crazyserver approved these changes

2024-01-11 15:40 UTC, NoelDeMartin commented on src/addons/messages/tests/behat/basic_usage.feature
> -  @ionic7_failure
What do you mean? I've removed all the `@ionic7_failure` from the codebase.

2024-01-11 16:48 UTC, crazyserver commented on src/addons/messages/tests/behat/basic_usage.feature
> -  @ionic7_failure
Tha's it, the other test that you fixed.

2024-01-11 20:48 UTC, crazyserver requested changes

2024-01-11 20:48 UTC, crazyserver commented on src/testing/services/behat-runtime.ts
> +    get domUtils(): TestingBehatDomUtilsService {
Is this here for testing purposes? I think this is not used anywhere, right?

2024-01-15 09:48 UTC, crazyserver approved these changes

2024-01-16 10:41 UTC, crazyserver approved these changes

2024-01-16 10:41 UTC, merged