MOBILE-4496: Improve Behat CI
moodlehq/moodleapp pull request #3914
Opened 2024-01-30 09:13 UTC by NoelDeMartin

2024-01-30 14:32 UTC, dpalou requested changes

2024-01-30 14:32 UTC, dpalou commented on .github/workflows/acceptance.yml
> -        default: ''
Do you think it would be possible to keep this option? I've barely used, but Pau uses it sometimes.

2024-01-31 07:34 UTC, NoelDeMartin commented on local_moodleappbehat/tests/behat/behat_app.php
> +     * @Then /^a notification with title (".+") should( not)? be scheduled(?: (\d+) minutes before the "(.+)" assignment due date)? in the app$/
I think we already had a similar discussion about [the notification step](https://github.com/moodlehq/moodleapp/blob/main/local_moodleappbehat/tests/behat/behat_app.php#L480), although I cannot recall where.

I consider this step a custom step to test our application; it's not a step that we'll document for plugin developers to reuse. So I think it's ok if it's very specific to our app tests, and if we ever need to make it more generic we can do it then. But I think generalizing now would be wasted efforts.

2024-01-31 10:07 UTC, NoelDeMartin commented
Thanks for the review @dpalou, please take another look.

Besides tackling your suggestions, I've also refactored the CI pipeline further so that it uploads failure reports and completes all the suites even if others fail. That's more in line with the way it worked before, and it'll often be useful see everything that fails; not just the first one.

2024-01-31 14:05 UTC, dpalou approved these changes

2024-01-31 14:05 UTC, merged