MOBILE-4304: Replace WebSQL with sqlite-wasm
moodlehq/moodleapp pull request #3927
Opened 2024-02-08 14:30 UTC by NoelDeMartin

2024-02-12 11:15 UTC, dpalou requested changes

2024-02-12 11:15 UTC, dpalou commented on src/testing/services/behat-runtime.ts
> +            }
Wouldn't it be better to fetch the contents only if the parameter `contents` isn't empty? The URL contents aren't used otherwise.

I guess it won't be usual to have this step with contents="", but you're checking in the next `if` so maybe it makes sense to check it here too.

2024-02-12 11:15 UTC, dpalou commented on src/core/features/emulator/services/db.ts
> +        return asyncInstance(async () => {
Maybe we should add a comment explaining why the returned type is SQLiteObject instead of a Promise or AsyncInstance (and that right now they're compatible types).

2024-02-12 14:41 UTC, NoelDeMartin commented on src/addons/mod/scorm/services/scorm-offline.ts
> +                        rowIdColumn: null,
I looked into this again, and it seems like there was a bug in the code. The `rowIdColumn` should be `id` by default, but if it's explicitly set to null it shouldn't use the default value and remain unset instead.

This is used to indicate which field should be used as the "row id", which is an sqlite feature that wasn't supported in memory databases before this PR. In sqlite, this happens automatically when a table has a primary key that is a number (and I don't recall which other conditions must apply). But I thought it would be too difficult to also determine that automatically for inmemory databases, so I opted for adding new configuration parameters.

I don't like the fact that this small feature that is only used in a couple of places affects the codebase so much, but I tried to do it using type safety to avoid possible bugs. Though I think I failed on that, because when the parameter is omitted, it is possible to have missmatching types. If he `RowIdColumn` generic is set as `never` (as in the example you mentioned), it only allows passing null as a value for the column. But it doesn't detect that not passing a value would result in using `'id'`, which is not compatible with the type `never`. But I didn't want to complicate the code even further, so I decided to leave it there.

2024-02-12 14:42 UTC, NoelDeMartin commented on src/addons/mod/scorm/services/database/scorm.ts
> +export const ATTEMPTS_TABLE_PRIMARY_KEYS = ['scormid', 'userid', 'attempt'] as const;
It seems I introduced this pattern later on and I didn't apply it everywhere, so I've updated the code to be used more consistently now. The only situations where I'm not using it is if the primary key is a single column, rather than many, because I think it would be overkill to introduce so much indirection for a single column.

2024-02-12 14:45 UTC, NoelDeMartin commented on src/core/services/local-notifications.ts
> +            null,
This is related with the first comment in the review, the reason is that the tables without an argument are defaulting to `id`, whereas in this table the rowIdColumn is set to null.

In this case, this is necessary because even though there is an `id` primary key in this table, it's not an integer so it would be treated as a row id column by sqlite.

2024-02-12 14:46 UTC, NoelDeMartin commented on src/core/features/h5p/classes/framework.ts
>          }
Good catch, it seems like I was too optimistic with my refactor and ended up introducing a bug. I wanted to avoid using the hashes because this required implementing a new operation in tables; which was deleting rows using complex conditions. It seems it's not possible to avoid it, so I ended up implementing `deleteWhere` to achieve it.

2024-02-12 14:48 UTC, NoelDeMartin commented on src/core/features/h5p/classes/framework.ts
> +        const data: Omit<CoreH5PLibraryDBRecord, 'id'> & Partial<Pick<CoreH5PLibraryDBRecord, 'id'>> = {
Great idea, I have created a new helper type called `SubPartial`.

Looking at solutions online, I see that others have called it `PartialBy` or `Optional`, but I wasn't convinced. `PartialBy` doesn't seem so intuitive, and with `Optional` it's not clear that only some keys are made optional (in fact, semantically you could say it means the same as `Partial`.

So I ended up using `SubPartial`, but let me know if you think of a better alternative.

2024-02-12 15:03 UTC, NoelDeMartin commented
Thanks @dpalou for the review, I have updated the code but I didn't rebase so you should be able to look at the diffs of the forced pushes to see everything that changed.

2024-02-13 14:43 UTC, dpalou commented on src/core/features/h5p/classes/framework.ts
> +        const data: Omit<CoreH5PLibraryDBRecord, 'id'> & Partial<Pick<CoreH5PLibraryDBRecord, 'id'>> = {
Sounds good to me!

2024-02-13 14:45 UTC, dpalou approved these changes

2024-02-13 14:47 UTC, dpalou commented
Thanks @NoelDeMartin , the code looks good to me but there is a conflict in a snapshot. I'm happy to integrate it once the conflict is resolved :)

2024-02-14 08:28 UTC, dpalou approved these changes

2024-02-14 08:53 UTC, merged