Mobile 4329
moodlehq/moodleapp pull request #3938
Opened 2024-02-21 11:39 UTC by crazyserver

2024-02-22 13:59 UTC, dpalou requested changes

2024-02-22 13:59 UTC, dpalou commented on src/core/features/siteplugins/classes/handlers/user-handler.ts
> +        CoreUserProfileHandlerType.LIST_ITEM : CoreUserProfileHandlerType.BUTTON;
You should still check TYPE_COMMUNICATION here, otherwise plugins using it will start using LIST_ITEM instead of BUTTON.

2024-02-23 09:44 UTC, crazyserver commented on src/core/features/dataprivacy/services/dataprivacy.ts
> +     * @todo Implement types and pagination.
No need :-) thanks!

2024-02-23 10:22 UTC, crazyserver commented on src/theme/theme.base.scss
> +        td, th, th[aria-current="page"] {
IT was defined this way in grades so I left it as is.

2024-02-27 11:46 UTC, dpalou requested changes

2024-02-27 11:46 UTC, dpalou commented on src/core/features/siteplugins/classes/handlers/user-handler.ts
> +        CoreUserProfileHandlerType.LIST_ITEM : CoreUserProfileHandlerType.BUTTON;
I see you now handle `TYPE_COMMUNICATION` in the `registerHandler` function of the delegate, but that's not enough. If a plugin defines "type" => "communication" in mobile.php, this check will see that it's different than `BUTTON` and will convert it to `LIST_ITEM`. But it should be converted to `BUTTON` instead.

2024-02-27 11:58 UTC, crazyserver commented on src/core/features/siteplugins/classes/handlers/user-handler.ts
> +        CoreUserProfileHandlerType.LIST_ITEM : CoreUserProfileHandlerType.BUTTON;
Done :-)

2024-02-27 12:48 UTC, merged