Mobile 4498
moodlehq/moodleapp pull request #3951
Opened 2024-02-29 14:54 UTC by crazyserver

2024-03-01 10:20 UTC, dpalou requested changes

2024-03-01 10:20 UTC, dpalou commented on src/core/features/courses/services/courses-helper.ts
> +     * This is a temporary function to be used until we move AddonCourseCompletion to core folder.
Did you open an issue in the tracker so we don't forget about this?

2024-03-01 10:20 UTC, dpalou commented on src/addons/blog/blog.module.ts
> +}
Since this code isn't used in compile, maybe we should just remove it like we did for data privacy?

2024-03-04 12:09 UTC, crazyserver commented on src/core/features/courses/services/courses-helper.ts
> +     * This is a temporary function to be used until we move AddonCourseCompletion to core folder.
Done https://tracker.moodle.org/browse/MOBILE-4537

2024-03-04 12:25 UTC, crazyserver commented on src/core/features/tag/services/tag.ts
> +        return !!site && site.canUseAdvancedFeature('usetags') &&
Yep, good catch!

2024-03-04 14:13 UTC, dpalou approved these changes

2024-03-04 14:13 UTC, merged