MOBILE-4329 dataprivacy: Add link handlers
moodlehq/moodleapp pull request #3953
Opened 2024-03-04 11:48 UTC by crazyserver

2024-03-04 14:24 UTC, dpalou requested changes

2024-03-04 14:24 UTC, dpalou commented on src/core/features/dataprivacy/services/handlers/createdatarequest-link.ts
> +        params: Params,
This parameter is wrongly typed (also in some existing link handlers). It should be `Record<string, string>`, not `Params`.

2024-03-04 14:24 UTC, dpalou commented on src/core/features/dataprivacy/services/handlers/createdatarequest-link.ts
> +            createType: params.type,
`params.type` is a string, and I think you want a number here. IMO you should use `Number(params.type)`.

2024-03-04 14:24 UTC, dpalou commented on src/core/features/courses/services/handlers/my-courses-link.ts
> +                    { params: {
The indentation is wrong here, you should put this in two different lines (since you're closing 1 bracket per line.

2024-03-04 14:39 UTC, crazyserver commented
Thanks Dani! Done!

2024-03-04 14:49 UTC, dpalou submitted a review, later dismissed

2024-03-05 07:05 UTC, dpalou approved these changes

2024-03-05 07:05 UTC, merged