MOBILE-4219 blog: Add and edit blog entries
moodlehq/moodleapp pull request #3956
Opened 2024-03-05 14:28 UTC by alfonso-salces

2024-03-12 15:47 UTC, NoelDeMartin commented
@alfonso-salces I rerun the tests just in case, but it seems like this PR has caused a regression in the glossary tests. There are also some merge conflicts you'll have to resolve.

2024-03-14 13:22 UTC, alfonso-salces commented on src/addons/blog/components/entry-options-menu.html
> +            <ion-label color="danger">
This wont work because it will set the background-color as danger too.

2024-03-15 08:58 UTC, alfonso-salces commented on src/addons/blog/pages/edit-entry/edit-entry.ts
> +            this.form.controls.associateWithCourse.patchValue(true);
According to the [official Angular docs](https://angular.io/guide/reactive-forms#updating-parts-of-the-data-model) are slightly different, `patchValue` is quitter unsafe than `setValue` because in complex nested forms `setValue` catch errors and `patchValue` silence them, so maybe in this case it doesn't care so much because we are not using nested controls but maybe we can take into account for other use cases, or directly use always `setValue`.

2024-03-19 16:29 UTC, dpalou requested changes

2024-03-19 16:29 UTC, dpalou commented on src/addons/blog/services/handlers/index-link.ts
> +                await CoreNavigator.navigateToSitePath('/blog/index', { params: pageParams, siteId });
This /index probably isn't needed either because the default root has a redirect, and the same happens in the user handler.

2024-03-19 16:29 UTC, dpalou commented on src/addons/blog/tests/behat/entries.feature
> +    And I press "Display options" in the app
I think this step is flaky because there will be 2 "Display options" in the app, one for each post. You should specify that you want to click the "Display options" of "Blog post one".

2024-03-19 16:29 UTC, dpalou commented on src/core/lang.json
> +    "bynameondate": "By <strong> {{$a.name}} </strong> - {{$a.date}}",
Are the spaces next to the name intended? The ones inside the strong tags. Just to be sure it's not adding some extra spaces.

2024-03-19 16:29 UTC, dpalou commented on src/addons/blog/services/blog.ts
> +        siteId?: string,
The options parameter you defined already accepts a siteId so there's no need to put it in a separate parameter.

2024-03-19 16:29 UTC, dpalou commented on src/addons/blog/services/blog.ts
> +    async isRemovingEnabled(siteId?: string): Promise<boolean> {
This function is no longer used, you can remove it.

2024-03-19 16:29 UTC, dpalou commented on src/addons/blog/pages/index/index.ts
> +            const loading = await CoreDomUtils.showModalLoading();
When using `deleteEntry` I told you to use `showModalLoading` instead of `this.loaded = false`, but this is an event so I think this case is different because the event can be triggered by another page (anything in the app could trigger this event), and then the user would see a modal for something he isn't seeing in the screen.

2024-03-19 16:29 UTC, dpalou commented on src/addons/blog/pages/index/index.ts
> +            this.entries = this.entries.filter(entry => entry.id !== id);
Filtering the entries locally is faster, but if the user leaves the page and opens it again he will see the deleted entry again because the list is cached in the app. You should probably refresh the list in this case too.

2024-03-19 16:29 UTC, dpalou commented on src/addons/blog/pages/index/index.scss
> +        &-visibility-permission {
Is this a valid selector? It's the first time I see using "&" to concatenate something that's not a valid CSS selector. IMO it would be better to put the whole ".entry-visibility-permission" here, it's easier to identify what you're doing. 

And the same applies to other things like "&-draft", "&-subject", etc.

2024-03-20 09:42 UTC, alfonso-salces commented on src/addons/blog/pages/index/index.scss
> +        &-visibility-permission {
We have decided to avoid this change request.

2024-03-20 13:51 UTC, dpalou requested changes

2024-03-20 13:51 UTC, dpalou commented on src/addons/blog/pages/index/index.ts
> +    route = inject(ActivatedRoute);
I think this `route` is no longer used and can be removed.

2024-03-20 14:46 UTC, dpalou approved these changes

2024-03-20 15:13 UTC, merged