Mobile 4544
moodlehq/moodleapp pull request #3976
Opened 2024-03-13 14:20 UTC by crazyserver

2024-03-14 10:21 UTC, dpalou requested changes

2024-03-14 10:21 UTC, dpalou commented on src/core/components/timer/core-timer.html
> +            <div *ngIf="hidable" class="core-timer-visibility">
This rename can be a breaking change for plugins.

2024-03-14 10:21 UTC, dpalou commented on src/addons/mod/quiz/pages/player/player.html
> +        timerHiddenPrefferenceName="quiz_timerhidden" />
```suggestion
        timerHiddenPreferenceName="quiz_timerhidden" />
```

2024-03-15 09:55 UTC, crazyserver commented on src/core/components/timer/core-timer.html
> +            <div *ngIf="hidable" class="core-timer-visibility">
Deprecated ;-)

2024-03-18 07:22 UTC, dpalou approved these changes

2024-03-18 07:36 UTC, merged