MOBILE-4557 blog: Support offline blog
moodlehq/moodleapp pull request #4043
Opened 2024-05-10 11:31 UTC by alfonso-salces

2024-05-14 12:25 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +    protected async syncAllEntriesFunc(force: boolean, siteId: string): Promise<void> {
The function that performs the sync (right now it's this one, but it could be a new function once you apply `getOngoingSync`/`addOngoingSync`) should return `AddonBlogSyncResult`. In this result you should add the warnings I mention in other comments so the page that triggers the manual sync can display them once the sync is done. Also, the "updated" property should be used to determine if the AUTO_SYNC event should be triggered or not.

2024-07-24 09:44 UTC, dpalou requested changes

2024-07-24 13:19 UTC, alfonso-salces commented on src/addons/blog/pages/index/index.html
> +    @if ((filter.userid === currentUserId || showMyEntriesToggle) && loaded() && optionsAvailable) {
This is done because showMyEntriesToggle already checks filter.userid

2024-08-01 14:07 UTC, dpalou commented on src/addons/blog/pages/edit-entry/edit-entry.ts
> +                value: typeof params.attachmentsId === 'number' ? params.attachmentsId : JSON.stringify(params.attachmentsId),
The whole `options` array is stored as a JSON string in database, so there's no need to convert the attachmentsid to a JSON string here. You can leave it as an object and it will be converted along with the rest of options.

2024-08-01 14:17 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +                    await this.syncUpdatedEntry({ ...entry, id: entry.id, options: JSON.parse(entry.options) });
You aren't passing the siteId to `syncUpdatedEntry` or `uploadAttachments`. Please remember to always pass the siteId, otherwise things will go wrong when synchronizing data from a site that isn't the current one.

2024-08-01 14:20 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +            }
Even if there are no offline files to upload, when editing an existing entry the user could have deleted attachments so there could be files to delete.

2024-08-01 14:26 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +            const filesToDelete = CoreFileUploader.getFilesToDelete(attachments.online, offlineFiles);
You fixed part of the function, but broke the part that was ok xD

`attachments.online` contains the "online" attachments that the user left when saving, but that's not the list of "original" attachments because the user could have deleted some files. You need to retrieve the original attachments using `AddonBlog.getEntries` like you did before, the code would be something like this (please notice it's pseudo code):

```
const onlineEntry = AddonBlog.getEntries(...);

const filesToDelete = CoreFileUploader.getFilesToDelete(onlineEntry.attachmentfiles, attachments.online);
```

2024-08-01 14:29 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +        }
I think this `catch` isn't needed, isn't it? It's just ignoring some errors that I think we shouldn't ignore. The calls to `uploadAttachments` are already inside another try/catch so the errors will be handled in there.

2024-08-01 14:35 UTC, dpalou commented on src/addons/blog/services/blog-offline.ts
> +    async deleteOfflineEntryRecord(created: number, siteId?: string): Promise<void> {
I think deleting entries by `created` isn't the best, because `created` might not be unique in the server. In a Moodle site there could be 2 entries with the same created time, you should only use created when you don't have an id.

2024-08-01 14:37 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +                    await this.syncUpdatedEntry({ ...entry, id: entry.id, options: JSON.parse(entry.options) });
```suggestion
                    await this.syncUpdatedEntry({ ...entry, id: entry.id, options: formattedEntry.options });
```
You already parsed the options so you can reuse them instead of parsing them again, right?

2024-08-01 14:41 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +                this.addOfflineDataDeletedWarning(warnings, entry.summary, error);
```suggestion
                this.addOfflineDataDeletedWarning(warnings, entry.subject, error);
```
I think it's better to use subject, right? Summary is the whole post contents, it can be too long.

2024-08-01 14:43 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +                return { updated: false, warnings };
You're not sending data to server but you're "discarding" data, so the data displayed to the user was updated. You should return updated=true in this case.

2024-08-01 14:46 UTC, dpalou commented on src/addons/blog/services/blog.ts
> +            if (error && !CoreUtils.isWebServiceError(error)) {
```suggestion
            if (!CoreUtils.isWebServiceError(error)) {
```
I think there's no need to check if `error` is set, `isWebServiceError` is already checking it. And if `error` is empty we should probably consider it is as a local error, which `isWebServiceError` already does.

The same happens in the `updateEntry` and `deleteEntry` functions.

2024-08-01 14:49 UTC, dpalou commented on src/addons/blog/services/blog.ts
> +            }
IMO the code to set the id to a negative number should be all inside blog-offline. In a previous comment I mentioned that we can probably remove the `updateEntryOffline` function, and the function `addOfflineEntry` already handles it correctly inside the function.

2024-08-01 14:54 UTC, dpalou commented on src/addons/blog/services/blog.ts
> +            }
```suggestion
            await CoreUtils.ignoreErrors(AddonBlogOffline.unmarkEntryAsRemoved(params.entryid));
```
Instead of reading and writing, you can just write and ignore the errors. And the `ignoreErrors` can probably be removed too because you delete using a WHERE, so it won't throw an error if no entries are found, but you can leave it just in case.

2024-08-01 14:58 UTC, dpalou commented on src/addons/blog/services/blog.ts
> +        const attachmentfiles = [...optionsFiles.online, ...offlineFiles];
```suggestion
        const moduleId = options?.find(option => option.name === 'modassoc')?.value as number | undefined;
        const courseId = options?.find(option => option.name === 'courseassoc')?.value as number | undefined;
        const tags = options?.find(option => option.name === 'tags')?.value as string | undefined;
        const publishState = options?.find(option => option.name === 'publishstate')?.value as AddonBlogPublishState
            ?? AddonBlogPublishState.draft;
        const user = await CoreUser.getProfile(offlineEntry.userid);
        const offlineFiles = await AddonBlogOffline.getOfflineFiles(offlineEntry.id ?? offlineEntry.created);
        const optionsFiles = this.getAttachmentFilesFromOptions(options);
        const attachmentFiles = [...optionsFiles.online, ...offlineFiles];
```
Our variables should use camelCase, unless when we're using destructuring and the name comes from a WebService response.

2024-08-14 09:01 UTC, dpalou requested changes

2024-08-14 09:01 UTC, dpalou commented on src/addons/blog/services/blog.ts
> +export type AddonBlogUpdateEntryWSParams = AddonBlogAddEntryWSParams & ({ entryid: number } | { created?: number });
`created` is not a valid parameter of the WebService. The WSParams type should reflect what the WebService expects, the other parameters used by the app should be in a different type (e.g. you can just put it in the function declaration like you do with `attachments` and `forceOffline`:

`{ attachments?: string; forceOffline?: boolean }`

2024-08-19 10:26 UTC, dpalou requested changes

2024-08-19 10:26 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +                await AddonBlogOffline.deleteOfflineEntryRecord(entry.id ? { id: entry.id } : { created: entry.created });
```suggestion
                await AddonBlogOffline.deleteOfflineEntryRecord(entry.id ? { id: entry.id } : { created: entry.created }, siteId);
```

2024-08-19 10:26 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +        await AddonBlogOffline.deleteOfflineEntryRecord({ id });
```suggestion
        await AddonBlogOffline.deleteOfflineEntryRecord({ id }, siteId);
```

2024-08-19 10:26 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +        const offlineFiles = await AddonBlogOffline.getOfflineFiles(folder);
```suggestion
        const offlineFiles = await AddonBlogOffline.getOfflineFiles(folder, site.id);
```

2024-08-19 10:26 UTC, dpalou commented on src/addons/blog/services/blog-offline.ts
> +            const folderPath = await AddonBlogOffline.getOfflineEntryFilesFolderPath(folderName);
```suggestion
    async getOfflineFiles(folderName: AddonBlogOfflineParams, siteId?: string): Promise<CoreFileEntry[]> {
        try {
            const folderPath = await AddonBlogOffline.getOfflineEntryFilesFolderPath(folderName, siteId);
```

2024-08-19 10:26 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +            { readingStrategy: CoreSitesReadingStrategy.PREFER_NETWORK },
```suggestion
            { readingStrategy: CoreSitesReadingStrategy.PREFER_NETWORK, siteId: site.id },
```

2024-08-19 10:26 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +        const entriesToBeRemoved = await AddonBlogOffline.getEntriesToRemove();
```suggestion
        const entriesToBeRemoved = await AddonBlogOffline.getEntriesToRemove(siteId);
```

2024-08-19 10:26 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +                await AddonBlog.deleteEntryOnline({ entryid: entry.id });
```suggestion
                await AddonBlog.deleteEntryOnline({ entryid: entry.id }, siteId);
```

2024-08-19 10:26 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +                    await AddonBlogOffline.deleteOfflineEntryRecord({ id: entry.id });
```suggestion
                    await AddonBlogOffline.deleteOfflineEntryRecord({ id: entry.id }, siteId);
```

2024-08-19 10:26 UTC, dpalou commented on src/addons/blog/services/blog-sync.ts
> +                await AddonBlogOffline.unmarkEntryAsRemoved(entry.id);
```suggestion
                await AddonBlogOffline.unmarkEntryAsRemoved(entry.id, siteId);
```

2024-08-19 12:00 UTC, dpalou approved these changes

2024-08-19 12:02 UTC, merged