Mobile 4594
moodlehq/moodleapp pull request #4108
Opened 2024-07-03 15:08 UTC by crazyserver

2024-07-16 06:50 UTC, dpalou requested changes

2024-07-16 06:50 UTC, dpalou commented on src/core/features/compile/services/compile.ts
> -        instance['Network'] = CoreNetwork.instance; // @deprecated since 4.1, plugins should use CoreNetwork instead.
I've detected that Network is used in a couple of plugins (choicegroup and forumng). I'll open a PR to fix it, but we decided to keep it in the code for now so plugins have time to integrate it and release it, and admins can update the plugin. Please add a comment explaining why we decided to leave the code for now.

2024-07-16 06:50 UTC, dpalou commented on src/core/services/app.ts
> -    }
I've detected that isOnline is used in a couple of plugins (choicegroup and forumng). I'll open a PR to fix it, but we decided to keep it in the code for now so plugins have time to integrate it and release it, and admins can update the plugin. Please add a comment explaining why we decided to leave the code for now.

2024-07-16 06:50 UTC, dpalou commented on src/addons/mod/bigbluebuttonbn/tests/behat/basic_usage.feature
> +    And I wait "3" seconds
I don't like these "waits", but I wasn't able to reproduce the issue in a local environment so it's hard to debug this. Since I don't want to block the integration of this just because of this problem, can you please add a TODO comment to review this later?

2024-07-16 06:58 UTC, crazyserver commented on browserslist
> +iOS >=15
Those settings come from Ionic8 requirements https://ionicframework.com/docs/reference/browser-support

2024-07-16 07:03 UTC, crazyserver commented on src/core/features/compile/services/compile.ts
> -        instance['Network'] = CoreNetwork.instance; // @deprecated since 4.1, plugins should use CoreNetwork instead.
Thanks :-)

2024-07-18 08:35 UTC, dpalou approved these changes

2024-07-18 08:35 UTC, merged