MOBILE-4630 pluginfile: Add lang to file download request
moodlehq/moodleapp pull request #4124
Opened 2024-07-22 07:01 UTC by alfonso-salces

2024-07-22 09:28 UTC, dpalou requested changes

2024-07-22 09:28 UTC, dpalou commented on src/core/services/utils/url.ts
> +        return this.addParamsToUrl(url, { offline: '1', lang: Translate.currentLang });
The app uses "-" for child languages (e.g. en-us), while Moodle uses "_" (e.g. en_us). So I guess this won't work fine for child languages.

Also, we usually prefer using our `CoreLang` service instead of using `Translate` directly. The problem is that our `getCurrentLanguage` function is async. Maybe we could create a new function that is synchronous, something like `getCurrentLanguageInstant` or `getCurrentLanguageSync`, and this function wouldn't have the code to detect the current language (this means it can return undefined). Also, this function also converts the format to Moodle format if you indicate it using the parameter, so the problem with "_" and "-" would be easily fixed.

2024-07-22 09:28 UTC, dpalou commented on src/core/services/utils/url.ts
> +        return this.addParamsToUrl(url, { offline: '1', lang: Translate.currentLang });
One thing to take into account is that, if the user changes the language of the app, the downloaded files will still have the old language. One possible solution is to "invalidate" all files when the app language changes, but that means all the files will be re-downloaded when probably most files won't have multi lang. We should probably discuss this internally with Juan to decide what we want to do.

2024-07-22 11:52 UTC, alfonso-salces commented on src/core/services/utils/url.ts
> +        return this.addParamsToUrl(url, { offline: '1', lang: Translate.currentLang });
As we dicussed internally with Juan, this is expected and does not require to take care of that right now.

2024-07-23 08:02 UTC, dpalou approved these changes

2024-07-23 08:02 UTC, merged