Mobile 4616
moodlehq/moodleapp pull request #4127
Opened 2024-07-22 15:25 UTC by crazyserver

2024-07-23 10:03 UTC, dpalou requested changes

2024-07-23 10:03 UTC, dpalou commented on src/core/classes/sites/authenticated-site.ts
> +            let lang = await CoreLang.getCurrentLanguage(CoreLangFormat.LMS);
Now that we have a synchronous function to get the current language maybe we should use it instead? This function should always be called after the app has been initialized.

Btw, I think this function isn't used in our public code (I haven't checked our private code).

2024-07-23 13:10 UTC, crazyserver commented on src/core/classes/sites/authenticated-site.ts
> +            let lang = await CoreLang.getCurrentLanguage(CoreLangFormat.LMS);
No it's isn't used.... Do you want me to remove it? It generates some circular deps, and that's why I moved it, but I can directly warn the user it will be removed

2024-07-23 13:10 UTC, crazyserver commented on src/core/singletons/url.ts
> +    }
:-)

2024-07-25 09:24 UTC, dpalou requested changes

2024-07-25 09:24 UTC, dpalou commented on src/core/singletons/url.ts
> +            scheme: match[2] || undefined,
As we discussed, I think it's better to only treat protocol here. Also in assemble function.

2024-07-25 09:24 UTC, dpalou commented on src/core/singletons/url.ts
> +    Scheme = 'scheme',
As we discussed, I guess it's better to name this part "protocol" instead of scheme.

2024-07-25 09:24 UTC, dpalou commented on src/core/singletons/url.ts
> +    }
If we don't differentiate between protocol and scheme in `parse`, the behaviour of this function will change. Before, it only captured protocols followed by "://", now it will also capture "javascript:", "mailto:", etc. Maybe it's ok like this, but we need to be careful this change doesn't break anything.

If we force that `parse` only captures protocols with "://", then it will break the function `isLocalFileUrl`.

If this becomes too problematic maybe we can stop using parse in some of these functions for now.

2024-07-25 09:24 UTC, dpalou commented on src/core/singletons/url.ts
> +    }
As we discussed, maybe this code should be moved somewhere else, like CoreCustomURLSchemes because a string with a URL scheme might not be a valid URL.

2024-07-25 09:24 UTC, dpalou commented on src/core/singletons/url.ts
> +        }
This function can use `parse` too, right?

2024-07-25 09:24 UTC, dpalou commented on src/core/singletons/url.ts
> +    static removeUrlParts(url: string, parts: CoreUrlPartNames[]): string {
A tiny improvement for this function would be to accept a single part as a param too:

`parts: CoreUrlPartNames | CoreUrlPartNames[]`

That way you can do things like `removeUrlParts(url, CoreUrlPartNames.Scheme)` without having to pass an array. But it's a tiny improvement, feel free to leave it like this if you prefer.

2024-07-25 09:24 UTC, dpalou commented on src/core/singletons/url.ts
> +                    url = url.replace(/^www./, '');
Sine this RegExp uses "^", the order of the part names is important. E.g. if I do:

[CoreUrlPartNames.WWWInDomain, CoreUrlPartNames.Scheme]

It won't work properly, because first it will look for www but it won't be found at the beginning because the URL still has the protocol. And it won't work either if the user only wants to remove "www". We should probably modify the regexp to search it after the protocol too.

2024-07-25 10:17 UTC, dpalou approved these changes

2024-07-25 13:22 UTC, dpalou submitted a review, later dismissed

2024-07-25 13:52 UTC, dpalou approved these changes

2024-07-25 13:52 UTC, merged