MOBILE-4631: Hide the login form in the app when is hidden in LMS
moodlehq/moodleapp pull request #4141
Opened 2024-08-05 09:19 UTC by albertgasset

2024-08-05 12:41 UTC, dpalou requested changes
The format of commit names is "ISSUE component: Description". Your commit lacks a component, e.g. "login".

2024-08-05 12:41 UTC, dpalou commented on src/core/classes/sites/unauthenticated-site.ts
> +    showloginform?: number; // Display default login form.
```suggestion
    showloginform?: number; // @since 4.5.Display default login form. 
```

We usually indicate the LMS version where this value was introduced.

2024-08-05 12:41 UTC, dpalou commented on src/core/features/login/pages/credentials/credentials.ts
> +        this.alwaysShowLoginFormObserver = CoreEvents.on<number>(ALWAYS_SHOW_LOGIN_FORM_CHANGED, async () => {
```suggestion
        this.alwaysShowLoginFormObserver = CoreEvents.on(ALWAYS_SHOW_LOGIN_FORM_CHANGED, async () => {
```

To define the parameters of an event we do it differently so it's detected automatically without having to specify the type in every listener. You should add the type in here:

https://github.com/moodlehq/moodleapp/blob/main/src/core/features/login/services/login-helper.ts#L1695

In this code we're basically adding new values to the `CoreEventsData` interface that is used by `CoreEvents`. The keys of the object are the names of the events, and the value is the type of the parameter passed to the event. If you add your event in here, all the listeners will automatically infer the type without having to specify it manually. So you can remove the `<number>` type from here and from reconnect page.

PD: Please notice the type of the parameter you're passing is `{ value: number }`, not just `number`.

2024-08-05 13:48 UTC, albertgasset commented
Thanks @dpalou  for the review, I've updated the branch with the changes.

2024-08-06 05:54 UTC, dpalou approved these changes

2024-08-06 05:55 UTC, merged