Mobile 4442
moodlehq/moodleapp pull request #4180
Opened 2024-09-17 12:41 UTC by crazyserver

2024-09-18 13:44 UTC, dpalou requested changes

2024-09-18 13:44 UTC, dpalou commented on src/core/features/course/components/course-format/course-format.ts
> +            const subSection = this.subSections.find((section) => section.id === this.initialSectionId);
Shouldn't you also check `initialSectionNumber`? Or subsection don't have a number?

2024-09-18 13:44 UTC, dpalou commented on src/core/features/course/components/course-section/course-section.html
> +</div>
Most of this HTML is the same as above, I think the only differences are:

slot="header"
<div slot="content">
<ng-container *ngIf="section.expanded">

IMO it would be better to move all the common code to ng-templates to reuse it. And that way it's easier to view that the content is the same in both cases.

2024-09-18 13:44 UTC, dpalou commented on src/core/features/course/components/course-section/course-section.ts
> +    @Input() sections: CoreCourseSectionToDisplay[] = []; // List of sections in the course.
This comment says "List of sections in the course.". But then you either pass a list of subsections, or nothing at all. This is confusing.

2024-09-18 13:44 UTC, dpalou commented on src/core/features/course/services/course.ts
> +    itemid?: number; // @since 4.5 The optional item id delegate component can use to identify its instance.
I put the comment here, but it's not related to this line of code. This commit has a submessage that only contains "a".

2024-09-18 13:44 UTC, dpalou commented on src/core/features/course/components/course-index/course-index.ts
> +                }
If the subsection isn't found for some reason, shouldn't you also "return"? Otherwise you'll try to get the completion status when you shouldn't.

2024-09-18 13:44 UTC, dpalou commented on src/core/features/course/components/course-index/course-index.ts
> +    accordionMultipleChange(ev: AccordionGroupChangeEventDetail): void {
Is this function used? You aren't using ion-accordion in course-index.

2024-09-18 13:44 UTC, dpalou commented on src/core/features/course/components/course-format/course-format.ts
> +            this.setSectionExpanded(section);
If the user has selected a subsection but not a module, shouldn't we scroll to the subsection? Otherwise the user might not see it.

2024-09-18 14:01 UTC, crazyserver commented on src/core/features/course/components/course-index/course-index.ts
> +    accordionMultipleChange(ev: AccordionGroupChangeEventDetail): void {
True, I tried to add accordion on course index but I had a limitation when clicking on the icon to expand collapse (i took the ion-item action instead). Now it has been removed.

2024-09-19 08:33 UTC, crazyserver commented on src/core/features/course/components/course-format/course-format.ts
> +            const subSection = this.subSections.find((section) => section.id === this.initialSectionId);
True! thx!

2024-09-19 08:35 UTC, crazyserver commented on src/core/features/course/components/course-section/course-section.ts
> +    @Input() sections: CoreCourseSectionToDisplay[] = []; // List of sections in the course.
changed!

2024-09-19 08:44 UTC, crazyserver commented on src/core/features/course/components/course-index/course-index.ts
> +                }
I'd return but without the subsection. thx

2024-09-19 09:56 UTC, dpalou requested changes

2024-09-19 09:56 UTC, dpalou commented on src/addons/mod/subsection/services/handlers/index-link.ts
> +    ): CoreContentLinksAction[] | Promise<CoreContentLinksAction[]> {        return [{
Wrong indentation (the return).

2024-09-19 09:56 UTC, dpalou commented on src/addons/mod/subsection/services/subsection.ts
> +};
I think this type isn't used.

2024-09-19 09:56 UTC, dpalou commented on src/core/features/course/components/course-format/course-format.ts
> +     * @param isSubsection Whether the module is inside a subsection.
IMO this JSDoc/parameter names is wrong.

The first line says "or section", but the parameter is called "isSubsection". The code actually allows scrolling to a section, so I guess the parameter should be named "isSection".

Also, the JSDoc of the parameter says "Whether the module is inside a subsection.", but it's actually used is to determine if the ID is a section or a module.

2024-09-19 09:56 UTC, dpalou commented on src/core/features/course/components/course-index/course-index.scss
> +div.core-course-index-subsection{
```suggestion
div.core-course-index-subsection {
```

2024-09-19 09:56 UTC, dpalou commented on src/core/features/course/components/course-section/course-section.ts
> +    subsection?: CoreCourseSectionToDisplay;
In course index, you name the module property "subSection", but here you name it "subsection" in lowercase. IMO we should be consistent.

I was concerned that this could cause problems if we used the same "module" object in both places. But I see that in course index we create a copy of the module, so as far as JS is concerned I think it should be ok. Maybe TS complains because the types don't match and you need to do an `Omit` in course index.

2024-09-19 10:32 UTC, crazyserver commented on src/core/features/course/components/course-section/course-section.ts
> +    subsection?: CoreCourseSectionToDisplay;
OK, done, thanks. About your concern, TS is not complaining so I left it like it is now

2024-09-19 10:42 UTC, dpalou submitted a review, later dismissed

2024-09-19 13:57 UTC, dpalou approved these changes

2024-09-19 13:57 UTC, merged