MOBILE-4639 badges: Support links to badges/badgeclass.php?id=X
moodlehq/moodleapp pull request #4181
Opened 2024-09-17 15:01 UTC by albertgasset

2024-09-18 11:09 UTC, dpalou requested changes

2024-09-18 11:09 UTC, dpalou commented on src/addons/badges/pages/badge-class/badge-class.ts
> +        this.badgeId = parseInt(CoreNavigator.getRouteParam('badgeId') ?? '');
Can't you use `CoreNavigator.getRouteNumberParam` instead? It automatically converts to number. If the parameter is undefined, it will return undefined.

2024-09-18 11:09 UTC, dpalou commented on src/addons/badges/pages/badge-class/badge-class.ts
> +        await CoreUtils.ignoreErrors(this.fetchBadgeClass());
This `ignoreErrors` isn't needed because `fetchBadgeClass` already captures errors. It doesn't hurt, so if you prefer leaving it it's ok for me.

2024-09-19 07:57 UTC, albertgasset commented on src/addons/badges/pages/badge-class/badge-class.ts
> +        this.badgeId = parseInt(CoreNavigator.getRouteParam('badgeId') ?? '');
I've change it to `CoreNavigator..getRequiredRouteNumberParam`

2024-09-19 07:57 UTC, albertgasset commented on src/addons/badges/pages/badge-class/badge-class.ts
> +        await CoreUtils.ignoreErrors(this.fetchBadgeClass());
I've remove it

2024-09-19 08:16 UTC, dpalou approved these changes

2024-09-19 08:22 UTC, merged