MOBILE-3893 assign: Add button to remove submissions
moodlehq/moodleapp pull request #4191
Opened 2024-09-27 15:05 UTC by albertgasset

2024-09-30 10:33 UTC, dpalou requested changes

2024-09-30 10:33 UTC, dpalou commented on src/addons/mod/assign/components/submission/addon-mod-assign-submission.html
> +                                            userSubmission!.status === statusNew)">
This button lets you add a new submission when you have removed the previous one in offline. I tried it because I'm not sure if the sync process will be ok in that case, and I found that clicking the "Add submission" button throws a connection error, probably because we don't have cached the required data to add a new submission, only to edit the current one.

Basically what I did is:

- Open an assignment that already had a submission.
- Open the "i" menu and click Download.
- Go offline and click "Remove submission".
- Click "Add submission" when I'm still offline. I get a connection error.

If we can handle this case and make the "Add submission" button work in offline, we need to be careful because adding a new offline submission might override the info stored in the device DB (the one that indicates that the previous submission was deleted), and that can cause problems when synchronizing the info.

I guess it would be simpler to not allow adding a new submission if you have deleted the previous one in offline and you haven't synchronized, but the UX is worse for the user.

2024-10-02 13:46 UTC, albertgasset commented on src/addons/mod/assign/components/submission/addon-mod-assign-submission.html
> +                                    <div *ngIf="editedOffline" class="list-item-limited-width adaptable-buttons-row">
It is not needed, I've remove it.

2024-10-02 13:46 UTC, albertgasset commented on src/addons/mod/assign/components/submission/addon-mod-assign-submission.html
> +                                        class="list-item-limited-width adaptable-buttons-row">
I've remove it.

2024-10-02 13:46 UTC, albertgasset commented on src/addons/mod/assign/services/assign-helper.ts
> +    }
I've removed the function.

2024-10-02 13:48 UTC, albertgasset commented on src/addons/mod/assign/services/assign.ts
> +        const warnings = await site.write<CoreWSExternalWarning[]>('mod_assign_remove_submission', params);
Fixed.

2024-10-02 13:48 UTC, albertgasset commented on src/addons/mod/assign/services/assign.ts
> +    async removeSubmission(
We can detect this case: when the cached online submission has status "new" or "reopened".  Now the offline submission is deleted in this case, so nothing will be syncrhonized.

2024-10-02 14:09 UTC, albertgasset commented on src/addons/mod/assign/services/assign.ts
> +    async removeSubmissionOnlie(assignId: number, userId?: number, siteId?: string): Promise<void> {
Fixed.

2024-10-04 06:34 UTC, dpalou requested changes

2024-10-04 06:34 UTC, dpalou commented on src/addons/mod/assign/services/assign.ts
> +                // The submission was created offline and not synced, just delete the offline submission.
Thanks Albert, this works better now, but the following can still happen (it's a less common use case though):

- I add a new submission in offline.
- I go online and, before the app synchronizes, I click the Remove submission button.

In this case the device is online, so this check isn't be performed. The app discards the offline submission, and then it calls `this.removeSubmissionOnline`, which throws an error because the submission isn't found. I guess you shouldn't call `this.removeSubmissionOnline` either if it's a new/reopened submission.

2024-10-04 11:38 UTC, albertgasset commented on src/addons/mod/assign/services/assign.ts
> +                // The submission was created offline and not synced, just delete the offline submission.
I've fixed it and added this case to the Behat test.

2024-10-04 13:32 UTC, dpalou approved these changes

2024-10-04 13:32 UTC, merged