Mobile 4660
moodlehq/moodleapp pull request #4193
Opened 2024-10-01 10:41 UTC by crazyserver

2024-10-01 13:47 UTC, dpalou requested changes
Taking into account all the problems we're facing here, maybe it would have been better to take a different approach: when we receive the data from WS, we could modify the data to replace all the mod_subection activities with their section, and remove the subsection from the list of sections. That way in section contents we would have modules and sections, and all the app would receive this new structure (there would be no need to filter the list of sections in the page, or calculate module.subsection and so on). For the app, mod_subsection wouldn't exist, only the function converting the WS data would know that there is an activity called mod_subsection.

I guess it's too late now to try this approach, and maybe it causes other problems, so for now I guess it's better to keep your approach.

2024-10-01 13:47 UTC, dpalou commented on src/addons/storagemanager/pages/course-storage/course-storage.ts
> +                    this.prefetchSection(sectionFinder.section);
When `data.sectionId` is a subsection, you're checking if the parent section is downloading (`section.isDownloading`) but in `isBeingDownloaded` you pass `downloadId` (which is calculated using data.sectionId, the subsection id). So in one condition you use the section and in the other you use the subsection. This seems wrong.

I'm not sure if in this case you should check the subsection, the parent section or both. But right now the check doesn't seem consistent.

2024-10-01 13:47 UTC, dpalou commented on src/addons/storagemanager/pages/course-storage/course-storage.ts
> +            const status = CoreCourseModulePrefetchDelegate.determineModuleStatus(moduleFound, data.status);
Should we call this function for mod_subsection modules? They don't have a status, it's always not downloaded because their prefetch handler doesn't store a status (and it's ok that it doesn't store it, because the status is calculated dynamically in this page).

2024-10-01 13:47 UTC, dpalou commented on src/core/features/course/components/course-format/course-format.ts
>          if (expandedSections === undefined) {
This empty array line can be moved to the existing if:

```suggestion
        // Expand all sections if not defined.
        if (expandedSections === undefined) {
            this.accordionMultipleValue = [];
```

2024-10-01 13:47 UTC, dpalou commented on src/addons/storagemanager/pages/course-storage/course-storage.ts
>              await CoreCourseHelper.confirmDownloadSizeSection(this.courseId, section, this.sections);
While testing this I noticed that this function calls `CoreCourseModulePrefetchDelegate.getDownloadSize` passing `section.modules`, and `section.modules` can include a mod_subsection. But subsection don't have a download size, they return -1 (cannot calculate), so for those sections it will always say that the size couldn't be calculated.

2024-10-02 09:45 UTC, crazyserver commented on src/addons/storagemanager/pages/course-storage/course-storage.ts
> +            const status = CoreCourseModulePrefetchDelegate.determineModuleStatus(moduleFound, data.status);
I've change the conditions to find it.

2024-10-07 09:27 UTC, dpalou commented
Closing this PR in favor of https://github.com/moodlehq/moodleapp/pull/4194, which includes these commits along with others.

2024-10-07 09:27 UTC, closed without merging