Mobile 4653
moodlehq/moodleapp pull request #4232
Opened 2024-11-11 13:59 UTC by crazyserver

2024-11-14 09:49 UTC, dpalou requested changes

2024-11-14 09:49 UTC, dpalou commented on src/core/singletons/utils.ts
> +    }
I looked where this function is used and I think it can be replaced by "??". So maybe we can deprecate this function in the Utils provider and don't include it here.

2024-11-14 09:49 UTC, dpalou commented on src/core/features/compile/services/compile.ts
>          instance['CoreArray'] = CoreArray;
CoreArray is duplicated and some singletons like CoreBrowser or CoreMedia are missing. I'm not sure if all singletons should be exported to plugins, e.g. in CoreRedirects the only function that IMO could be interesting for plugins is "checkRedirect", and it seems very specific so maybe we don't need to export it.

2024-11-14 11:28 UTC, crazyserver commented on src/core/features/siteplugins/services/siteplugins-init.ts
> +export class CoreSitePluginsInit {
OK then, reverted

2024-11-15 10:13 UTC, crazyserver commented on src/addons/calendar/services/calendar-sync.ts
>  export type AddonCalendarSyncEvents = CoreSyncResult & {
I've removed types.ts since I think it's not necessary now to do that.

2024-11-15 10:34 UTC, crazyserver commented on src/core/features/course/pages/index/index.ts
> +        this.progressObserver = CoreEvents.on(COURSE_PROGRESS_UPDATED_EVENT, (data) => {
We've talked to maintain _EVENT at the end

2024-11-15 10:34 UTC, crazyserver commented on src/addons/calendar/constants.ts
> +export const ADDON_CALENDAR_FILTER_CHANGED_EVENT = 'addon_calendar_filter_changed_event';
We've talked to maintain _EVENT at the end

2024-11-15 11:27 UTC, crazyserver commented on src/core/services/app-db.ts
> +export class CoreAppDBService {
Yep it reduces quite a lot

2024-11-15 11:30 UTC, crazyserver commented on src/core/services/app-db.ts
> +        this.schemaVersionsTable.setLazyConstructor(async () => {
I agree here

2024-11-15 11:56 UTC, crazyserver commented on src/core/singletons/iab.ts
> +    static closeInAppBrowser(): void {
Done :-)

2024-11-18 13:16 UTC, dpalou submitted a review, later dismissed

2024-11-18 13:46 UTC, merged