MOBILE-4676: Use core strings
moodlehq/moodleapp pull request #4243
Opened 2024-11-20 10:45 UTC by jleyva

2024-11-25 11:55 UTC, crazyserver requested changes

2024-11-25 11:55 UTC, crazyserver commented on scripts/langindex.json
> +  "addon.messages.type_offline": "message",
type_offline does not exist, use 'message/offline' instead.

2024-11-25 11:55 UTC, crazyserver commented on scripts/langindex.json
> +  "addon.messages.type_online": "message",
type_online does not exist, use 'message/online' instead.

2024-11-25 11:58 UTC, crazyserver commented
Additional to that, please change strings on lang.json from
addon.block_myoverview.nocoursesenrolled to 'You are currently not enrolled in any courses.'
addon.mod_glossary.searchquery to 'Enter your search query'
addon.messages.type_blocked to 'Blocked users'

I think the other ones do not change

2024-11-26 09:52 UTC, jleyva commented
> i

@crazyserver I just applied the requested changes

2024-11-26 11:42 UTC, crazyserver commented
Closed in favour of https://github.com/moodlehq/moodleapp/pull/4248

2024-11-26 11:42 UTC, closed without merging