MOBILE-4653 core: Add site logo component
moodlehq/moodleapp pull request #4252
Opened 2024-12-04 13:28 UTC by crazyserver

2024-12-09 08:05 UTC, dpalou requested changes

2024-12-09 08:05 UTC, dpalou commented on src/core/features/mainmenu/components/user-menu/user-menu.html
> +                    <core-site-logo [hideOnError]="true" fallbackLogo="assets/img/login_logo.png" />
I think that using the new component in user-menu has changed the behaviour. Before this change, the user-menu called `getPublicConfig` (if needed) to fetch the logo, but the `core-site-logo` component doesn't do that.

AFAIK when you login in a site we don't set the public config, we only call `getPublicConfig` in the places that we need it, so it's possible that the site instance doesn't have this info (and so the logo won't be displayed).

2024-12-09 09:24 UTC, crazyserver commented on src/core/features/courses/pages/my/my.html
> -                <img src="assets/img/top_logo.png" class="core-header-logo" [alt]="siteName">
The visibility of the logo is controlled by CSS. So it shows the logo or the title and this is still the same.

2024-12-09 12:55 UTC, dpalou commented on src/core/components/site-logo/site-logo.ts
> +        this.siteId = CoreSites.getCurrentSiteId();
If you receive a `site` instance via input then you should use its ID (if it has an ID). In credentials we won't have an ID, but in reconnect we will.

2024-12-09 12:55 UTC, dpalou commented on src/core/components/site-logo/site-logo.html
> +    <img *ngIf="siteLogo" [src]="siteLogo" class="core-logo" [alt]="siteName" core-external-content (error)="imageError()">
You're passing the siteId to format-text, but not to this core-external-content.

2024-12-09 12:55 UTC, dpalou commented on src/core/components/site-logo/site-logo.html
> +    <core-format-text [text]="siteName" [filter]="false" contextLevel="system" [contextInstanceId]="0" [siteId]="siteId" />
In some cases you're using [filter]="false", but in others you don't. I guess this is because of copy paste. Since we cannot know where will this component be used IMO we should remove this filter=false (and maybe we should improve the format-text directive to avoid calling the filter functions if there is no site ID?

2024-12-09 12:55 UTC, dpalou commented on src/core/features/courses/pages/my/my.html
> -                <img src="assets/img/top_logo.png" class="core-header-logo" [alt]="siteName">
I don't agree that the behaviour is the same now :P But as we talked in chat we'll support using an online URL for top logo too, so it's ok like this.

2024-12-10 08:40 UTC, dpalou approved these changes

2024-12-10 08:56 UTC, merged