Mobile 3063
moodlehq/moodleapp pull request #4266
Opened 2024-12-16 13:11 UTC by crazyserver

2024-12-17 08:10 UTC, dpalou requested changes

2024-12-17 08:10 UTC, dpalou commented on src/core/features/viewer/services/viewer.ts
> +        document.body.classList.toggle('core-reading-mode-multimedia-hidden', !settings.showMultimedia);
If I'm not mistaken, when exiting the reading mode you're leaving all this CSS in the DOM. Shouldn't you remove it too? I know it's not applied because other classes are removed, but maybe we should clean it up too.

2024-12-17 08:10 UTC, dpalou commented on src/core/singletons/dom.ts
> +    static removeAllStyles(text: string | undefined): string {
I think this function isn't used, I'm not sure if you want to keep it or not.

2024-12-17 09:29 UTC, crazyserver commented on src/core/directives/reading-mode.ts
> +        this.contentEl?.classList.add('core-reading-mode-content');
Yep, this is something we can do only once, so I moved it to addTextViewerButton instead

2024-12-17 09:32 UTC, crazyserver commented on scripts/langindex.json
> +  "core.viewer.readingthemelight": "local_moodlemobileapp/core.settings.colorscheme-light",
Not to duplicate the string that is yet in local_moodlemobileapp

2024-12-17 10:03 UTC, crazyserver commented on src/core/features/viewer/services/viewer.ts
> +        document.body.classList.toggle('core-reading-mode-multimedia-hidden', !settings.showMultimedia);
I think it's ok to leave it there, it defines the settings but disabled.

2024-12-18 07:06 UTC, dpalou approved these changes

2024-12-18 07:06 UTC, merged